-- ============================================================
-- StoiComunication V2 - Seed Track 1: Comunicación Estoica (PREMIUM)
-- 90 días + 13 retos semanales + 3 hitos mensuales
-- Fuentes: Robbins (Awaken the Giant Within), Solà Pastor, Voss,
--          Duhigg, Treasure, Gallo, Brown, Howes (Greatness Mindset,
--          School of Greatness, Mask of Masculinity), Lee, Martell
-- Idempotente: re-ejecutar ACTUALIZA el contenido existente.
-- ============================================================

-- ------------------------------------------------------------
-- DÍAS (90)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'comunicacion')
INSERT INTO stoic.program_days (track_id, day_number, phase, week, module, title, instructions, rationale, source_author)
SELECT t.id, v.day_number, v.phase, v.week, v.module, v.title, v.instructions, v.rationale, v.source_author
FROM t, (VALUES
  -- SEMANA 1: Diagnóstico y línea base
  (1, 1, 1, 'perception', 'Video de línea base', 'Grábate 3 minutos en video hablando de un tema de tu trabajo, sin preparar. Míralo dos veces: la primera solo escuchando (cuenta muletillas y mide palabras por minuto), la segunda solo mirando (postura, manos, ojos). Registra también tu nivel de nervios (1-5). Guarda video y métricas: son tu punto de partida y tu prueba del día 86.', 'Sin línea base no hay progreso medible. La confrontación con tu propia grabación es incómoda exactamente porque es el diagnóstico más honesto que existe: lo que el mundo ve y tú no.', 'Adrià Solà Pastor'),
  (2, 1, 1, 'perception', 'Benchmark de escucha', 'Pide a 5 personas clave de tu entorno (pareja, colegas, familia) que califiquen tu capacidad de escucha del 1 al 10, y que te digan una situación concreta donde escuchaste mal. Anota todo en silencio absoluto: sin justificarte, sin explicar, sin "sí pero". Eres un auditor recogiendo datos de un tercero: tú.', 'Este ejercicio de vulnerabilidad radical expone los puntos ciegos que ninguna auto-observación alcanza. Howes y Lee lo usan como punto de partida porque la nota ajena es la única línea base que tu ego no puede editar.', 'Chris Lee / Lewis Howes'),
  (3, 1, 1, 'perception', 'Mapa de conversaciones', 'Durante todo el día, clasifica cada conversación importante: ¿es práctica (resolver algo), emocional (sentirse escuchado) o social (conexión e identidad)? Anota tipo detectado y si tu respuesta correspondió al tipo. El error clásico: responder práctico a lo emocional. Cuenta cuántas veces lo hiciste hoy.', 'La mayoría de los malentendidos ocurren porque dos personas sostienen tipos distintos de conversación sin saberlo. Detectar el tipo antes de responder es la habilidad madre de todas las demás.', 'Charles Duhigg'),
  (4, 1, 1, 'perception', 'Inventario de muletillas', 'Revisa el video del día 1 y lista tus 3 muletillas dominantes ("eh", "este", "o sea", "digamos", "¿sí?"). Hoy solo detéctalas cuando salgan: no las corrijas todavía, cuenta. Pon una marca discreta en el cuaderno cada vez. Al final del día tendrás tu frecuencia real, que casi siempre es el triple de lo que creías.', 'La muletilla nace del miedo al silencio y opera bajo el radar de la conciencia. No puedes erradicar lo que no has contado primero: la métrica precede a la corrección.', 'Adrià Solà Pastor'),
  (5, 1, 1, 'perception', 'Auditoría de lenguaje corporal', 'Tres veces hoy (mañana, mediodía, tarde) haz una foto mental de tu postura: ¿hombros atrás y abajo o enrollados hacia el teléfono? ¿brazos cruzados? ¿manos visibles? ¿torso alineado con tu interlocutor? Corrige en el momento y nota el cambio inmediato de energía al corregir: no es casualidad, es bioquímica.', 'Robbins enseña que la fisiología es la palanca más rápida del estado: la postura no solo comunica hacia afuera — fabrica emoción hacia adentro. Dos minutos de postura expandida cambian lo que sientes y lo que proyectas.', 'Robbins / Solà'),
  (6, 1, 1, 'action', 'Calentamiento vocal', 'Antes de tu primera reunión: 1) respira profundo expandiendo el diafragma, 2) vibra los labios (lip trills) con sonido, 3) masajea la mandíbula y haz chasquidos con la lengua, 4) articula sílabas del tono más grave al más agudo. Total: 5 minutos. La voz es un instrumento físico: nadie sale a competir sin calentar.', 'Treasure enseña que la voz preparada gana resonancia y pierde tensión: la diferencia entre sonar dubitativo y sonar presente muchas veces es puramente muscular.', 'Julian Treasure'),
  (7, 1, 1, 'perception', 'Retro semana 1', 'Revisa tus métricas y registros de la semana y responde por escrito: ¿qué descubriste de tu comunicación que no sabías? ¿Qué dijeron los 5 del benchmark que más te dolió (ahí suele estar el oro)? Define tu objetivo número 1 de estos 90 días en una sola frase medible.', 'El ciclo actuar-registrar-ajustar es lo que separa la práctica deliberada de simplemente tener conversaciones. El dato que duele es el que señala el entrenamiento correcto.', 'Plan 90 días'),

  -- SEMANA 2: Fisiología, estado y voz (Robbins: la Tríada aplicada)
  (8, 1, 2, 'will', 'Priming matutino', 'Antes de tocar el celular: 10 minutos de manipulación deliberada del estado — postura expansiva (pecho abierto, mentón arriba), respiración 4-4-6 (inhala 4, retén 4, exhala 6) y una incantación en voz alta CON movimiento: "hoy hablo con calma y claridad". No es meditación pasiva: es encender el sistema a tu favor antes de que el día lo encienda en tu contra.', 'Robbins fundamenta todo su método en esto: el estado precede al desempeño, y la fisiología es la puerta de entrada al estado. Quien no gestiona su bioquímica matutina comunica todo el día desde el estado que le tocó, no desde el que eligió.', 'Tony Robbins'),
  (9, 1, 2, 'action', 'Pausa de 2 segundos', 'Durante todo el día, inserta una pausa deliberada de 2-3 segundos antes de responder cualquier pregunta importante. Permanece en silencio mientras organizas la idea, sosteniendo la mirada, sin rellenar con sonidos. La pausa se sentirá eterna para ti y natural para el otro: esa asimetría es normal y desaparece con la práctica.', 'La pausa transmite control emocional y procesamiento analítico. Treasure y Solà coinciden: quien tolera el micro-silencio proyecta el doble de autoridad que quien lo rellena.', 'Treasure / Solà'),
  (10, 1, 2, 'action', 'Ritmo a la mitad', 'En tu reunión más importante de hoy, habla deliberadamente al 50% de tu velocidad habitual. Usa la desaceleración — no el volumen — para enfatizar los puntos críticos. Te parecerá exageradamente lento; graba un fragmento si puedes y comprueba que desde afuera suena, simplemente, seguro.', 'La aceleración comunica ansiedad y miedo a perder el turno; el ritmo pausado comunica que el turno es tuyo y lo sabes. Robbins recomienda bajar a la mitad porque la percepción interna del orador siempre va al doble.', 'Tony Robbins'),
  (11, 1, 2, 'action', 'Melodía vocal', 'Grábate 2 minutos explicando algo técnico variando deliberadamente: graves y agudos, velocidad según el dramatismo, volumen entre susurro estratégico y proyección. Escucha la grabación: ¿hay música o hay línea plana? Repite una vez exagerando la variación hasta la caricatura: el punto óptimo real está más cerca de la caricatura que de tu costumbre.', 'El cerebro del oyente se habitúa a los estímulos constantes y los deja de procesar — como quien vive junto al mar deja de oír las olas. La variación es lo único que mantiene viva la atención.', 'Adrià Solà Pastor'),
  (12, 1, 2, 'will', 'Respiración táctica', 'Tres veces hoy, antes de hablar en reunión o llamada: inhala contando 4, exhala contando 6, tres ciclos. Úsala también si notas la voz temblar: el temblor no es falta de preparación, es tensión muscular por estrés social — y se apaga por la vía del cuerpo, no repasando las notas.', 'La exhalación larga activa el sistema parasimpático y le comunica al cerebro que no hay amenaza. Robbins lo aplica antes de cada escenario: primero el estado, después el contenido.', 'Tony Robbins'),
  (13, 1, 2, 'will', 'Vocabulario transformacional', 'Caza hoy 3 frases limitantes de tu diálogo interno y externo ("estoy abrumado", "seguro lo digo mal", "soy malo para esto") y reformúlalas en voz alta con vocabulario de menor intensidad negativa o mayor capacidad: "estoy organizando prioridades", "estoy afinando cómo decirlo", "estoy entrenando esto". Las palabras habituales no describen tu experiencia: la fabrican.', 'Robbins dedica un capítulo entero al vocabulario transformacional: cambiar la etiqueta verbal habitual de una emoción cambia su intensidad real. Quien dice "furioso" siente más furia que quien dice "molesto" ante el mismo hecho.', 'Tony Robbins'),
  (14, 1, 2, 'perception', 'Retro semana 2', 'Re-graba el video de 3 minutos del día 1 (mismo tema). Compara contra la línea base: ¿muletillas por minuto? ¿ritmo? ¿postura? ¿variación vocal? Anota los números y una sola cosa a reforzar la próxima semana. Dos grabaciones separadas por 14 días son la evidencia que tu autoduda no puede discutir.', 'Comparar grabaciones propias es la forma más rápida de convencer al cerebro escéptico de que el entrenamiento paga: la evidencia visual vence a la opinión interna.', 'Plan 90 días'),

  -- SEMANA 3: Escucha activa y tipos de conversación
  (15, 1, 3, 'perception', 'La pregunta explícita', 'En al menos una conversación importante de hoy pregunta directamente: "¿buscas que te ayude a resolver esto o que te escuche?". Y luego — la parte difícil — actúa según la respuesta, no según tu impulso de arreglar. Si pidió escucha, tu única tarea es que se sienta escuchado hasta que él mismo pida opciones.', 'Preguntar el tipo de conversación evita el error que más relaciones desgasta: dar soluciones cuando el otro necesitaba desahogo. Duhigg lo documenta como la marca distintiva de los supercomunicadores.', 'Charles Duhigg / Howes'),
  (16, 1, 3, 'perception', 'Filtros de escucha', 'Al inicio de tu reunión más importante, desactiva conscientemente tus expectativas y juicios previos sobre quien habla: la etiqueta que ya le pusiste, lo que "siempre dice", lo que esperas que pida. Atiende solo a los hechos y al tono de HOY, sin planear tu respuesta mientras habla. Al final verifica: ¿dijo algo que tu filtro habitual habría borrado?', 'Escuchamos a través de filtros (cultura, valores, expectativas, historia con la persona) que editan el mensaje antes de que llegue a la conciencia. Desactivarlos una reunión te muestra cuánto llevabas sin oír.', 'Julian Treasure'),
  (17, 1, 3, 'perception', 'Paráfrasis con emoción', 'En una conversación de hoy, devuelve un resumen de lo que la otra persona dijo incluyendo la emoción detectada: "parece que esta situación te está frustrando por la falta de claridad". Espera a que confirme — o te corrija — antes de dar tu opinión. La corrección también es victoria: ahora sabes qué siente de verdad.', 'La validación emocional garantiza al otro que fue procesado y comprendido, y desarma sus defensas antes de cualquier propuesta. Voss la usa con secuestradores; funciona mejor con colegas.', 'Chris Lee / Chris Voss'),
  (18, 1, 3, 'perception', 'Escucha sin ego', 'Elige una conversación y complétala sin interrumpir ni una vez: no completes frases, no edites mentalmente el mensaje, no prepares tu réplica mientras habla. Asume con humildad total que no sabes qué va a decir — aunque creas que sí. Cuando termine, cuenta hasta dos antes de responder.', 'Lee llama escucha egoísta a la que solo atiende los fragmentos que confirman los propios prejuicios. Suprimir el impulso de interrumpir es el músculo base: sin él, toda técnica de empatía es teatro.', 'Chris Lee'),
  (19, 1, 3, 'perception', 'Detecta el canal VAK', 'Observa a 2 personas cercanas: ¿procesan mejor viendo (visual: "no lo veo claro"), oyendo (auditivo: "no me suena") o haciendo (kinestésico: "no me cuadra")? Sus propias palabras te delatan su canal. Adapta cómo les explicas algo hoy: diagrama para el visual, narración para el auditivo, ejemplo manipulable para el kinestésico.', 'Adaptar el mensaje al canal dominante del receptor multiplica la comprensión sin cambiar el contenido: el rapport de Robbins empieza por hablar el dialecto sensorial del otro.', 'Tony Robbins'),
  (20, 1, 3, 'perception', 'El puente diferido', 'Retoma hoy un tema que alguien te mencionó hace días: "la semana pasada dijiste que ibas a hacer X, ¿cómo te fue?". Escucha con atención total la respuesta y haz una pregunta de seguimiento. Guarda en una nota los pendientes vitales de tu gente: es tu base de datos de consideración.', 'Recordar la vida del otro es de las señales de aprecio más potentes que existen: Howes la usa para construir las relaciones que sostienen su red. La gente olvida lo que dijiste; no olvida que la recordaste.', 'Lewis Howes'),
  (21, 1, 3, 'perception', 'Retro semana 3', 'Revisa tu registro de la semana: ¿cuántas conversaciones clasificaste bien (práctica/emocional/social)? ¿En cuántas escuchaste sin interrumpir? ¿Qué canal VAK domina en tu equipo? Nombra por escrito tu patrón de escucha más débil: será tu objetivo silencioso de las próximas semanas.', 'El registro semanal convierte impresiones vagas en datos accionables: la escucha se entrena con marcador, como cualquier deporte.', 'Plan 90 días'),

  -- SEMANA 4: Silencio estratégico y muletillas
  (22, 1, 4, 'action', 'Silencio estratégico', 'Después de tu frase más importante del día, haz una pausa total de 3 segundos sosteniendo la mirada, sin desviar los ojos ni asentir compulsivamente. Deja que el silencio pese: está trabajando para ti — subrayando lo que dijiste, dándole tiempo al otro de procesarlo, y demostrando que no necesitas aprobación inmediata.', 'El silencio es un multiplicador de tensión narrativa y autoridad. Solà insiste: muy pocos lo sostienen, y por eso dominarlo te separa instantáneamente del 99% de los emisores.', 'Adrià Solà Pastor'),
  (23, 1, 4, 'action', 'Guerra a las muletillas', 'Día de cero relleno: cada vez que notes que viene una muletilla, cállate. Prefiere el micro-silencio incómodo al ruido. Lleva la cuenta de las que se escaparon. Truco de emergencia: cierra la boca físicamente al terminar cada frase — la muletilla necesita la boca entreabierta para colarse.', 'Las muletillas son grietas acústicas que drenan credibilidad: reducen matemáticamente el valor percibido de lo que dices, por brillante que sea el contenido. Cada una le cobra impuesto a tu autoridad.', 'Adrià Solà Pastor'),
  (24, 1, 4, 'action', 'Pregunta de francotirador', 'Sustituye hoy una pregunta cerrada ("¿te gustó?") por una abierta, precisa y con intención ("¿qué fue lo que más te sorprendió de esto y por qué?"). Prepárala antes: la pregunta de francotirador se calibra, no se improvisa. Observa cuánto más revela la respuesta.', 'Las preguntas cerradas solo confirman tus sesgos; las grandes y calibradas obligan al otro a pensar de verdad y son portales a información que ni él sabía que tenía. La calidad de tus preguntas define la calidad de tus conversaciones — hacia afuera y hacia adentro.', 'Solà / Robbins'),
  (25, 1, 4, 'action', 'Status sin notas', 'Da tu actualización de estado al equipo sin leer notas. Estructura mental de tres puntos, pausas en lugar de relleno, y cierre claro. Si te pierdes, pausa en silencio, respira y retoma: perderse y recuperarse con calma proyecta más dominio que no perderse nunca.', 'Hablar sin guion entrena la confianza en tu propio procesamiento en vivo. La recuperación serena de un tropiezo es la prueba visible de control emocional.', 'Plan 90 días'),
  (26, 1, 4, 'action', 'Elevator pitch', 'Explica tu proyecto actual en 60 segundos exactos. Grábate. Escucha y elimina cada palabra innecesaria. Repite hasta que quepa con claridad y sin correr. Versión final: qué problema resuelve, para quién, qué cambia si funciona. Si sobra tiempo, sobraban palabras.', 'Comprimir sin perder claridad es el ejercicio de síntesis que revela si de verdad entiendes lo que haces. Martell lo exige a sus fundadores: si no cabe en un minuto, no está claro ni para ti.', 'Dan Martell'),
  (27, 1, 4, 'action', 'Micro-presentación de 5 minutos', 'Prepara y grábate una presentación de 5 minutos sobre un tema que domines, con estructura: apertura con intención (por qué esto importa AHORA) → mensaje central → cierre memorable (una frase que se lleven). Autoevalúa: claridad, contacto visual, emoción, muletillas por minuto.', 'La estructura apertura-mensaje-cierre es lo que convierte información en discurso que se recuerda. Solà: no te recuerdan por todo lo que dijiste sino por cómo abriste y cómo cerraste.', 'Adrià Solà Pastor'),
  (28, 1, 4, 'perception', 'Retro semana 4', 'Compara la presentación del día 27 con tu video del día 1: muletillas por minuto, ritmo, pausas, postura, variación vocal. Escribe el porcentaje de mejora en cada métrica y qué falta. Este es tu primer hito verificable: celebra el delta, no la perfección.', 'Cerrar el primer ciclo con datos duros consolida la identidad de comunicador en entrenamiento. Howes insiste: reconocer el progreso es parte del método, no vanidad.', 'Plan 90 días / Howes'),

  -- SEMANA 5: Cierre fase 1 + espejo táctico (Voss)
  (29, 1, 5, 'perception', 'Examen de fase 1', 'Escribe: ¿qué técnica del primer mes te costó más y por qué? ¿Cuál ya sale sola? ¿Qué dice eso de tu perfil (te cuesta más el silencio = ansiedad de aprobación; te cuesta más escuchar = necesidad de control)? Elige el punto débil que seguirás puliendo mientras arranca la fase 2.', 'La retrospectiva honesta y sin autoflagelación es el examen de Séneca aplicado al entrenamiento: juez justo del propio mes, ni fiscal ni fan.', 'Séneca / Plan 90 días'),
  (30, 1, 5, 'will', 'Día de integración', 'Ejecuta el día completo: priming matutino + calentamiento vocal + pausa deliberada + escucha sin ego + silencio estratégico + vocabulario vigilado. Todo en un mismo día. Nota al final cuáles piezas ya corren solas y cuáles todavía piden esfuerzo consciente: esas últimas son tu lista de repaso.', 'Integrar las piezas en un solo día demuestra que dejaron de ser ejercicios y empiezan a ser tu sistema operativo de comunicación.', 'Plan 90 días'),
  (31, 2, 5, 'action', 'Espejo táctico', 'En una conversación relevante, repite las últimas 1-3 palabras clave que tu interlocutor acaba de decir, con tono de pregunta (entonación ascendente). Luego calla. Observa cómo profundiza solo, sin que preguntaras nada. Úsalo mínimo 3 veces hoy en conversaciones distintas.', 'El espejo genera sintonía inconsciente e invita al otro a elaborar sin sentirse interrogado: Voss lo llama la herramienta con mejor relación simpleza-poder de toda la negociación.', 'Chris Voss'),
  (32, 2, 5, 'action', 'Espejo bajo fricción', 'Usa el espejo táctico en una conversación con tensión real (cliente molesto, jefe apurado, familiar irritado). Baja la velocidad, usa la voz calmada, repite sus palabras clave en tono inquisitivo y deja que se explique. Tu objetivo no es ganar el punto: es bajar la temperatura y obtener el mapa completo de su posición.', 'Bajo fricción, el espejo desacelera la escalada y le demuestra al otro que está siendo escuchado, no combatido. La información que suelte ahí vale más que cualquier argumento tuyo.', 'Chris Voss'),
  (33, 2, 5, 'action', 'Silencio post-espejo', 'Hoy, después de cada espejo, sostén un silencio absoluto de al menos 4 segundos. No lo rellenes aunque queme: el turno es del otro y el silencio es la presión suave que lo invita a usarlo. Cuenta mentalmente "mil uno, mil dos, mil tres, mil cuatro" si hace falta.', 'El silencio después del espejo es lo que obliga al interlocutor a llenar el vacío con la información que necesitas. Espejo sin silencio es solo eco.', 'Chris Voss'),
  (34, 2, 5, 'action', 'Espejo + paráfrasis', 'En una conversación difícil, encadena el protocolo completo: espejo de sus palabras clave → escucha → paráfrasis con la emoción detectada → espera su confirmación ("exacto", "así es") → solo entonces tu punto de vista. Sin saltarte pasos: el orden ES la técnica.', 'La secuencia espejo-paráfrasis-confirmación hace que el otro baje las defensas antes de que argumentes. Voss enseña que el "así es" del interlocutor es la campana que anuncia que ya puedes proponer.', 'Voss / Lee'),
  (35, 2, 5, 'perception', 'Retro semana 5', 'Documenta 2 casos de esta semana donde el espejo táctico reveló información que no habrías obtenido preguntando directamente. ¿Qué dijeron después del silencio? ¿En qué contexto te salió más natural y en cuál se sintió forzado? Calibra: el espejo forzado suena a burla; el natural, a interés.', 'Registrar los casos de éxito calibra tu confianza en la técnica y te enseña sus contextos óptimos. La herramienta se afina con bitácora.', 'Plan 90 días'),

  -- SEMANA 6: Etiquetado emocional y validación
  (36, 2, 6, 'action', 'Etiquetado emocional', 'Cuando notes tensión, resistencia o duda en alguien, etiquétala en voz alta sin usar "yo": "parece que hay cierta preocupación sobre los plazos", "suena a que esto te resulta injusto". Silencio absoluto después. Si aciertas, se descomprime; si fallas, te corrige con la emoción real. Ambos resultados ganan.', 'Nombrar la emoción del otro la disipa: la neurociencia muestra que etiquetar un afecto reduce la activación de la amígdala. Voss lo convirtió en el bisturí de la negociación.', 'Chris Voss'),
  (37, 2, 6, 'action', 'Etiqueta lo positivo', 'Hoy etiqueta también emociones positivas: "suena a que estás orgulloso de cómo quedó esto", "parece que este proyecto te entusiasma de verdad". Observa el efecto: la persona se expande, profundiza y te asocia con ese estado. Estás validando identidad, no solo ánimo.', 'Validar la emoción positiva amplifica el vínculo igual que etiquetar la negativa la disuelve. Howes lo practica en cada entrevista: la gente se abre ante quien celebra su fuego.', 'Voss / Howes'),
  (38, 2, 6, 'action', 'Auditoría de acusaciones', 'Antes de una conversación tensa, escribe lo peor que el otro podría estar pensando de ti ("crees que llego tarde con esto", "parece que no valoré tu trabajo") y dilo tú primero al inicio: "probablemente sientas que te dejé colgado con esto...". Nómbralo todo antes de que lo use.', 'Nombrar tú mismo las acusaciones les quita el veneno: es la vacuna de Voss. Lo no dicho opera como artillería enemiga; lo dicho por ti, como puente.', 'Chris Voss'),
  (39, 2, 6, 'action', 'Validación específica', 'Reconoce públicamente una contribución concreta de un colega describiendo la acción y su impacto: "tu análisis de ayer hizo que el cliente decidiera de inmediato". Nada de "buen trabajo" genérico: la especificidad es lo que lo vuelve real. Una vez al día, desde hoy.', 'El reconocimiento específico fortalece la relación y te posiciona como líder que ve el trabajo ajeno de verdad. Howes lo lista entre los hábitos del equipo ganador: la gente rinde para quien la ve.', 'Lewis Howes'),
  (40, 2, 6, 'action', 'Etiquetado por escrito', 'Aplica el etiquetado en un correo difícil: nombra la preocupación probable del lector antes de tu propuesta ("sé que esto puede parecer un cambio de alcance a última hora..."). Después la propuesta, corta y clara. Relee antes de enviar: ¿tu primer párrafo desarma o dispara?', 'El etiquetado escrito desarma la lectura defensiva igual que la voz lo hace en persona: el lector que se siente comprendido lee el resto con otra actitud.', 'Chris Voss'),
  (41, 2, 6, 'action', 'Combo completo', 'En una misma conversación importante encadena: espejo → etiqueta emocional → pregunta abierta calibrada. Ejemplo: "¿...el presupuesto?" (espejo) → "parece que hay presión desde arriba con este tema" (etiqueta) → "¿cómo podríamos presentarlo para que pase?" (calibrada). Registra qué obtuviste.', 'Las técnicas se potencian en secuencia: el espejo abre, la etiqueta valida y la pregunta abierta dirige. Es la coreografía básica de la empatía táctica completa.', 'Chris Voss'),
  (42, 2, 6, 'perception', 'Retro semana 6', 'Revisa la semana: ¿qué etiquetas funcionaron y cuáles sonaron falsas? ¿Usaste "yo" sin querer ("yo veo que estás molesto" en vez de "parece que...")? ¿Respetaste el silencio posterior? La etiqueta mal calibrada suena a manipulación; la retro te enseña el tono y el momento.', 'Las herramientas de empatía táctica requieren afinación personal: la misma frase en dos bocas suena a cuidado o a técnica. La bitácora es tu afinador.', 'Plan 90 días'),

  -- SEMANA 7: Preguntas calibradas y el poder del No
  (43, 2, 7, 'action', 'Pregunta calibrada', 'Sustituye hoy toda pregunta de confirmación ("¿estás de acuerdo?") por una calibrada que empiece con cómo o qué: "¿cómo podríamos resolver esto juntos?", "¿qué nos está impidiendo avanzar?". La calibrada no pide permiso: pide pensamiento. Y quien piensa contigo, construye contigo.', 'Las calibradas eliminan la confrontación, obligan al otro a reflexionar y le dan una ilusión de control que facilita la colaboración. Voss las llama las preguntas que hacen el trabajo por ti.', 'Chris Voss'),
  (44, 2, 7, 'action', 'Destierra el porqué', 'Reformula hoy todo "¿por qué hiciste X?" en "¿qué te llevó a X?" o "¿cómo llegaste a esa decisión?". El porqué acusa aunque no quieras; el qué y el cómo invitan a explicar sin defensa. Excepción única: "¿por qué harías esto?" cuando quieres que el otro defienda TU propuesta.', 'El "por qué" dispara defensividad universal: suena a fiscal. Voss reserva su única versión útil para cuando la defensa del otro juega a tu favor.', 'Chris Voss'),
  (45, 2, 7, 'action', 'El poder del No', 'Formula una petición como pregunta orientada al no: "¿sería descabellado considerar esta alternativa?", "¿te parece mala idea si lo intentamos así?". Observa cuánto más fácil responde el otro: decir "no, no es mala idea" lo deja en control y a ti te da el avance.', 'Perseguir el "sí" genera defensividad y compromisos falsos; el "no" da al otro seguridad psicológica. Voss invirtió la venta tradicional: la puerta se abre por el lado del no.', 'Chris Voss'),
  (46, 2, 7, 'action', '¿Cómo se supone que haga eso?', 'Ante una petición irrazonable de hoy (plazo imposible, alcance inflado), en lugar de aceptar sumisamente o quejarte, devuelve con calma y tono curioso: "¿cómo se supone que logre eso con los recursos actuales?". Y silencio. Deja que el problema vuelva a su dueño.', 'Esa pregunta traslada el problema a quien lo creó sin romper la relación: es un límite disfrazado de colaboración. Voss la llama la forma más elegante de decir no sin decirlo.', 'Chris Voss'),
  (47, 2, 7, 'action', '¿Hay algo más?', 'Cierra hoy 3 conversaciones con la pregunta expansiva "¿hay algo más que deba saber?" y escucha en silencio lo que salga. Lo más importante suele aparecer después de la que parecía la última pregunta: la expansiva le da permiso de salir.', 'Lee enseña que la información crítica espera a sentirse segura: la pregunta expansiva más el silencio construyen esa seguridad en cinco segundos.', 'Chris Lee'),
  (48, 2, 7, 'action', 'Negociación real', 'Negocia hoy un plazo, alcance o condición real usando el arsenal completo: etiqueta la presión del otro → pregunta calibrada → propuesta con límite claro ("para garantizar calidad, entrego la primera parte el viernes y el consolidado el lunes — ¿cómo afecta eso sus planes?"). Sin ceder por incomodidad: la incomodidad es la señal de que estás negociando de verdad.', 'Transformar la exigencia en problema conjunto consolida autoridad sin fricción. La preparación previa (etiquetas y calibradas escritas) es lo que te sostiene cuando la adrenalina quiera que cedas.', 'Chris Voss'),
  (49, 2, 7, 'perception', 'Retro semana 7', 'Documenta tu negociación de la semana de principio a fin: qué técnicas usaste, qué obtuviste, dónde cediste de más y qué señal corporal te avisó que estabas por ceder (todos tenemos una). ¿Qué harías distinto? La negociación se aprende en la revisión, no en el calor.', 'Voss insiste en la preparación y la revisión: el gran negociador no es el más agresivo sino el que más aprende de cada ronda.', 'Plan 90 días'),

  -- SEMANA 8: Storytelling (Gallo + identidad de Robbins)
  (50, 2, 8, 'action', 'Tu historia personal', 'Escribe una historia corta de tu experiencia con estructura reto → acción → lección. Cuéntala en voz alta 2 veces hasta que fluya. Regla de oro: la historia debe tener un momento de vulnerabilidad real (el error, el miedo, la duda) — sin él es un currículum, no una historia.', 'Las historias con vulnerabilidad conectan porque el oyente se ve en ellas. Howes construyó una carrera entera contando primero la herida y después la lección: ese orden es el que abre puertas.', 'Gallo / Howes'),
  (51, 2, 8, 'action', 'Sparkline', 'Presenta hoy una propuesta contrastando "lo que es" (situación actual con datos) contra "lo que podría ser" (la solución y sus beneficios), alternando dos o tres veces, y cierra con una llamada a la acción clara. La tensión entre presente y futuro es el motor narrativo más viejo del mundo: úsalo en tu próxima reunión.', 'La estructura de contraste mantiene la atención y hace evidente el valor del cambio: Gallo la identifica en los mejores discursos de la historia moderna.', 'Carmine Gallo'),
  (52, 2, 8, 'action', 'Regla de tres', 'Organiza tu próximo correo importante o intervención en exactamente 3 puntos, anunciados al inicio: "hoy abordaremos tres cosas: el diagnóstico, las opciones y la recomendación". Ni cuatro ni cinco: tres. Si tienes cinco, agrupa; si tienes dos, encuentra el tercero o admite que son dos.', 'El cerebro retiene tríadas de forma óptima: tres puntos evitan la sobrecarga y proyectan claridad ejecutiva. Es la estructura silenciosa de casi todo discurso memorable.', 'Carmine Gallo'),
  (53, 2, 8, 'action', 'Analogía técnica', 'Explica hoy un concepto técnico de tu trabajo (un ETL, un dashboard, una arquitectura) a alguien no técnico usando una analogía cotidiana. Verifica el aprendizaje: pídele que te lo explique de vuelta con sus palabras. Si no puede, la analogía era para ti, no para él.', 'Si no puedes explicarlo simple, no lo dominas todavía. Martell exige a los técnicos matar la jerga: la claridad es un acto de respeto y una ventaja competitiva.', 'Dan Martell'),
  (54, 2, 8, 'action', 'Framework CPPS', 'Usa la estructura Contexto → Problema → Propuesta → Siguiente paso en una reunión real. Escríbelo antes en 4 líneas, dilo, y al final pregunta: "¿quedó claro el siguiente paso?". Repítelo hasta que el equipo empiece a esperar ese formato de ti: acabas de instalar un estándar.', 'Un framework fijo y repetible hace que las ideas técnicas se entiendan a la primera y libera tu mente para la entrega. La estructura conocida reduce la carga cognitiva de todos.', 'Dan Martell'),
  (55, 2, 8, 'action', 'El dato envuelto en historia', 'Presenta hoy un avance o métrica envolviéndolo en una mini-historia: quién tenía el problema, qué pasaba, qué cambió con el trabajo. El número es el final de la historia, no el reemplazo de la historia. Compara la reacción con tus presentaciones habituales de solo cifras.', 'Los datos informan pero las historias mueven: el número dentro de una narrativa se recuerda, se repite y se defiende en tu ausencia — que es donde se toman las decisiones reales.', 'Carmine Gallo'),
  (56, 2, 8, 'perception', 'Retro semana 8', 'Revisa la semana: ¿cuál historia o estructura aterrizó mejor? ¿Dónde notaste que perdías a la audiencia (el momento exacto)? Elige tu estructura por defecto de ahora en adelante y escribe tu historia personal pulida en su versión final: entra al repertorio permanente.', 'Tener una estructura por defecto elimina la improvisación caótica bajo presión: los grandes comunicadores no improvisan la forma, solo el color.', 'Plan 90 días'),

  -- SEMANA 9: Rapport, exposición social y miedo al juicio (Howes)
  (57, 3, 9, 'action', 'Matching sutil', 'En 2 conversaciones de hoy, iguala sutilmente el ritmo, tono y energía de tu interlocutor (sin imitar gestos de forma obvia). Cuando notes la sintonía — el otro se relaja, fluye — lidera: baja tú el ritmo y observa si te sigue. Ese es el momento exacto en que el rapport se vuelve influencia.', 'El rapport se construye igualando primero (pacing) para poder guiar después (leading): Robbins enseña que la conexión biológica precede a la persuasión racional.', 'Tony Robbins'),
  (58, 3, 9, 'action', 'Comentario situacional', 'Rompe el hielo con un desconocido comentando el contexto compartido en tono neutro y amable (la fila, el clima, el lugar). Sin agenda: solo testear receptividad. Antes de hacerlo, nota el pico de resistencia interna — ese pico es el miedo al juicio trabajando, y hoy lo desobedeces en dosis mínima.', 'Howes identifica el miedo al juicio como uno de los tres asesinos de la grandeza: se desactiva con exposición en dosis, no con argumentos. El entorno común es el terreno más seguro para la primera dosis.', 'Howes / escalera social'),
  (59, 3, 9, 'action', '¿Qué te trajo por acá?', 'En un evento, curso o espacio compartido, acércate a alguien y pregunta: "¿qué te trajo por acá?". Haz una pregunta de seguimiento basada en lo que escuches. Estás saltando el small talk directo a las motivaciones — el terreno donde nace la conexión real.', 'Las preguntas sobre motivación abren más que las preguntas sobre hechos: Howes construyó su red de mentores empezando conversaciones exactamente así.', 'Howes / escalera social'),
  (60, 3, 9, 'action', 'Cumplido y retirada', 'Haz un cumplido genuino e impersonal a alguien (su reloj, su libro, su elección) y retírate inmediatamente después del gracias. Sin esperar conversación: el punto es dar valor social gratis y comprobar que puedes iniciar contacto sin necesitar nada de vuelta — ni siquiera la charla.', 'Dar sin esperar retorno entrena la abundancia social: quien no necesita la aprobación del otro conversa desde otra frecuencia. La retirada inmediata es lo que lo demuestra.', 'Escalera social'),
  (61, 3, 9, 'action', 'Tres minutos con alguien nuevo', 'Inicia una conversación de 2-3 minutos con alguien nuevo (gym, oficina, cafetería) buscando activamente un punto de afinidad: proyecto, hobby, contexto. Usa el arsenal ya entrenado: pregunta abierta, escucha sin ego, espejo si fluye. Cierra elegante: "un gusto, nos vemos por acá".', 'Buscar similitudes en lugar de diferencias reduce la distancia percibida y asienta la confianza. El cierre elegante importa tanto como la apertura: es lo último que recuerdan.', 'Escalera social'),
  (62, 3, 9, 'action', 'Cambia el canal', 'Toma un mensaje tuyo que no aterrizó esta semana y reformúlalo en otro canal: si fue verbal, hazlo diagrama; si fue escrito, explícalo en persona; si fue abstracto, hazlo demo. Documenta si mejoró la comprensión. Regla: antes de culpar al receptor, cambia el canal.', 'Cuando un mensaje no llega, el problema suele ser el canal, no el contenido ni el receptor. El comunicador maduro tiene tres versiones de cada mensaje importante.', 'Tony Robbins'),
  (63, 3, 9, 'perception', 'Retro semana 9', 'Dibuja tu escalera de exposición social: ¿qué peldaño ya es cómodo (saludos, small talk, conversación, grupos) y cuál sigue? ¿Qué te dijo el miedo al juicio esta semana y cuántas veces lo desobedeciste? Define el reto social de la próxima semana un peldaño arriba del cómodo.', 'La desensibilización funciona por gradiente: consolidar un peldaño antes de subir evita el retroceso. El miedo desobedecido en dosis pierde autoridad en grande.', 'Howes / Plan 90 días'),

  -- SEMANA 10: Asertividad y límites (Brown + Voss)
  (64, 3, 10, 'action', 'Límite sin disculpa excesiva', 'Di no hoy a algo que excede tu capacidad, con hechos y sin justificaciones en cadena: "no puedo asumir este proyecto ahora por las prioridades X e Y". Punto. Sin pedir perdón tres veces, sin inventar excusas decorativas. La brevedad del límite es su fuerza: cada justificación extra es una puerta que dejas abierta.', 'Ser claro es ser amable: los límites difusos generan resentimiento en ambas direcciones. Brown enseña que la gente más compasiva que existe es también la que tiene los límites más firmes.', 'Brené Brown'),
  (65, 3, 10, 'action', 'Expectativas explícitas', 'Al iniciar una tarea conjunta hoy, define por escrito con la otra parte: "¿cómo luce el éxito de este entregable?" y "¿qué obstáculos podrían impedirlo?". Dos preguntas, cinco minutos, y acabas de eliminar el 80% de los reproches futuros — que nacen casi siempre de supuestos nunca verbalizados.', 'Los supuestos no verbalizados son la semilla de los conflictos de equipo: la alineación explícita los mata de raíz. Es transparencia radical aplicada a lo cotidiano.', 'Brené Brown'),
  (66, 3, 10, 'action', 'Noticia incómoda sin sobre-justificar', 'Da hoy (o simula por escrito) una noticia incómoda — retraso, error, cambio — con la estructura: hecho, impacto, plan, siguiente paso. Sin justificarte de más: la sobre-justificación comunica culpa y debilita el mensaje; el plan comunica control. El que trae plan conserva la autoridad aunque traiga mal dato.', 'La forma de dar la mala noticia define tu reputación más que la noticia misma: el mensajero con plan se vuelve el líder de la solución.', 'Plan 90 días'),
  (67, 3, 10, 'action', 'No sé / me equivoqué', 'Di hoy en voz alta "no sé" o "me equivoqué" cuando corresponda, sin minimizarlo ni adornarlo, sosteniendo la mirada. Es el día de quitarse la máscara del sabelotodo: la que exige tener siempre la respuesta y convierte cada conversación en un examen.', 'Howes describe la máscara del sabelotodo como una de las más caras: bloquea el aprendizaje y la conexión a la vez. Admitir el error sin drama proyecta más autoridad que fingir certeza — y da permiso al equipo de reportar los suyos.', 'Howes / Brown'),
  (68, 3, 10, 'action', 'Claro es amable', 'Reescribe y envía hoy ese mensaje ambiguo que llevas días evitando (el recordatorio, la corrección, la petición). Versión corta, clara y respetuosa: etiqueta si ayuda ("sé que esto puede caer pesado..."), hecho, petición concreta. Lo que se evita por incomodidad se cobra con intereses.', 'La claridad temprana es el menor de los males: Brown enseña que la falta de claridad es falta de amabilidad disfrazada de tacto.', 'Brené Brown'),
  (69, 3, 10, 'action', 'Contacto visual sostenido', 'Tras emitir tu propuesta o respuesta importante de hoy, sostén el contacto visual en silencio total 3-5 segundos. No desvíes la mirada ni asientas compulsivamente. El contacto sostenido comunica convicción; desviarlo por timidez es sumisión social refleja — y hoy la reescribes.', 'La mirada sostenida tras la propuesta es el sello no verbal de la convicción: sin ella, hasta la mejor propuesta parece pregunta.', 'Escalera social nivel 4'),
  (70, 3, 10, 'perception', 'Retro semana 10', '¿Qué límite te costó más poner esta semana y qué pasó realmente después de ponerlo? Compara la catástrofe imaginada con la reacción real: casi siempre el mundo responde mejor de lo que el miedo prometió. Documenta esa brecha — es tu evidencia contra la próxima vez que el miedo negocie.', 'Documentar que el mundo no se acabó tras el límite reeduca al cerebro que lo temía: el expediente de límites puestos es el antídoto del complaciente crónico.', 'Plan 90 días / Howes'),

  -- SEMANA 11: Feedback y liderazgo (Martell + Howes: equipo)
  (71, 3, 11, 'action', 'Feedback SBI', 'Da hoy un feedback usando Situación → Comportamiento → Impacto: "en la reunión de ayer (S), cuando interrumpiste la demo (C), el cliente perdió el hilo de la propuesta (I)". Sin juicios de carácter ("eres impulsivo"): solo conducta observable y su efecto. Cierra con pregunta: "¿cómo lo viste tú?".', 'El SBI separa la conducta de la persona: hace el feedback recibible y accionable. El juicio de carácter activa defensa; el dato de impacto activa reflexión.', 'Plan 90 días'),
  (72, 3, 11, 'action', 'Regla 1-3-1 hacia arriba', 'Lleva hoy un problema a tu jefe o equipo en formato 1-3-1: un (1) problema definido con precisión y contexto, tres (3) opciones viables analizadas, una (1) recomendación argumentada. Llegar con el problema masticado te convierte en la persona que trae soluciones — la reputación más valiosa que existe en una organización.', 'Martell instaló el 1-3-1 para acelerar decisiones y eliminar la cultura de la queja: quien lo usa hacia arriba se vuelve promovible; quien lo exige hacia abajo, escalable.', 'Dan Martell'),
  (73, 3, 11, 'action', 'Instala el 1-3-1', 'Cuando alguien te traiga hoy un problema, no lo resuelvas: pídele que vuelva con 3 opciones y una recomendación. Acompaña sin dar la respuesta — aunque la tengas y aunque sea más rápido dársela. Estás comprando su desarrollo con tu incomodidad de corto plazo.', 'Resolver todo tú crea dependencia y te convierte en el cuello de botella: Martell enseña a delegar el problema, no la tarea. El criterio ajeno solo crece donde tu respuesta no llega primero.', 'Dan Martell'),
  (74, 3, 11, 'action', 'Cede la palabra', 'En una junta de hoy, haz brillar activamente a alguien más: "X trabajó a fondo esto, ¿nos cuentas cómo lo resolviste?". Resiste el impulso de completar sus frases o de coronar su explicación con la tuya. El protagonismo cedido con intención vuelve multiplicado en lealtad y en información.', 'Ceder el escenario es la señal de estatus más contraintuitiva del liderazgo: Howes la ve en todos los grandes — el que menos necesita brillar es el que más luz controla.', 'Howes / Plan 90 días'),
  (75, 3, 11, 'action', 'Feedforward', 'Después de tu intervención más importante de hoy, pregunta a alguien de confianza: "¿qué puedo mejorar la próxima vez?". Escucha sin defenderte — ni una aclaración — y agradece. Pedir mejora futura en vez de evaluación pasada hace la crítica fácil de dar y de recibir.', 'El feedforward desarma al crítico y al criticado a la vez: nadie se defiende del futuro. Robbins lo llama retroalimentación de campeones: los mejores la piden, no la esperan.', 'Robbins / Plan 90 días'),
  (76, 3, 11, 'action', 'Delega el problema, no la tarea', 'Entrega hoy la propiedad completa de un problema (contexto, criterio de éxito, restricciones, fecha) en lugar de una lista de tareas fraccionadas. Define el qué y el para cuándo; el cómo es del dueño nuevo. Tu única regla: no rescatarlo al primer tropiezo.', 'Delegar tareas crea microgestión; delegar problemas crea pensamiento crítico y responsabilidad por el resultado. Es la diferencia entre tener ayudantes y formar sucesores.', 'Dan Martell'),
  (77, 3, 11, 'perception', 'Retro semana 11', '¿Qué cambió en tu entorno al usar 1-3-1, SBI y delegación de problemas? ¿Quién respondió mejor y quién resistió? Anota a quién le seguirás exigiendo el formato y qué harás con quien lo esquiva. Los sistemas de comunicación se consolidan midiendo su efecto en los demás.', 'El liderazgo comunicativo se verifica en la conducta ajena: si tu equipo empieza a llegar con opciones en vez de quejas, el sistema prendió.', 'Dan Martell'),

  -- SEMANA 12: Conflicto, disidencia y vulnerabilidad (Voss + Howes: máscaras)
  (78, 3, 12, 'action', 'Aclaración directa', 'Agenda 10 minutos con alguien con quien hubo un roce o malentendido reciente. Expón el hecho neutro: "vi X en tu correo; quiero asegurarme de que estamos alineados, ¿qué perspectiva tienes?". Sin acusación, sin víctima: dos adultos revisando un dato. La mayoría de los conflictos mueren en esta conversación de 10 minutos que casi nadie tiene.', 'La confrontación temprana basada en hechos evita la escalada pasivo-agresiva que pudre las relaciones. El conflicto evitado no desaparece: fermenta.', 'Plan 90 días / Voss'),
  (79, 3, 12, 'action', 'Disidencia racional', 'Expresa hoy una opinión contraria a la mayoría o a tu superior con preámbulo neutral: "veo el valor de A; sin embargo, en B encuentro un riesgo crítico. Propongo esta alternativa...". Di tu verdad con estructura y sin pedir perdón por tenerla. El conformismo también es una máscara — la del que prefiere caer bien a ser útil.', 'Vencer el conformismo grupal anteponiendo la verdad racional gana respeto intelectual duradero. Howes insiste: la grandeza exige la incomodidad de la voz propia.', 'Howes / Plan 90 días'),
  (80, 3, 12, 'action', 'Empatía táctica en caliente', 'En el próximo desacuerdo, antes de argumentar, resume la posición del otro hasta que diga "exacto" o "así es". Solo entonces presenta la tuya. Si la discusión sube de temperatura, vuelve al resumen: es tu botón de reinicio. Nadie escucha tu argumento mientras siente que no entendiste el suyo.', 'El "así es" del otro es la campana de Voss: señala que las defensas bajaron y el canal se abrió. Argumentar antes de oírla es hablar con la puerta cerrada.', 'Chris Voss'),
  (81, 3, 12, 'action', 'LA conversación pendiente', 'Ten hoy la conversación difícil que llevas semanas posponiendo. Prepárala por escrito: auditoría de acusaciones, etiquetas probables, calibradas, tu límite claro y tu mejor alternativa si no hay acuerdo. Ejecútala con el estado gestionado (respiración táctica antes de entrar). La conversación evitada gobierna tu energía desde la sombra; tenerla es recuperar el mando.', 'Todo lo entrenado en 81 días existe para este momento: las conversaciones que evitas son la frontera exacta de tu crecimiento.', 'Integración'),
  (82, 3, 12, 'action', 'Comunicación de crisis', 'Simulacro por escrito: redacta cómo comunicarías un fallo grave de tu responsabilidad. Estructura: qué pasó, impacto real, qué estamos haciendo, cuándo habrá noticias. Sin culpables, sin adornos, sin minimizar. Léelo en voz alta con voz calmada: en crisis, tu tono ES el mensaje.', 'En crisis, la transparencia estructurada y la calma comunican más liderazgo que cualquier discurso: la gente no recuerda el fallo, recuerda quién sostuvo el timón.', 'Plan 90 días'),
  (83, 3, 12, 'action', 'Vulnerabilidad estratégica', 'Comparte hoy con tu equipo un error propio y la lección que te dejó. Breve, sin drama y con la lección clara. Es el día de quitarse la máscara del invencible: la que exige no mostrar grieta jamás — y que, según descubrió Howes, es la que más aísla a quien la carga.', 'La vulnerabilidad del líder da permiso al equipo de reportar errores a tiempo: es infraestructura de confianza. Howes documentó que detrás de cada máscara hay conexión esperando: quitársela primero es liderar.', 'Howes / Brown'),
  (84, 3, 12, 'perception', 'Retro semana 12', 'Bajo presión, ¿cuál es tu patrón: luchar, huir o congelarte? Identifícalo con ejemplos de la semana y escribe qué técnica concreta lo contrarresta (¿luchar → resumen hasta el "así es"? ¿huir → la cita agendada que no puedes esquivar? ¿congelarte → respiración + calibrada memorizada?). Conocer tu default es poder instalarle un interruptor.', 'La respuesta automática al conflicto no se elimina: se le instala un protocolo delante. El estoico no confía en su temple del momento — confía en su preparación.', 'Plan 90 días'),

  -- SEMANA 13: Evaluación final
  (85, 3, 13, 'evaluation', 'Preparación de la presentación final', 'Prepara una presentación de 10 minutos sobre un tema tuyo (proyecto, propuesta, pasión) que integre todo: apertura con intención, 3 puntos, una historia con vulnerabilidad real, datos envueltos en narrativa y cierre memorable. Diseña también tu estado: qué priming harás antes, qué incantación, qué ancla física.', 'La presentación final es el examen integrador: cada técnica de los 90 días tiene su lugar en ella — incluida la gestión del estado, que es la que sostiene a todas las demás.', 'Evaluación'),
  (86, 3, 13, 'evaluation', 'Ensayo grabado', 'Graba la presentación completa. Cuenta muletillas, mide ritmo, pausas y variación vocal. Ponla al lado de tu video del día 1 y mira ambos: esa distancia es tu progreso objetivo, en video, innegable. Anota los números finales de tus métricas.', 'La comparación día 1 vs día 86 convierte 90 días de esfuerzo en evidencia irrefutable: es el expediente completo presentado al juez más escéptico — tú.', 'Evaluación'),
  (87, 3, 13, 'evaluation', 'Ejecución ante audiencia real', 'Presenta ante una audiencia real: tu equipo, colegas o familia. Ejecuta tu ritual de estado antes de entrar. Al terminar, pide feedback específico: ¿mensaje claro? ¿siguiente paso claro? ¿qué sobró? El escenario real es el único validador final: los nervios ante gente de verdad no se simulan.', 'La grandeza se demuestra en el campo, no en el ensayo: presentar ante personas reales cierra el ciclo que la grabación solo aproxima.', 'Evaluación / Howes'),
  (88, 3, 13, 'evaluation', 'Revisión de registros', 'Relee todas tus retros semanales. Identifica el patrón débil que más se repitió en los 90 días (interrumpir, cerrar mal, evitar límites, correr al hablar, rellenar silencios...). Escríbelo sin suavizarlo: tu patrón más repetido es tu próximo programa de entrenamiento.', 'Las 12 retros juntas dibujan el mapa que ninguna semana aislada muestra: los patrones solo se ven en serie.', 'Evaluación'),
  (89, 3, 13, 'evaluation', 'Mini-plan de 30 días', 'Diseña un mini-plan de 30 días enfocado únicamente en tu punto débil dominante: un ejercicio diario, una métrica, una retro semanal. Un solo frente: la concentración de fuerza es lo que convierte una debilidad crónica en una fortaleza nueva.', 'El progreso post-programa depende de enfocar un frente a la vez: el que entrena todo a la vez después del día 90, en dos semanas no entrena nada.', 'Evaluación'),
  (90, 3, 13, 'evaluation', 'Evaluación final: celebra la voz nueva', 'Abre el informe de 90 días en la app: progreso por módulo, rachas, días perdidos, consistencia. Escribe tu retro final: qué eres capaz de decir hoy — y a quién — que el día 1 era impensable. Y celebra de verdad: la constancia de 90 días de práctica deliberada es un logro que la mayoría jamás intenta.', 'La evidencia dice qué pasó; tu relato decide qué significa; la celebración le enseña al sistema nervioso que este camino paga. Ya no practicas comunicación: eres un comunicador que entrena.', 'Evaluación / Howes')
) AS v(day_number, phase, week, module, title, instructions, rationale, source_author)
ON CONFLICT (track_id, day_number) DO UPDATE SET
  phase = EXCLUDED.phase,
  week = EXCLUDED.week,
  module = EXCLUDED.module,
  title = EXCLUDED.title,
  instructions = EXCLUDED.instructions,
  rationale = EXCLUDED.rationale,
  source_author = EXCLUDED.source_author;

-- ------------------------------------------------------------
-- RETOS SEMANALES (13)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'comunicacion')
INSERT INTO stoic.program_weeks (track_id, week_number, theme, challenge_title, challenge_description, deliverable)
SELECT t.id, v.week_number, v.theme, v.challenge_title, v.challenge_description, v.deliverable
FROM t, (VALUES
  (1, 'Diagnóstico y línea base', 'Establece tu punto de partida', 'Graba tu video diagnóstico de 3 minutos, consigue que 5 personas califiquen tu escucha del 1 al 10 (con un ejemplo concreto cada una) y clasifica tus conversaciones de la semana por tipo.', 'Video del día 1 + tabla de métricas (muletillas, palabras/min, nervios) + 5 calificaciones de escucha con sus ejemplos.'),
  (2, 'Estado y voz', 'Ritual de priming 7 días seguidos', 'Ejecuta el priming matutino (postura + respiración 4-4-6 + incantación con movimiento) los 7 días antes de tocar el celular, y practica el vocabulario transformacional a diario.', 'Registro diario del ritual + lista de las 3 reformulaciones de vocabulario que más usaste.'),
  (3, 'Escucha activa', 'Tres conversaciones deliberadas', 'Practica en 3 conversaciones reales: identifica el tipo (práctica/emocional/social), pregunta explícitamente qué necesita el otro, parafrasea con emoción y escucha una conversación completa sin interrumpir.', 'Registro de 6 conversaciones con tipo identificado, aciertos y la paráfrasis que mejor funcionó.'),
  (4, 'Silencio y estructura', 'Presentación simulada de 5 minutos', 'Prepara, graba y autoevalúa una presentación de 5 minutos con apertura → mensaje → cierre memorable, usando pausas en lugar de muletillas y contacto visual sostenido.', 'Video + autoevaluación (claridad, contacto visual, muletillas/min) + comparación numérica contra el día 1.'),
  (5, 'Espejo táctico', 'El espejo en el mundo real', 'Usa el espejo táctico (últimas palabras clave en tono de pregunta + 4 segundos de silencio) en al menos 3 conversaciones reales, incluida una con fricción.', '2 casos documentados donde el espejo reveló información inesperada + qué dijeron tras el silencio.'),
  (6, 'Etiquetado emocional', 'Etiqueta bajo tensión', 'Aplica el etiquetado en una conversación difícil real (sin usar "yo", con silencio posterior), haz una auditoría de acusaciones antes de una conversación tensa y da una validación específica diaria.', 'Registro: qué etiquetas usaste, cómo reaccionó el otro, y la auditoría de acusaciones escrita.'),
  (7, 'Preguntas calibradas', 'Una negociación real', 'Negocia algo real esta semana (plazo, alcance, condición) usando calibradas, preguntas orientadas al no, "¿cómo se supone que haga eso?" y un límite claro sin romper la relación.', 'Documento de la negociación: técnicas usadas, resultado obtenido y dónde estuviste a punto de ceder.'),
  (8, 'Storytelling', 'Propuesta con estructura', 'Presenta una propuesta o avance real usando sparkline (lo que es vs lo que podría ser), la regla de tres y un dato envuelto en historia, y pide feedback directo.', 'La propuesta escrita + el feedback recibido + tu historia personal pulida en versión final.'),
  (9, 'Exposición social', 'Sube un peldaño de la escalera', 'Completa 3 microinteracciones con desconocidos (comentario situacional, "¿qué te trajo por acá?", cumplido con retirada) registrando el pico de miedo al juicio antes de cada una.', 'Registro de las 3 interacciones: qué dijiste, cómo respondieron y cuánto midió el miedo antes vs después.'),
  (10, 'Asertividad y límites', 'Dos límites claros', 'Pon 2 límites reales esta semana: un no con hechos y sin disculpas en cadena, y una expectativa explícita por escrito. Incluye un "no sé" o "me equivoqué" dicho sin adornos.', 'Qué dijiste exactamente, qué pasó después y la brecha entre la catástrofe imaginada y la reacción real.'),
  (11, 'Liderazgo comunicativo', 'Instala el 1-3-1', 'Usa el 1-3-1 hacia arriba (con tu jefe) y hacia abajo (exígelo ante un problema que te traigan), da un feedback SBI y delega un problema completo en vez de tareas.', 'El primer problema recibido en formato 1-3-1 + tu feedback SBI documentado + el problema delegado.'),
  (12, 'Conflicto y vulnerabilidad', 'La conversación pendiente', 'Ten LA conversación difícil que llevas posponiendo, preparada con auditoría de acusaciones, etiquetas y calibradas. Comparte además un error propio con tu equipo (máscara del invencible, fuera).', 'Retro escrita de la conversación: qué preparaste, qué pasó, qué aprendiste + el error compartido y su efecto.'),
  (13, 'Evaluación final', 'Presentación de graduación', 'Presenta 10 minutos ante audiencia real integrando todo el arsenal (estado, estructura, historia, silencio), compara tus métricas finales contra el día 1 y cierra con tu retro de 90 días.', 'Video final + comparación numérica día 1 vs día 86 + documento de retro + mini-plan de 30 días.')
) AS v(week_number, theme, challenge_title, challenge_description, deliverable)
ON CONFLICT (track_id, week_number) DO UPDATE SET
  theme = EXCLUDED.theme,
  challenge_title = EXCLUDED.challenge_title,
  challenge_description = EXCLUDED.challenge_description,
  deliverable = EXCLUDED.deliverable;

-- ------------------------------------------------------------
-- HITOS MENSUALES (3)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'comunicacion')
INSERT INTO stoic.program_months (track_id, month_number, title, description)
SELECT t.id, v.month_number, v.title, v.description
FROM t, (VALUES
  (1, 'Fundamentos: estado, voz y escucha', 'Dominar la gestión del estado (priming, Tríada, respiración táctica, vocabulario transformacional de Robbins), la voz (melodía, ritmo, silencio estratégico de Solà) y la escucha activa (tipos de conversación de Duhigg, paráfrasis, escucha sin ego de Lee). Hito verificable: el video del día 28 muestra al menos 50% menos muletillas por minuto que el del día 1, con métricas comparadas por escrito.'),
  (2, 'Persuasión: negociación y storytelling', 'Integrar el arsenal completo de Voss (espejo, etiquetado, auditoría de acusaciones, calibradas, el poder del No) y las estructuras narrativas (sparkline y regla de tres de Gallo, CPPS de Martell, la historia personal con vulnerabilidad de Howes) en el trabajo real. Hito verificable: una negociación real documentada con resultado favorable + una propuesta presentada con estructura narrativa y feedback recibido.'),
  (3, 'Liderazgo: límites, conflicto y voz propia', 'Consolidar la asertividad (límites sin disculpa de Brown, expectativas explícitas), los sistemas de liderazgo (1-3-1 y delegación de problemas de Martell, SBI, feedforward), el manejo del conflicto (empatía táctica en caliente) y la caída de las máscaras (sabelotodo, invencible — Howes). Hito verificable: presentación final de 10 minutos ante audiencia real + la conversación difícil pendiente, tenida y documentada.')
) AS v(month_number, title, description)
ON CONFLICT (track_id, month_number) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description;
