-- ============================================================
-- StoiComunication V2 - Seed Track 1: Comunicación Estoica
-- 90 días + 13 retos semanales + 3 hitos mensuales
-- Fuentes: Robbins, Solà Pastor, Voss, Duhigg, Treasure,
--          Gallo, Brown, Howes, Lee, Martell
-- ============================================================

-- ------------------------------------------------------------
-- DÍAS (90)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'comunicacion')
INSERT INTO stoic.program_days (track_id, day_number, phase, week, module, title, instructions, rationale, source_author)
SELECT t.id, v.day_number, v.phase, v.week, v.module, v.title, v.instructions, v.rationale, v.source_author
FROM t, (VALUES
  -- SEMANA 1: Diagnóstico y línea base
  (1, 1, 1, 'perception', 'Video de línea base', 'Grábate 3 minutos en video hablando de un tema de tu trabajo. Luego míralo y registra: número de muletillas, palabras por minuto y nivel de nervios (1-5). Guarda estas métricas: son tu punto de partida.', 'Sin línea base no hay progreso medible. La confrontación visual con tu propio discurso es el diagnóstico más honesto que existe.', 'Adrià Solà Pastor'),
  (2, 1, 1, 'perception', 'Benchmark de escucha', 'Pide a 5 personas clave de tu entorno (pareja, colegas, familia) que califiquen tu capacidad de escucha del 1 al 10. Anota las respuestas y comentarios en silencio, sin justificarte ni replicar.', 'Este ejercicio de vulnerabilidad expone tus puntos ciegos y te da una línea base innegable sobre la cual construir.', 'Chris Lee / Lewis Howes'),
  (3, 1, 1, 'perception', 'Mapa de conversaciones', 'Durante todo el día, clasifica cada conversación importante: ¿es práctica (resolver algo), emocional (sentirse escuchado) o social (conexión)? Anota fecha, tipo detectado y si acertaste.', 'La mayoría de los malentendidos ocurren porque dos personas sostienen tipos distintos de conversación sin saberlo.', 'Charles Duhigg'),
  (4, 1, 1, 'perception', 'Inventario de muletillas', 'Revisa el video del día 1 y lista tus 3 muletillas dominantes ("eh", "este", "o sea", "digamos"). Hoy dedícate solo a detectarlas cuando salgan: no las corrijas todavía, solo cuenta.', 'La muletilla nace del miedo al silencio. No puedes erradicar lo que no has hecho consciente primero.', 'Adrià Solà Pastor'),
  (5, 1, 1, 'perception', 'Auditoría de lenguaje corporal', 'Tres veces hoy (mañana, mediodía, tarde) haz una foto mental de tu postura: ¿hombros atrás y abajo? ¿brazos cruzados? ¿manos visibles? ¿torso alineado con tu interlocutor? Corrige en el momento.', 'La presencia no verbal influye en tus hormonas de estrés y en la percepción de confianza que proyectas, antes de decir una palabra.', 'Adrià Solà Pastor'),
  (6, 1, 1, 'action', 'Calentamiento vocal', 'Antes de tu primera reunión: 1) respira profundo expandiendo el diafragma, 2) vibra los labios (lip trills), 3) masajea mandíbula y haz chasquidos con la lengua, 4) articula sílabas del tono más grave al más agudo. Total: 5 minutos.', 'Preparar la voz mejora la resonancia, reduce la tensión vocal y proyecta seguridad desde la primera frase del día.', 'Julian Treasure'),
  (7, 1, 1, 'perception', 'Retro semana 1', 'Revisa tus métricas y registros de la semana. Responde por escrito: ¿qué descubriste de tu comunicación que no sabías? Define tu objetivo número 1 para estos 90 días en una sola frase.', 'El ciclo actuar-registrar-ajustar es lo que separa la práctica deliberada de simplemente tener conversaciones.', 'Plan 90 días'),

  -- SEMANA 2: Fisiología, respiración y voz
  (8, 1, 2, 'will', 'Priming matutino', 'Antes de tocar el celular: 10 minutos de postura expansiva (pecho abierto, mentón arriba) + respiración 4-4-6 (inhala 4, retén 4, exhala 6) + una incantación en voz alta con movimiento ("hoy hablo con calma y claridad").', 'La fisiología precede al pensamiento: cambiar postura y respiración altera tu bioquímica antes de que la mente racional pueda sabotearte.', 'Tony Robbins'),
  (9, 1, 2, 'action', 'Pausa de 2 segundos', 'Durante todo el día, inserta una pausa deliberada de 2-3 segundos antes de responder cualquier pregunta importante. Permanece en silencio mientras organizas la idea, sin rellenar con sonidos.', 'La pausa transmite control emocional, genera expectación y demuestra que procesas la información de forma analítica, no reactiva.', 'Julian Treasure / Solà'),
  (10, 1, 2, 'action', 'Ritmo a la mitad', 'En tu reunión más importante de hoy, habla deliberadamente al 50% de tu velocidad habitual. Usa la desaceleración en los puntos críticos en lugar de subir el volumen.', 'El ritmo pausado facilita la asimilación y proyecta seguridad incuestionable; la aceleración denota ansiedad y miedo a perder la atención.', 'Tony Robbins'),
  (11, 1, 2, 'action', 'Melodía vocal', 'Grábate 2 minutos explicando algo técnico variando deliberadamente: graves y agudos, velocidad según el dramatismo, y volumen. Escucha la grabación: ¿suenas monótono o hay música?', 'El cerebro ignora los estímulos constantes como quien vive frente al mar deja de oír las olas. La variación es lo único que mantiene al oyente despierto.', 'Adrià Solà Pastor'),
  (12, 1, 2, 'will', 'Respiración táctica', 'Tres veces hoy, antes de hablar en una reunión o llamada: inhala contando 4, exhala contando 6, repite 3 veces. Hazlo también si notas que la voz te tiembla.', 'El temblor de voz no es falta de preparación: es tensión muscular por estrés social. La exhalación larga activa el sistema parasimpático y le dice al cerebro que no hay amenaza.', 'Tony Robbins'),
  (13, 1, 2, 'will', 'Lenguaje interno', 'Caza hoy 3 frases limitantes de tu diálogo interno ("estoy abrumado", "seguro lo digo mal", "no soy bueno para esto") y reformúlalas en voz alta en versión de capacidad ("estoy aprendiendo a manejar esta complejidad").', 'El lenguaje moldea el significado de la experiencia: el vocabulario de limitación produce profecías autocumplidas.', 'Tony Robbins'),
  (14, 1, 2, 'perception', 'Retro semana 2', 'Re-graba el video de 3 minutos del día 1 (mismo tema). Compara: ¿muletillas? ¿ritmo? ¿postura? Anota las diferencias numéricas y una cosa a reforzar la próxima semana.', 'Comparar grabaciones tuyas separadas por días es la evidencia objetiva de progreso que tu cerebro necesita para sostener el hábito.', 'Plan 90 días'),

  -- SEMANA 3: Escucha activa y tipos de conversación
  (15, 1, 3, 'perception', 'La pregunta explícita', 'En al menos una conversación importante de hoy pregunta directamente: "¿buscas que te ayude a resolver esto o que te escuche?". Actúa según la respuesta, no según tu impulso.', 'Preguntar el tipo de conversación evita el error clásico: dar soluciones cuando el otro necesitaba desahogo, o consolar cuando pedía ayuda práctica.', 'Charles Duhigg / Howes'),
  (16, 1, 3, 'perception', 'Filtros de escucha', 'Al inicio de tu reunión más importante, haz el esfuerzo consciente de desactivar tus expectativas y juicios previos sobre quien habla. Atiende solo a los hechos y al tono, sin planear tu respuesta mientras el otro habla.', 'Escuchamos a través de filtros (cultura, valores, expectativas) que distorsionan el mensaje. Desactivarlos reduce los malentendidos de raíz.', 'Julian Treasure'),
  (17, 1, 3, 'perception', 'Paráfrasis con emoción', 'En una conversación de hoy, devuelve un resumen de lo que la otra persona dijo incluyendo la emoción detectada: "parece que esta situación te está frustrando por la falta de claridad". Espera a que confirme antes de dar tu opinión.', 'La validación emocional garantiza al otro que fue procesado y comprendido, y desarma sus defensas antes de cualquier propuesta.', 'Chris Lee / Chris Voss'),
  (18, 1, 3, 'perception', 'Escucha sin interrumpir', 'Elige una conversación y complétala sin interrumpir ni una vez: no completes frases, no edites mentalmente el mensaje, no prepares tu réplica. Asume que no sabes qué va a decir.', 'La escucha egoísta solo atiende los fragmentos que confirman los propios prejuicios. Suprimir el impulso de interrumpir es el músculo base de la empatía.', 'Chris Lee'),
  (19, 1, 3, 'perception', 'Detecta el canal VAK', 'Observa a 2 personas cercanas: ¿procesan mejor viendo (visual), oyendo (auditivo) o haciendo (kinestésico)? Adapta cómo les explicas algo: diagrama vs explicación verbal vs dejar que lo prueben.', 'Adaptar el mensaje al canal dominante del receptor multiplica la comprensión sin cambiar el contenido.', 'Tony Robbins'),
  (20, 1, 3, 'perception', 'El puente diferido', 'Retoma hoy un tema que alguien te mencionó hace días: "la semana pasada dijiste que ibas a hacer X, ¿cómo te fue?". Escucha con total atención la respuesta.', 'Recordar la vida del otro es una de las señales de consideración más potentes para crear lazos duraderos: la gente aprecia sentirse importante.', 'Lewis Howes'),
  (21, 1, 3, 'perception', 'Retro semana 3', 'Revisa tu registro de conversaciones de la semana: ¿cuántas clasificaste bien (práctica/emocional/social)? ¿En cuántas escuchaste sin interrumpir? Anota tu patrón de escucha más débil.', 'El registro semanal convierte impresiones vagas en datos accionables.', 'Plan 90 días'),

  -- SEMANA 4: Silencio estratégico y muletillas
  (22, 1, 4, 'action', 'Silencio estratégico', 'Después de tu frase más importante del día, haz una pausa total de 3 segundos sosteniendo la mirada, sin desviar los ojos ni asentir compulsivamente. Deja que el silencio pese.', 'El silencio es un multiplicador de tensión narrativa y autoridad. Muy pocos lo sostienen: dominarlo te separa del 99% de los emisores.', 'Adrià Solà Pastor'),
  (23, 1, 4, 'action', 'Guerra a las muletillas', 'Día de cero relleno: cada vez que notes que viene una muletilla, cállate. Prefiere el micro-silencio incómodo al ruido. Lleva la cuenta de las que se te escaparon.', 'Las muletillas son grietas acústicas que drenan credibilidad: reducen matemáticamente el valor percibido de lo que dices, por brillante que sea.', 'Adrià Solà Pastor'),
  (24, 1, 4, 'action', 'Pregunta de francotirador', 'Sustituye hoy una pregunta cerrada ("¿te gustó?") por una abierta, precisa y con intención ("¿qué fue lo que más te sorprendió de esto y por qué?"). Observa la diferencia en la respuesta.', 'Las preguntas cerradas solo confirman tus sesgos; las preguntas grandes y calibradas son portales directos a la conexión y a la información valiosa.', 'Adrià Solà Pastor'),
  (25, 1, 4, 'action', 'Status sin notas', 'Da tu actualización de estado al equipo sin leer notas. Usa pausas en lugar de relleno cuando necesites organizar la siguiente idea.', 'Hablar sin guion entrena la confianza en tu propio procesamiento y demuestra dominio del tema.', 'Plan 90 días'),
  (26, 1, 4, 'action', 'Elevator pitch', 'Explica tu proyecto actual en 60 segundos exactos. Grábate. Escucha y elimina cada palabra innecesaria. Repite hasta que quepa con claridad y sin correr.', 'Comprimir sin perder claridad es el ejercicio de síntesis que revela si de verdad entiendes lo que haces.', 'Dan Martell'),
  (27, 1, 4, 'action', 'Micro-presentación de 5 minutos', 'Prepara y grábate una presentación de 5 minutos sobre un tema que domines, con estructura: apertura con intención → mensaje central → cierre memorable. Autoevalúa: claridad, contacto visual, emoción.', 'La estructura apertura-mensaje-cierre es lo que convierte información en un discurso que se recuerda.', 'Adrià Solà Pastor'),
  (28, 1, 4, 'perception', 'Retro semana 4', 'Compara la presentación del día 27 con tu video del día 1: muletillas por minuto, ritmo, pausas, postura. Escribe el porcentaje de mejora y qué falta.', 'Cerrar el primer ciclo con datos duros consolida la identidad de comunicador en entrenamiento.', 'Plan 90 días'),

  -- SEMANA 5: Cierre fase 1 + espejo táctico
  (29, 1, 5, 'perception', 'Examen de fase 1', 'Escribe: ¿qué técnica del primer mes te costó más y por qué? ¿Cuál ya sale sola? Elige el punto débil que vas a seguir puliendo mientras arrancas la fase 2.', 'La retrospectiva honesta y sin autoconmiseración es el examen estoico aplicado al entrenamiento.', 'Séneca / Plan 90 días'),
  (30, 1, 5, 'will', 'Día de integración', 'Ejecuta el día completo: priming matutino + calentamiento vocal + pausa deliberada + escucha sin interrumpir + silencio estratégico. Todo en un mismo día, sin excepciones.', 'Integrar las piezas en un solo día demuestra que ya no son ejercicios aislados sino un sistema operativo.', 'Plan 90 días'),
  (31, 2, 5, 'action', 'Espejo táctico', 'En una conversación relevante, repite las últimas 1-3 palabras clave que tu interlocutor acaba de decir, con tono de pregunta (entonación ascendente). Luego calla y observa cómo profundiza solo.', 'El espejo genera sintonía inconsciente e invita al otro a elaborar sin que se sienta interrogado: obtienes información sin confrontar.', 'Chris Voss'),
  (32, 2, 5, 'action', 'Espejo bajo fricción', 'Usa el espejo táctico en una conversación con tensión real (cliente molesto, jefe apurado, familiar irritado). Repite sus palabras clave en tono inquisitivo y deja que se explique.', 'Bajo fricción, el espejo desacelera la escalada y le demuestra al otro que está siendo escuchado, no combatido.', 'Chris Voss'),
  (33, 2, 5, 'action', 'Silencio post-espejo', 'Hoy, después de cada espejo, sostén un silencio absoluto de al menos 4 segundos. No lo rellenes aunque el silencio incomode: el turno es del otro.', 'El silencio después del espejo es lo que obliga al interlocutor a llenar el vacío con la información que necesitas.', 'Chris Voss'),
  (34, 2, 5, 'action', 'Espejo + paráfrasis', 'En una conversación difícil, combina: espejo de sus palabras clave → escucha → paráfrasis con la emoción detectada → confirmación. Solo entonces da tu punto de vista.', 'La secuencia espejo-paráfrasis-confirmación es el protocolo completo de escucha táctica: el otro baja las defensas antes de que argumentes.', 'Chris Voss / Chris Lee'),
  (35, 2, 5, 'perception', 'Retro semana 5', 'Documenta 2 casos de esta semana donde el espejo táctico reveló información que no habrías obtenido preguntando directamente. ¿Qué dijeron después del silencio?', 'Registrar los casos de éxito calibra tu confianza en la técnica y te muestra en qué contextos funciona mejor.', 'Plan 90 días'),

  -- SEMANA 6: Etiquetado emocional y validación
  (36, 2, 6, 'action', 'Etiquetado emocional', 'Cuando notes tensión, resistencia o duda en alguien, etiquétala en voz alta sin usar "yo": "parece que hay cierta preocupación sobre los plazos", "suena a que esto te resulta injusto". Silencio absoluto después.', 'Nombrar la emoción del otro la disipa: la etiqueta bien puesta desactiva la amígdala y fortalece la confianza.', 'Chris Voss'),
  (37, 2, 6, 'action', 'Etiqueta lo positivo', 'Hoy etiqueta también emociones positivas: "suena a que estás orgulloso de cómo quedó esto", "parece que este proyecto te entusiasma de verdad". Observa el efecto.', 'Validar la emoción positiva amplifica el vínculo igual que etiquetar la negativa la disuelve.', 'Chris Voss'),
  (38, 2, 6, 'action', 'Auditoría de acusaciones', 'Antes de una conversación tensa, escribe lo peor que el otro podría estar pensando de ti ("crees que llego tarde con esto", "parece que no valoré tu trabajo") y dilo tú primero al inicio de la conversación.', 'Nombrar tú mismo las acusaciones les quita el veneno antes de que el otro las use: es la vacuna de la negociación.', 'Chris Voss'),
  (39, 2, 6, 'action', 'Validación específica', 'Reconoce públicamente una contribución concreta de un colega describiendo la acción y su impacto: "tu análisis de ayer hizo que el cliente decidiera de inmediato". Nada de "buen trabajo" genérico.', 'El reconocimiento específico fortalece la relación y te posiciona como líder enfocado en el desarrollo de otros.', 'Lewis Howes'),
  (40, 2, 6, 'action', 'Etiquetado por escrito', 'Aplica el etiquetado en un correo difícil: nombra la preocupación probable del lector antes de tu propuesta ("sé que esto puede parecer un cambio de alcance...").', 'El etiquetado escrito desarma la lectura defensiva del correo igual que la voz lo hace en persona.', 'Chris Voss'),
  (41, 2, 6, 'action', 'Combo completo', 'En una misma conversación importante encadena: espejo → etiqueta emocional → pregunta abierta. Registra qué obtuviste.', 'Las técnicas se potencian en secuencia: el espejo abre, la etiqueta valida y la pregunta abierta dirige.', 'Chris Voss'),
  (42, 2, 6, 'perception', 'Retro semana 6', 'Revisa la semana: ¿qué etiquetas funcionaron y cuáles sonaron falsas? ¿Usaste "yo" sin querer? ¿Respetaste el silencio posterior? Anota tu ajuste para la próxima.', 'La etiqueta mal calibrada suena a manipulación; la retro te enseña a afinar el tono y el momento.', 'Plan 90 días'),

  -- SEMANA 7: Preguntas calibradas y el poder del No
  (43, 2, 7, 'action', 'Pregunta calibrada', 'Sustituye hoy toda pregunta de confirmación ("¿estás de acuerdo?") por una calibrada que empiece con cómo o qué: "¿cómo podríamos resolver esto juntos?", "¿qué nos está impidiendo avanzar?".', 'Las calibradas eliminan la confrontación, obligan al otro a reflexionar y le dan una ilusión de control que facilita la colaboración.', 'Chris Voss'),
  (44, 2, 7, 'action', 'Destierra el porqué', 'Reformula hoy todo "¿por qué hiciste X?" en "¿qué te llevó a X?" o "¿cómo llegaste a esa decisión?". El porqué acusa; el qué y el cómo invitan.', 'El "por qué" genera actitud defensiva universal: suena a acusación aunque no lo sea.', 'Chris Voss'),
  (45, 2, 7, 'action', 'El poder del No', 'Formula una petición como pregunta orientada al no: "¿sería descabellado considerar esta alternativa?", "¿te parece mala idea si lo intentamos así?". Observa cuánto más fácil responde el otro.', 'Perseguir el "sí" genera defensividad y compromisos falsos; el "no" da al otro seguridad y control, y abre la información real.', 'Chris Voss'),
  (46, 2, 7, 'action', '¿Cómo se supone que haga eso?', 'Ante una petición irrazonable de hoy (plazo imposible, alcance inflado), en lugar de aceptar sumisamente o quejarte, devuelve con calma: "¿cómo se supone que logre eso con los recursos actuales?".', 'Esa pregunta traslada el problema a quien lo creó sin romper la relación: es un límite disfrazado de colaboración.', 'Chris Voss'),
  (47, 2, 7, 'action', '¿Hay algo más?', 'Cierra hoy 3 conversaciones con la pregunta expansiva "¿hay algo más que deba saber?" y escucha en silencio lo que salga.', 'Lo más importante suele aparecer después de la última pregunta: la expansiva le da permiso de salir.', 'Chris Lee'),
  (48, 2, 7, 'action', 'Negociación real', 'Negocia hoy un plazo, alcance o condición real usando el arsenal: etiqueta la presión del otro, pregunta calibrada, propuesta con límite claro ("para garantizar calidad, entrego la primera parte el viernes y el consolidado el lunes, ¿cómo afecta eso sus planes?").', 'Transformar la exigencia en problema conjunto consolida tu autoridad profesional sin fricción.', 'Chris Voss'),
  (49, 2, 7, 'perception', 'Retro semana 7', 'Documenta tu negociación de la semana de principio a fin: qué técnicas usaste, qué obtuviste, dónde cediste de más. ¿Qué harías distinto?', 'La negociación se aprende en la revisión posterior, no en el calor del momento.', 'Plan 90 días'),

  -- SEMANA 8: Storytelling
  (50, 2, 8, 'action', 'Tu historia personal', 'Escribe una historia corta de tu experiencia con estructura reto → acción → lección. Cuéntala en voz alta 2 veces hasta que fluya natural. Será parte de tu repertorio.', 'Las historias personales conectan y hacen memorables las ideas que los datos solos no logran fijar.', 'Carmine Gallo / Martell'),
  (51, 2, 8, 'action', 'Sparkline', 'Presenta hoy una propuesta contrastando "lo que es" (situación actual con datos) contra "lo que podría ser" (la solución y sus beneficios), y cierra con una llamada a la acción clara.', 'La tensión narrativa entre presente y futuro deseado mantiene la atención y hace evidente el valor del cambio.', 'Carmine Gallo'),
  (52, 2, 8, 'action', 'Regla de tres', 'Organiza tu próximo correo importante o intervención en exactamente 3 puntos, anunciados al inicio: "hoy abordaremos tres cosas: el diagnóstico, las opciones y la recomendación".', 'El cerebro retiene tríadas de forma óptima: tres puntos evitan la sobrecarga y proyectan claridad ejecutiva.', 'Carmine Gallo'),
  (53, 2, 8, 'action', 'Analogía técnica', 'Explica hoy un concepto técnico de tu trabajo (un ETL, un dashboard, una arquitectura) a alguien no técnico usando una analogía cotidiana. Verifica que lo pueda repetir con sus palabras.', 'Si no puedes explicarlo con una analogía simple, todavía no lo dominas lo suficiente como para liderar con ello.', 'Dan Martell'),
  (54, 2, 8, 'action', 'Framework CPPS', 'Usa la estructura Contexto → Problema → Propuesta → Siguiente paso en una reunión real. Escríbelo antes en 4 líneas, dilo, y al final pregunta: "¿quedó claro el siguiente paso?".', 'Un framework fijo y repetible hace que las ideas técnicas se entiendan a la primera y libera tu mente para la entrega.', 'Dan Martell'),
  (55, 2, 8, 'action', 'El dato envuelto en historia', 'Presenta hoy un avance o métrica envolviéndolo en una mini-historia (quién tenía el problema, qué pasaba, qué cambió) en lugar de mostrar el número solo.', 'Los datos informan pero las historias mueven: el número dentro de una narrativa se recuerda y se comparte.', 'Carmine Gallo'),
  (56, 2, 8, 'perception', 'Retro semana 8', 'Revisa la semana: ¿cuál historia o estructura aterrizó mejor? ¿Dónde notaste que perdías a la audiencia? Elige tu estructura por defecto de ahora en adelante.', 'Tener una estructura por defecto elimina la improvisación caótica bajo presión.', 'Plan 90 días'),

  -- SEMANA 9: Rapport, VAK y exposición social
  (57, 3, 9, 'action', 'Matching sutil', 'En 2 conversaciones de hoy, iguala sutilmente el ritmo, tono y energía de tu interlocutor (sin imitar gestos de forma obvia). Cuando haya sintonía, lidera bajando tú el ritmo.', 'El rapport se construye igualando primero (pacing) para poder guiar después (leading): la conexión precede a la influencia.', 'Tony Robbins'),
  (58, 3, 9, 'action', 'Comentario situacional', 'Rompe el hielo con un desconocido comentando el contexto compartido en tono neutro y amable (la fila, el clima, el lugar). Sin agenda: solo testear receptividad.', 'El entorno común es el terreno más seguro para iniciar contacto: entrena la lectura de la disposición ajena sin invadir.', 'Escalera social'),
  (59, 3, 9, 'action', '¿Qué te trajo por acá?', 'En un evento, curso o espacio compartido, acércate a alguien y pregunta: "¿qué te trajo por acá?". Haz una pregunta de seguimiento basada en lo que escuches.', 'Esa pregunta salta el small talk vacío directo a las motivaciones: el terreno donde nace la conexión real.', 'Escalera social'),
  (60, 3, 9, 'action', 'Cumplido y retirada', 'Haz un cumplido genuino e impersonal a alguien (su reloj, su libro, su elección) y retírate inmediatamente después del gracias. Sin esperar conversación.', 'Dar valor social gratis y sin segundas intenciones entrena la observación positiva y elimina la presión de sostener la charla.', 'Escalera social'),
  (61, 3, 9, 'action', 'Tres minutos con alguien nuevo', 'Inicia una conversación de 2-3 minutos con alguien nuevo (gym, oficina, cafetería) buscando activamente un punto de afinidad: proyecto, hobby, contexto.', 'Buscar similitudes en lugar de diferencias reduce la distancia percibida y asienta la base de la confianza.', 'Escalera social'),
  (62, 3, 9, 'action', 'Cambia el canal', 'Toma un mensaje tuyo que no aterrizó esta semana y reformúlalo en otro canal: si fue verbal, hazlo diagrama; si fue escrito, explícalo en persona. Documenta si mejoró la comprensión.', 'Cuando un mensaje no llega, el problema suele ser el canal, no el contenido.', 'Tony Robbins'),
  (63, 3, 9, 'perception', 'Retro semana 9', 'Dibuja tu escalera de exposición social: ¿qué peldaño ya es cómodo (saludos, small talk, conversación) y cuál sigue? Define el reto social de la próxima semana un peldaño arriba.', 'La desensibilización social funciona por gradiente: consolidar un peldaño antes de subir evita el retroceso.', 'Plan 90 días'),

  -- SEMANA 10: Asertividad y límites
  (64, 3, 10, 'action', 'Límite sin disculpa excesiva', 'Di no hoy a algo que excede tu capacidad, con hechos y sin justificaciones en cadena: "no puedo asumir este proyecto ahora por las prioridades X e Y". Punto. Sin pedir perdón tres veces.', 'Ser claro es ser compasivo: los límites difusos generan resentimiento en ambas direcciones.', 'Brené Brown'),
  (65, 3, 10, 'action', 'Expectativas explícitas', 'Al iniciar una tarea conjunta hoy, define por escrito con la otra parte: "¿cómo luce el éxito de este entregable?" y "¿qué obstáculos podrían impedirlo?".', 'Los supuestos no verbalizados son la semilla de los reproches: la alineación explícita los mata de raíz.', 'Brené Brown'),
  (66, 3, 10, 'action', 'Noticia incómoda sin sobre-justificar', 'Da hoy (o simula por escrito) una noticia incómoda —retraso, error, cambio— con la estructura: hecho, impacto, plan, siguiente paso. Sin justificarte de más.', 'La sobre-justificación comunica culpa y debilita el mensaje; el plan comunica control.', 'Plan 90 días'),
  (67, 3, 10, 'action', 'No sé / me equivoqué', 'Di hoy en voz alta "no sé" o "me equivoqué" cuando corresponda, sin minimizarlo ni adornarlo. Sostén la mirada al decirlo.', 'Admitir el error sin drama proyecta más autoridad que fingir certeza: la vulnerabilidad calculada construye confianza.', 'Brené Brown / Plan 90 días'),
  (68, 3, 10, 'action', 'Claro es amable', 'Reescribe y envía hoy ese mensaje ambiguo que llevas días evitando (el recordatorio, la corrección, la petición). Versión corta, clara y respetuosa.', 'Lo que se evita por incomodidad se cobra con intereses: la claridad temprana es el menor de los males.', 'Brené Brown'),
  (69, 3, 10, 'action', 'Contacto visual sostenido', 'Tras emitir tu propuesta o respuesta importante de hoy, sostén el contacto visual en silencio total 3-5 segundos. No desvíes la mirada ni asientas compulsivamente.', 'El contacto sostenido comunica convicción y compostura; desviar la mirada por timidez es sumisión social refleja.', 'Escalera social nivel 4'),
  (70, 3, 10, 'perception', 'Retro semana 10', '¿Qué límite te costó más poner esta semana y qué pasó realmente después de ponerlo? Compara la catástrofe imaginada con la reacción real.', 'Documentar que el mundo no se acabó tras el límite reeduca al cerebro que lo temía.', 'Plan 90 días'),

  -- SEMANA 11: Feedback y liderazgo
  (71, 3, 11, 'action', 'Feedback SBI', 'Da hoy un feedback usando Situación → Comportamiento → Impacto: "en la reunión de ayer (S), cuando interrumpiste la demo (C), el cliente perdió el hilo de la propuesta (I)". Sin juicios de carácter.', 'El SBI separa la conducta de la persona: hace el feedback recibible y accionable.', 'Plan 90 días'),
  (72, 3, 11, 'action', 'Regla 1-3-1 hacia arriba', 'Lleva hoy un problema a tu jefe o equipo en formato 1-3-1: un (1) problema definido con precisión, tres (3) opciones viables, una (1) recomendación argumentada.', 'El 1-3-1 acelera decisiones, elimina la fatiga de decisión del líder y te posiciona como alguien que trae soluciones, no cargas.', 'Dan Martell'),
  (73, 3, 11, 'action', 'Instala el 1-3-1', 'Cuando alguien te traiga hoy un problema, no lo resuelvas: pídele que vuelva con 3 opciones y una recomendación. Acompaña sin dar la respuesta.', 'Resolver todo tú crea dependencia y te convierte en el cuello de botella; delegar el problema desarrolla el criterio del otro.', 'Dan Martell'),
  (74, 3, 11, 'action', 'Cede la palabra', 'En una junta de hoy, haz brillar activamente a alguien más: "X trabajó a fondo esto, ¿nos cuentas cómo lo resolviste?". Resiste el impulso de completar sus frases.', 'Ceder el protagonismo con intención es la señal de estatus más contraintuitiva y efectiva del liderazgo.', 'Plan 90 días'),
  (75, 3, 11, 'action', 'Feedforward', 'Después de tu intervención más importante de hoy, pregunta a alguien de confianza: "¿qué puedo mejorar la próxima vez?". Escucha sin defenderte y agradece.', 'Pedir mejora futura (no evaluación pasada) hace la crítica fácil de dar y de recibir.', 'Tony Robbins'),
  (76, 3, 11, 'action', 'Delega el problema, no la tarea', 'Entrega hoy la propiedad completa de un problema (contexto, criterio de éxito, restricciones) en lugar de una lista de tareas fraccionadas. Define solo el qué, no el cómo.', 'Delegar tareas crea microgestión; delegar problemas crea pensamiento crítico y responsabilidad por el resultado.', 'Dan Martell'),
  (77, 3, 11, 'perception', 'Retro semana 11', '¿Qué cambió en tu entorno al usar 1-3-1, SBI y delegación de problemas? ¿Quién respondió mejor? Anota a quién le seguirás exigiendo el formato.', 'Los sistemas de comunicación se consolidan midiendo su efecto en los demás, no solo en ti.', 'Plan 90 días'),

  -- SEMANA 12: Conflicto y disidencia
  (78, 3, 12, 'action', 'Aclaración directa', 'Agenda 10 minutos con alguien con quien hubo un roce o malentendido reciente. Expón el hecho neutro: "vi X en tu correo; quiero asegurarme de que estamos alineados, ¿qué perspectiva tienes?".', 'La confrontación temprana basada en hechos evita la escalada pasivo-agresiva que pudre las relaciones de trabajo.', 'Plan 90 días / Voss'),
  (79, 3, 12, 'action', 'Disidencia racional', 'Expresa hoy una opinión contraria a la mayoría o a tu superior con preámbulo neutral: "veo el valor de A; sin embargo, en B encuentro un riesgo crítico. Propongo esta alternativa...".', 'Vencer el conformismo grupal anteponiendo la verdad racional al agrado superficial gana respeto intelectual.', 'Plan 90 días'),
  (80, 3, 12, 'action', 'Empatía táctica en caliente', 'En el próximo desacuerdo, antes de argumentar, resume la posición del otro hasta que diga "exacto" o "así es". Solo entonces presenta la tuya.', 'Nadie escucha tu argumento mientras siente que no entendiste el suyo: el "así es" es la puerta de entrada.', 'Chris Voss'),
  (81, 3, 12, 'action', 'LA conversación pendiente', 'Ten hoy la conversación difícil que llevas semanas posponiendo. Prepárala: auditoría de acusaciones, etiquetas, calibradas, límite claro. Ejecútala.', 'La conversación evitada gobierna tu energía desde la sombra; tenerla es recuperar el control.', 'Integración'),
  (82, 3, 12, 'action', 'Comunicación de crisis', 'Simulacro por escrito: redacta cómo comunicarías un fallo grave de tu responsabilidad. Estructura: qué pasó, impacto real, qué estamos haciendo, cuándo habrá noticias. Sin culpables ni adornos.', 'En crisis, la transparencia estructurada y la calma comunican más liderazgo que cualquier discurso.', 'Plan 90 días'),
  (83, 3, 12, 'action', 'Vulnerabilidad estratégica', 'Comparte hoy con tu equipo un error propio y la lección que te dejó. Breve, sin drama y con la lección clara.', 'La vulnerabilidad del líder da permiso al equipo de reportar errores a tiempo: es infraestructura de confianza.', 'Brené Brown / Howes'),
  (84, 3, 12, 'perception', 'Retro semana 12', 'Bajo presión, ¿cuál es tu patrón: luchar, huir o congelarte? Identifícalo con ejemplos de la semana y escribe qué técnica concreta lo contrarresta.', 'Conocer tu respuesta automática al conflicto te permite instalar el interruptor antes de que dispare.', 'Plan 90 días'),

  -- SEMANA 13: Evaluación final
  (85, 3, 13, 'evaluation', 'Preparación de la presentación final', 'Prepara una presentación de 10 minutos sobre un tema tuyo (proyecto, propuesta, pasión) que integre: apertura con intención, 3 puntos, una historia, datos envueltos en narrativa y cierre memorable.', 'La presentación final es el examen integrador: cada técnica de los 90 días tiene su lugar en ella.', 'Evaluación'),
  (86, 3, 13, 'evaluation', 'Ensayo grabado', 'Graba la presentación completa. Cuenta muletillas, mide ritmo y pausas. Compárala con tu video del día 1: esa distancia es tu progreso objetivo.', 'La comparación día 1 vs día 86 convierte 90 días de esfuerzo en evidencia irrefutable.', 'Evaluación'),
  (87, 3, 13, 'evaluation', 'Ejecución ante audiencia real', 'Presenta ante una audiencia real: tu equipo, colegas o familia. Pide feedback específico con tu plantilla: ¿mensaje claro? ¿siguiente paso claro? ¿qué sobró?', 'El escenario real es el único validador final: los nervios ante gente de verdad no se simulan.', 'Evaluación'),
  (88, 3, 13, 'evaluation', 'Revisión de registros', 'Relee todas tus retros semanales. Identifica el patrón débil que más se repitió en los 90 días (interrumpir, cerrar mal, evitar límites, correr al hablar...).', 'Tu patrón más repetido es tu próximo programa de entrenamiento.', 'Evaluación'),
  (89, 3, 13, 'evaluation', 'Mini-plan de 30 días', 'Diseña un mini-plan de 30 días enfocado únicamente en tu punto débil dominante: un ejercicio diario, una métrica, una retro semanal.', 'El progreso post-programa depende de enfocar un solo frente a la vez, no de repetirlo todo.', 'Evaluación'),
  (90, 3, 13, 'evaluation', 'Evaluación final de 90 días', 'Abre el informe de 90 días en la app: progreso por módulo, rachas, días perdidos, consistencia. Escribe tu retro final: qué eres capaz de hacer hoy que no podías el día 1.', 'Cerrar el ciclo con datos y reflexión escrita consolida la identidad: ya no practicas comunicación, eres un comunicador que entrena.', 'Evaluación')
) AS v(day_number, phase, week, module, title, instructions, rationale, source_author)
ON CONFLICT (track_id, day_number) DO NOTHING;

-- ------------------------------------------------------------
-- RETOS SEMANALES (13)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'comunicacion')
INSERT INTO stoic.program_weeks (track_id, week_number, theme, challenge_title, challenge_description, deliverable)
SELECT t.id, v.week_number, v.theme, v.challenge_title, v.challenge_description, v.deliverable
FROM t, (VALUES
  (1, 'Diagnóstico y línea base', 'Establece tu punto de partida', 'Graba tu video diagnóstico de 3 minutos y consigue que 5 personas califiquen tu escucha del 1 al 10. Sin línea base no hay progreso medible.', 'Video del día 1 + tabla con métricas (muletillas, palabras/min, nervios 1-5) + 5 calificaciones de escucha.'),
  (2, 'Fisiología y voz', 'Ritual de priming 7 días seguidos', 'Ejecuta el priming matutino (postura + respiración 4-4-6 + incantación) los 7 días de la semana, antes de tocar el celular.', 'Registro diario de cumplimiento del ritual.'),
  (3, 'Escucha activa', 'Tres conversaciones deliberadas', 'Practica en 3 conversaciones reales: identifica el tipo (práctica/emocional/social), pregunta explícitamente qué necesita el otro, y parafrasea con emoción.', 'Registro de 6 conversaciones con tipo identificado y si acertaste.'),
  (4, 'Silencio y muletillas', 'Presentación simulada de 5 minutos', 'Prepara, graba y autoevalúa una presentación de 5 minutos con estructura apertura → mensaje → cierre, usando pausas en lugar de muletillas.', 'Video + plantilla de autoevaluación (claridad, contacto visual, muletillas/min).'),
  (5, 'Espejo táctico', 'El espejo en el mundo real', 'Usa el espejo táctico (repetir las últimas palabras clave en tono de pregunta + silencio) en al menos 3 conversaciones reales de la semana.', '2 casos documentados donde el espejo reveló información inesperada.'),
  (6, 'Etiquetado emocional', 'Etiqueta bajo tensión', 'Aplica el etiquetado emocional en una conversación difícil real de la semana: nombra la emoción del otro sin usar "yo" y guarda silencio.', 'Registro: qué etiqueta usaste, cómo reaccionó el otro, qué cambió.'),
  (7, 'Preguntas calibradas', 'Una negociación real', 'Negocia algo real esta semana (plazo, alcance, condición) usando preguntas calibradas, orientadas al no, y un límite claro sin romper la relación.', 'Documento de la negociación: técnicas usadas y resultado obtenido.'),
  (8, 'Storytelling', 'Propuesta con estructura', 'Presenta una propuesta o avance real usando sparkline (lo que es vs lo que podría ser) y la regla de tres, y pide feedback directo.', 'La propuesta escrita + el feedback recibido ("¿quedó claro el siguiente paso?").'),
  (9, 'Exposición social', 'Sube un peldaño de la escalera', 'Completa 3 microinteracciones con desconocidos: comentario situacional, "¿qué te trajo por acá?" y cumplido con retirada.', 'Registro de las 3 interacciones y cómo respondió cada persona.'),
  (10, 'Asertividad y límites', 'Dos límites claros', 'Pon 2 límites reales esta semana: un no con hechos y sin disculpas en cadena, y una expectativa explícita definida por escrito.', 'Qué dijiste exactamente y qué pasó después (vs lo que temías).'),
  (11, 'Liderazgo comunicativo', 'Instala el 1-3-1', 'Usa el formato 1-3-1 hacia arriba (con tu jefe) y hacia abajo (exígelo a alguien que te traiga un problema). Da al menos un feedback SBI.', 'El primer problema recibido en formato 1-3-1 + tu feedback SBI documentado.'),
  (12, 'Conflicto', 'La conversación pendiente', 'Ten LA conversación difícil que llevas posponiendo, preparada con auditoría de acusaciones, etiquetas y calibradas.', 'Retro escrita de la conversación: qué preparaste, qué pasó, qué aprendiste.'),
  (13, 'Evaluación final', 'Presentación de graduación', 'Presenta 10 minutos ante audiencia real integrando todo el arsenal, y cierra con tu retro de 90 días comparando contra el día 1.', 'Video final + documento de retro de 90 días + mini-plan de 30 días.')
) AS v(week_number, theme, challenge_title, challenge_description, deliverable)
ON CONFLICT (track_id, week_number) DO NOTHING;

-- ------------------------------------------------------------
-- HITOS MENSUALES (3)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'comunicacion')
INSERT INTO stoic.program_months (track_id, month_number, title, description)
SELECT t.id, v.month_number, v.title, v.description
FROM t, (VALUES
  (1, 'Fundamentos: voz, cuerpo y escucha', 'Dominar la fisiología (priming, respiración táctica), la voz (melodía, ritmo, silencio) y la escucha activa (tipos de conversación, paráfrasis). Hito verificable: el video del día 28 muestra al menos 50% menos muletillas por minuto que el del día 1.'),
  (2, 'Persuasión: negociación y storytelling', 'Integrar el arsenal de Voss (espejo, etiquetado, calibradas, el poder del No) y las estructuras narrativas (sparkline, regla de tres, CPPS) en tu trabajo real. Hito verificable: una negociación real documentada con resultado favorable, y una propuesta presentada con estructura narrativa.'),
  (3, 'Liderazgo: límites, feedback y conflicto', 'Consolidar asertividad (límites sin disculpa, expectativas explícitas), sistemas de liderazgo (1-3-1, SBI, delegación de problemas) y manejo de conflicto. Hito verificable: presentación final de 10 minutos ante audiencia real + la conversación difícil pendiente, tenida.')
) AS v(month_number, title, description)
ON CONFLICT (track_id, month_number) DO NOTHING;
