-- ============================================================
-- StoiComunication V2 - Seed Track 2: Práctica Interna (PREMIUM)
-- 90 días + 13 retos semanales + 3 hitos mensuales
-- Fuentes: Marco Aurelio, Séneca, Epicteto, Viktor Frankl,
--          Ryan Holiday (La disciplina marcará tu destino, Diario Estoico),
--          Tony Robbins (Awaken the Giant Within), Lewis Howes
--          (The Greatness Mindset, School of Greatness, The Mask of
--          Masculinity, Make Money Easy), Judson Brewer, James Clear,
--          Dan Martell, Adrià Solà
-- Idempotente: re-ejecutar ACTUALIZA el contenido existente.
-- ============================================================

-- ------------------------------------------------------------
-- DÍAS (90)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'interna')
INSERT INTO stoic.program_days (track_id, day_number, phase, week, module, title, instructions, rationale, source_author)
SELECT t.id, v.day_number, v.phase, v.week, v.module, v.title, v.instructions, v.rationale, v.source_author
FROM t, (VALUES
  -- SEMANA 1: Diario de identidad, decisiones y mapa de bucles
  (1, 1, 1, 'perception', 'Diario de identidad y la primera decisión', 'Escribe 20 minutos en tres bloques: 1) ¿Quién soy hoy, con datos y sin drama? 2) ¿Quién decido ser en 90 días? — descríbelo en presente, como si ya existiera. 3) ¿Qué creencias me limitan y desde cuándo las cargo? Cierra con una decisión formal escrita: no una preferencia ("me gustaría"), una decisión ("decidí, y corto toda otra posibilidad"). Guarda este texto: lo releerás el día 86.', 'Robbins insiste en que es en los momentos de decisión donde se moldea el destino: una decisión real es aquella tras la cual actúas de inmediato y quemas las naves. Sin ella, los 90 días son solo una intención.', 'Tony Robbins / James Clear'),
  (2, 1, 1, 'perception', 'Mapa del bucle: tu anatomía de la evasión', 'Construye la tabla completa de tu principal hábito de evasión: Disparador (¿qué lo enciende: hora, lugar, emoción, persona?) → Emoción (¿qué sientes 10 segundos antes?) → Conducta (¿qué haces exactamente?) → Recompensa (¿qué alivio te da y cuánto dura?). Hazlo con precisión de ingeniero: horas, lugares, duración. Después responde: ¿qué dolor estoy evitando sentir con este bucle?', 'Todo hábito destructivo es una solución torpe a un dolor real. Brewer demuestra que mapear el bucle con curiosidad ya reduce su poder: lo que se observa con precisión deja de operar en la sombra.', 'Judson Brewer / Robbins'),
  (3, 1, 1, 'perception', 'El científico del impulso', 'Hoy no pelees contra nada: solo registra. Cada vez que aparezca el impulso de tu bucle, anota hora, gatillo, intensidad (1-10) y qué estabas evitando hacer o sentir. Trátate como un científico que estudia a un sujeto fascinante. Al final del día cuenta: ¿cuántos impulsos hubo? ¿Cuál fue el patrón de horas?', 'La observación no juiciosa es el primer paso del método de Brewer: cuando pasas de "yo soy ansioso" a "estoy observando una ola de ansiedad", ya no eres el impulso — eres quien lo mira. Esa distancia es el principio del control.', 'Judson Brewer'),
  (4, 1, 1, 'will', 'Las preguntas que la vida te hace', 'Responde por escrito, sin buscar la respuesta impresionante sino la honesta: 1) ¿Por qué vale la pena el esfuerzo de estos 90 días? 2) ¿Qué problema de mi entorno soy capaz de ayudar a resolver como nadie más? 3) ¿Qué querría que dijeran de mí quienes me conocen de verdad, dentro de 20 años? Frankl lo llamaba invertir la pregunta: no interrogues a la vida — la vida te está interrogando a ti.', 'La evasión florece en el vacío existencial: nadie sostiene una disciplina dura sin un porqué que la pague. Howes lo confirma desde el otro extremo: sin una misión significativa, el miedo y la duda llenan el vacío.', 'Viktor Frankl / Lewis Howes'),
  (5, 1, 1, 'perception', 'Auditoría del tiempo: la evidencia forense', 'Registra hoy todas tus horas por colores: verde (construye tu futuro), amarillo (necesario neutro), rojo (evasión o destrucción). Sé despiadadamente honesto: el scrolling "para descansar" es rojo. Al final cuantifica las horas rojas y multiplícalas por 365: ese es el costo anual de tu bucle en horas de vida.', 'Martell calcula que sustraer un solo evasor primario devuelve unas 730 horas productivas al año. El número anual convierte una "manía inofensiva" en una fuga de vida que ya no puedes ignorar.', 'Dan Martell'),
  (6, 1, 1, 'perception', 'La ganancia secundaria: qué te da realmente el bucle', 'Escribe qué necesidades satisface de verdad tu hábito de evasión: ¿certidumbre (adormece el malestar de forma predecible)? ¿variedad (estímulo infinito)? ¿significado (validación, sentirte especial)? ¿conexión (aunque sea falsa)? Un patrón persiste solo si satisface al menos tres necesidades a la vez. Identifica las tuyas: son las que tu nueva vida tendrá que satisfacer mejor.', 'Robbins enseña que nunca eliminas un patrón: lo reemplazas por uno que cubra las mismas necesidades a mayor nivel. Si no sabes qué necesidades cubre el bucle, tu reemplazo fallará.', 'Tony Robbins'),
  (7, 1, 1, 'perception', 'Retro semana 1: la declaración de guerra', 'Relee todos tus registros de la semana y redacta tu declaración de guerra en media página: el bucle número 1 a romper, su disparador principal, su ganancia secundaria, su costo anual en horas y la decisión formal de reemplazarlo. Fírmala con fecha. Un enemigo con nombre, mapa y motivo es un enemigo vencible.', 'El ciclo actuar-registrar-ajustar de la práctica deliberada empieza con un diagnóstico brutal por escrito. La claridad es el primer acto de disciplina.', 'Plan 90 días'),

  -- SEMANA 2: Sustracción y la disciplina del cuerpo (Holiday)
  (8, 1, 2, 'action', 'Sustracción absoluta', 'Elimina hoy tu evasor primario por completo y ponle fricción física real: borra la app (no la escondas), saca el licor de la casa, deja el celular en otra habitación con alarma antigua de despertador. La regla de Holiday: gobierna tu cuerpo o él te gobernará a ti. Que ceder requiera al menos 10 pasos incómodos.', 'Martell aprendió al dejar el alcohol que el progreso no viene de añadir disciplina a un sistema saturado, sino de sustraer los asesinos del tiempo. La fricción física decide más que la fuerza de voluntad.', 'Dan Martell / Ryan Holiday'),
  (9, 1, 2, 'action', 'Ataca el alba', 'Mañana gánale al sol: despierta 30-60 minutos antes de lo habitual y usa esa hora robada para ti — sin pantallas: movimiento, escritura o lectura. Esta noche prepáralo todo: ropa lista, cuaderno abierto, cero decisiones que tomar al despertar. La primera batalla del día es contra la cama; gánala y el resto del día pelea a tu favor.', 'Holiday dedica un capítulo entero a madrugar como acto fundacional de autocontrol: quien pierde la primera batalla del día contra la comodidad ya pelea el resto en retirada.', 'Ryan Holiday'),
  (10, 1, 2, 'action', 'Estándar mínimo viable', 'Define por escrito tu línea base innegociable: hora máxima de acostarte, qué no entra a tu boca, movimiento mínimo diario (aunque sean 20 minutos), y tu práctica de escritura mínima (5 minutos). Cúmplela hoy con o sin ganas. No es tu meta: es el piso debajo del cual no existes. Se cumple los 365 días, con motivación o sin ella.', 'Solà lo llama estándar mínimo viable y Holiday lo confirma con los grandes: la libertad de los disciplinados viene de que su piso no se negocia nunca. Las metas fluctúan; el piso no.', 'Adrià Solà / Ryan Holiday'),
  (11, 1, 2, 'action', 'Descanso neutro: el lujo del aburrimiento', 'Haz hoy un bloque de 15-20 minutos de estímulo neutro: caminata sin dispositivos ni música bajo luz natural, o lectura en papel. El celular se queda. Nota la incomodidad de los primeros minutos: esa urgencia de estímulo es la abstinencia real de tu cerebro sobreestimulado, y atravesarla es el ejercicio.', 'Los descansos neutros resensibilizan los receptores de dopamina saturados por la gratificación instantánea: el aburrimiento tolerado es el gimnasio del circuito de recompensa.', 'Solà / neurociencia'),
  (12, 1, 2, 'action', 'Planes If-Then: decide antes de la batalla', 'Escribe 3 planes condicionales para tus momentos de tentación: "Si [siento urgencia de X en situación Y], entonces [haré Z: respirar 4-8, agua, caminar 5 minutos, abrir el cuaderno]". Ensáyalos mentalmente dos veces, con detalle sensorial. La respuesta debe estar decidida ANTES de que llegue el impulso: en caliente, siempre pierdes la negociación.', 'La implementación condicional automatiza la respuesta sana: Martell la usa para blindar la agenda y los estoicos la conocían como premeditación — el sabio no improvisa ante lo previsible.', 'Dan Martell / Séneca'),
  (13, 1, 2, 'action', 'La cadena de la palabra dada', 'Cumple hoy la cadena completa de compromisos mínimos: tender la cama, vaso de agua al despertar, tu movimiento mínimo, tu escritura mínima y acostarte a tu hora. Marca cada uno al completarlo. No son los hábitos lo que importa hoy: es demostrarle a tu cerebro que tu palabra interna vale, cinco veces seguidas.', 'La autoconfianza real no viene de los éxitos externos sino de la coherencia de cumplir la palabra dada en la intimidad: cada compromiso pequeño cumplido es un depósito en esa cuenta.', 'Solà / Holiday'),
  (14, 1, 2, 'perception', 'Retro semana 2: nunca dos días seguidos', '¿Cuántas horas rojas recuperaste esta semana contra la semana 1? ¿Cuántos días cumpliste el estándar mínimo completo? Instala desde hoy la regla maestra: NUNCA fallar dos días seguidos. Un fallo aislado es un dato; dos seguidos son el principio de un abandono. Si ayer fallaste, hoy es obligatorio.', 'Clear y Martell coinciden: la regla de nunca fallar dos veces protege la identidad en construcción. No se trata de ser perfecto sino de que el sistema se auto-repare rápido.', 'James Clear / Dan Martell'),

  -- SEMANA 3: Dicotomía del control y claridad (Diario Estoico: enero/marzo)
  (15, 1, 3, 'will', 'Examen matutino de Marco Aurelio', 'Dedica 10 minutos al despertar: escribe los obstáculos probables de hoy (la persona difícil, el retraso, la crítica), sepáralos en dos columnas — qué depende de ti (tus juicios, intenciones, respuestas) y qué no (sus actos, el clima, los resultados) — y decide por escrito cómo responderá tu mejor versión a lo incontrolable. Marco Aurelio se lo escribía a sí mismo cada mañana: hoy encontraré gente difícil, y no me gobernará.', 'La dicotomía del control es la primera lección del estoicismo y el tema de enero del Diario Estoico: toda la ansiedad vive en el territorio de lo que no depende de ti. La preparación matutina te quita la sorpresa, que es la mitad del golpe.', 'Marco Aurelio / Ryan Holiday'),
  (16, 1, 3, 'will', 'Examen nocturno de Séneca', 'Antes de dormir, 10 minutos con tres preguntas por escrito: ¿Qué hice mal hoy y cómo afectó mi paz o mis relaciones? ¿Qué hice bien y qué virtud apliqué? ¿Qué haría diferente mañana? Séneca lo hacía cada noche ante la lámpara: juez honesto de su propio día, sin fiscal ni abogado defensor. Honestidad total, autoflagelación cero.', 'El examen vespertino cierra el ciclo del día y convierte cada jornada en materia prima de mejora: Séneca escribió que el alma que se examina a diario duerme mejor que la que huye de sí misma.', 'Séneca'),
  (17, 1, 3, 'will', 'Dicotomía radical en tiempo real', 'Ante cada molestia de hoy — el trancón, el correo cortante, el plan cancelado — pregúntate en el momento exacto: ¿esto depende de mí? Si sí: actúa ahora, sin postergarlo. Si no: suéltalo con una frase interna explícita ("no es mío, sigo") y redirige la energía a lo que sí controlas. Lleva la cuenta de cuántas veces lo aplicaste.', 'Epicteto abría su manual con esta división: de las cosas, unas dependen de nosotros y otras no. Toda la filosofía práctica cabe en aplicar esa frase a las próximas 16 horas.', 'Epicteto'),
  (18, 1, 3, 'will', 'Reserva de juicio: la impresión no es el hecho', 'Hoy no emitas juicios inmediatos. Ante lo que te altere, di internamente: "esto es una impresión, no un hecho" y deja pasar 90 segundos antes de responder o etiquetar. En ese espacio entre el estímulo y la respuesta vive tu libertad completa: úsala. Registra las 3 impresiones más fuertes del día y qué eran realmente al examinarlas.', 'No nos perturban las cosas sino nuestros juicios sobre ellas, enseñaba Epicteto. Frankl lo redescubrió en el extremo: entre el estímulo y la respuesta hay un espacio, y en ese espacio está tu poder.', 'Epicteto / Viktor Frankl'),
  (19, 1, 3, 'will', 'El día enmarcado: ambos exámenes', 'Ejecuta hoy el ciclo completo: examen matutino de preparación + examen nocturno de revisión, el mismo día. Nota por escrito la diferencia: un día abierto con intención y cerrado con revisión es un día vivido dos veces — una en el diseño y otra en la ejecución. Este marco será tu práctica diaria permanente.', 'Mañana y noche son los dos extremos del bucle diario: controlarlos convierte el día entero en práctica. Es la arquitectura común de Marco Aurelio, Séneca y todos los sistemas modernos de journaling.', 'Marco Aurelio / Séneca'),
  (20, 1, 3, 'will', 'Queja cero', 'Un día completo sin quejarte en voz alta ni por chat. Cada queja detectada se reformula en el instante: o en acción ("voy a hacer X al respecto") o en aceptación explícita ("no depende de mí, sigo"). Si se te escapa una, no te castigues: reformúlala y sigue contando. Meta: terminar el día con más reformulaciones que quejas.', 'La queja es ensayar el victimismo: entrena al cerebro a ubicar el control afuera. Holiday lo resume en que el impedimento a la acción hace avanzar la acción — pero solo para quien no está ocupado quejándose.', 'Marco Aurelio / Holiday'),
  (21, 1, 3, 'perception', 'Retro semana 3: el mapa de tu paz', 'Revisa la semana: ¿qué te robó más paz? ¿Estaba de tu lado de la dicotomía o del otro? Casi siempre descubrirás que lo que más pesa está fuera de tu control — verlo por escrito lo vuelve innegable. ¿Cuántos días completaste ambos exámenes? Si fallaste alguno, ajusta el gatillo: pega el cuaderno a la almohada o al café.', 'La revisión semanal convierte impresiones vagas en datos: la disciplina de la percepción (parte 1 del año estoico de Holiday) se entrena midiendo dónde se te va el juicio.', 'Ryan Holiday'),

  -- SEMANA 4: Regulación somática (Brewer + Robbins)
  (22, 1, 4, 'will', 'El protocolo de 5 pasos', 'Memoriza y usa hoy ante cualquier impulso: 1) Detén el cuerpo y endereza la postura (hombros atrás, mentón arriba). 2) Tres respiraciones con exhalación doble: inhala 4, exhala 8. 3) Localiza la emoción en el cuerpo: ¿nudo, presión, calor, dónde? 4) Di: "observo el impulso y lo dejo pasar como una ola; este pensamiento no me define". 5) Inserta tu pensamiento de identidad del contrato. Ensáyalo dos veces en frío para tenerlo listo en caliente.', 'La secuencia interviene el bucle en el cuerpo antes de que llegue a la conducta: Robbins demostró que el cambio de fisiología interrumpe el estado en segundos, y Brewer que la observación curiosa disuelve la identificación con el impulso.', 'Robbins / Brewer'),
  (23, 1, 4, 'will', 'Surfear la ola', 'Cuando venga el craving hoy, no lo pelees ni cedas: cronométralo. Obsérvalo con curiosidad como una ola que sube, llega a su pico y baja sola. Apunta cuánto duró de verdad (spoiler: casi nunca más de 15 minutos). Los impulsos son como gatos callejeros: si no los alimentas con la conducta, cada vez vuelven menos.', 'Brewer demostró en adictos que la curiosidad vence a la fuerza de voluntad: la ola observada pierde a quien la observa. Ninguna emoción es permanente si no la realimentas.', 'Judson Brewer'),
  (24, 1, 4, 'will', 'La Tríada a demanda', 'Tres veces hoy, en horarios fijos, cambia tu estado con la Tríada de Robbins: fisiología (postura expansiva + 10 respiraciones profundas), enfoque (¿qué hay bueno en este momento? ¿qué estoy agradeciendo?) y lenguaje (di en voz alta una frase de capacidad, no de carga). No esperes a estar mal para usarla: prográmala como mantenimiento del sistema.', 'Robbins enseña que toda emoción tiene tres palancas: cómo usas el cuerpo, dónde pones el foco y qué te dices. Quien controla la tríada elige su estado en vez de padecerlo.', 'Tony Robbins'),
  (25, 1, 4, 'will', 'Mapeo somático: la emoción tiene dirección', 'Ante cada emoción fuerte de hoy, antes de actuar, nómbrala con precisión y ubícala: "ansiedad, pecho, 7 de 10", "irritación, mandíbula, 5 de 10". Solo eso: nombre, lugar, intensidad. La emoción nombrada con precisión pierde la mitad de su mando. La difusa gobierna entera.', 'Es el paso R-A-I-N de Brewer (reconocer, aceptar, investigar, nutrir): investigar la sensación con curiosidad corporal desactiva la red neuronal de la rumiación.', 'Judson Brewer'),
  (26, 1, 4, 'will', 'Interrupción de patrón', 'Al detectar hoy el inicio de tu bucle — el gesto de agarrar el celular, el paso hacia la cocina — interrumpe el patrón físicamente y de forma abrupta: levántate, cambia de habitación, sal a la luz, sacude el cuerpo, di algo absurdo en voz alta. Cuanto más brusca y rara la interrupción, mejor: el patrón necesita su secuencia completa para ejecutarse; rómpela a mitad.', 'Es el tercer paso del Condicionamiento Neuro-Asociativo de Robbins: interrumpir el patrón limitante hasta que el surco neuronal deje de ser el camino automático. Sin interrupción no hay espacio para instalar la alternativa.', 'Tony Robbins'),
  (27, 1, 4, 'will', 'La oferta mayor y mejor', 'Cada vez que resistas un impulso hoy, escribe inmediatamente después cómo se siente la paz de no haber cedido: en el cuerpo, en el orgullo, en la autoimagen. Compárala por escrito con lo que da la recaída (alivio de 5 minutos + resaca de culpa). Estás construyendo el catálogo de evidencia de que la presencia paga más que el estímulo.', 'Brewer lo llama la oferta mayor y mejor: el cerebro solo abandona una recompensa cuando comprueba, con experiencia repetida y registrada, que existe una mejor. Dásela por escrito.', 'Judson Brewer'),
  (28, 1, 4, 'perception', 'Retro semana 4: cierre de la descompresión', '¿Cuántas olas surfeaste sin ceder esta semana? ¿Cuál fue tu mejor intervención del protocolo? Cierra la fase 1 puntuando de 1 a 10: conciencia del bucle, regulación ante el impulso, cumplimiento del estándar mínimo. La fase de descompresión termina cuando el impulso ya no da las órdenes. Mide cuánto te falta y celebra cuánto avanzaste: ambas cosas son datos.', 'El primer mes purga los circuitos saturados y devuelve el mando a la corteza prefrontal: sin esta base fisiológica, el trabajo de identidad del mes 2 sería construir sobre arena.', 'Plan 90 días'),

  -- SEMANA 5: Cierre fase 1 + contrato sagrado (Robbins: decisiones, valores)
  (29, 1, 5, 'perception', 'Examen de fase 1', 'Relee todas tus retros del mes y responde: ¿qué evasor sigue vivo y en qué horario ataca? ¿qué práctica ya sale sola? ¿cuál abandonaste sin darte cuenta? Prepara la lista de cláusulas para el contrato de la fase 2: qué comportamientos son ya innegociables y cuáles necesitan refuerzo. La revisión mensual honesta convierte 30 días de práctica en cimientos.', 'Séneca revisaba su progreso como un administrador revisa las cuentas: sin drama y sin excusas. Lo que no se audita, se degrada.', 'Séneca / Plan 90 días'),
  (30, 1, 5, 'will', 'El día perfecto de fase 1', 'Ejecuta hoy el día completo integrado: ataca el alba + examen matutino + estándar mínimo viable + descanso neutro + protocolo ante impulsos + examen nocturno. Todo en un día, sin excepciones. No es un día especial: es el ensayo general de tu vida ordinaria nueva. Al cerrarlo, escribe cómo se sintió habitar un día entero diseñado por ti.', 'Un día completo integrado demuestra que las piezas ya forman un sistema operativo. Holiday insiste: el desfile diario de pequeños actos disciplinados ES el destino, no su preparación.', 'Ryan Holiday'),
  (31, 2, 5, 'will', 'El contrato sagrado', 'Redacta formalmente tu contrato de autoconcepto en presente: cómo actúa, come, entrena, habla, gasta y descansa la persona en la que te estás convirtiendo. Precisión milimétrica: no "hago ejercicio" sino "entreno lunes, miércoles y viernes a las 6:00 pase lo que pase". Incluye qué cosas esa persona ya NO hace jamás. Fírmalo con fecha y testigo (aunque el testigo seas tú ante el espejo).', 'El autoconcepto es un contrato que firmas contigo: Solà enseña que la autoconfianza nace de cumplir la palabra dada en la intimidad, y Robbins que la identidad es la fuerza que gobierna todos los comportamientos — actuamos según quien creemos ser.', 'Solà / Robbins / Martell'),
  (32, 2, 5, 'will', 'Regla del 300% + vocabulario transformacional', 'Lee tu contrato en voz alta al despertar y antes de dormir. Aplica la regla del 300%: 100% claridad + 100% creencia + 100% del tiempo. Y desde hoy vigila tu vocabulario: caza las palabras con las que describes tu vida y bájales o súbeles el voltaje a tu favor — no estás "destrozado", estás "recargando"; no estás "ansioso", estás "activado"; no "tienes" que entrenar, "eliges" entrenar. Las palabras que usas habitualmente esculpen lo que sientes.', 'Robbins dedica un capítulo entero al vocabulario transformacional: cambiar la palabra habitual con que etiquetas una emoción cambia la intensidad de la emoción misma. El lenguaje no describe tu estado: lo fabrica.', 'Tony Robbins / Dan Martell'),
  (33, 2, 5, 'action', 'Blindaje de calendario', 'Agenda tus hábitos clave de la semana como citas inamovibles: entrenamiento, exámenes matutino y nocturno, trabajo profundo, descansos neutros. Ponles nombre y hora exacta. La prueba de fuego: si alguien te pide ese espacio, respondes "tengo un compromiso" — porque lo tienes, con la persona del contrato. Lo que no está agendado no existe; lo agendado no se negocia.', 'Martell blinda el calendario para eliminar la negociación mental del momento: la decisión ya fue tomada por tu mejor versión en frío. El calendario es el contrato hecho horario.', 'Dan Martell'),
  (34, 2, 5, 'action', 'Compromiso público y consecuencia', 'Comunica hoy tu meta de 90 días a alguien que te pueda exigir cuentas — mentor, pareja, amigo sin filtro — y define con esa persona un chequeo semanal fijo. Añade una consecuencia disuasoria real si rompes el contrato: transferencia a una causa que detestas, confesión pública, doble entrenamiento. El compromiso sin costo es una opinión.', 'Martell incluye el compromiso público y la consecuencia severa en su protocolo de consistencia: la presión social positiva sostiene lo que la motivación abandona, y el costo real hace que el cerebro tome el contrato en serio.', 'Dan Martell / Lewis Howes'),
  (35, 2, 5, 'perception', 'Retro semana 5: la cláusula increíble', 'Relee tu contrato y detecta la cláusula que te cuesta más CREER (no cumplir: creer). Esa señala tu herida de identidad y define el trabajo de las próximas semanas. Escribe: ¿por qué me cuesta creerla? ¿qué evidencia concreta la haría creíble? ¿qué voz antigua dice que no puedo? Ponerle nombre a esa voz es el primer paso para jubilarla.', 'Howes enseña que la autoduda es el asesino silencioso de los sueños: no se vence discutiendo con ella sino acumulando evidencia en contra. La cláusula increíble es tu mapa de dónde acumularla.', 'Lewis Howes'),

  -- SEMANA 6: Identidad en acción (Clear + Robbins: incantaciones, preguntas de poder)
  (36, 2, 6, 'action', 'Un voto por la nueva identidad', 'Haz hoy una cosa que SOLO haría tu nueva identidad — la conversación evitada, el entrenamiento más duro, el trabajo antes del placer, el no que debías — y regístrala como Evidencia #1 en una lista que crecerá. No busques la acción impresionante: busca la inequívoca, la que tu identidad vieja jamás habría hecho.', 'Clear define cada acción como un voto por el tipo de persona que quieres ser: la identidad no se declara, se elige voto a voto. La evidencia acumulada es lo único que convence al cerebro escéptico.', 'James Clear'),
  (37, 2, 6, 'will', 'Incantación con el cuerpo encendido', 'Toma tu frase de identidad del contrato y conviértela en incantación: repítela hoy en voz alta, con volumen y con el cuerpo en movimiento — caminando fuerte, entrenando, gesticulando. Mínimo 2 minutos seguidos, dos veces en el día. No es una afirmación susurrada desde el sofá: es un estado fisiológico completo gritándole al sistema nervioso quién manda ahora.', 'Robbins distingue la afirmación (que el cerebro rechaza por falsa) de la incantación: al involucrar fisiología total y repetición emocional, la nueva creencia se instala como experiencia y no como deseo.', 'Tony Robbins'),
  (38, 2, 6, 'will', 'Preguntas de poder matutinas', 'Instala el ritual de Robbins: cada mañana, responde 3 preguntas diseñadas para dirigir el foco — ¿Qué hay en mi vida ahora mismo por lo que puedo estar genuinamente agradecido? ¿Qué me emociona o me emocionaría hoy si lo decidiera? ¿Qué voy a aportar hoy que nadie me pidió? La calidad de tus preguntas habituales determina la calidad de tu vida: el cerebro responde lo que le preguntes.', 'Robbins enseña que pensar ES preguntar y responder: quien se pregunta "¿por qué siempre me pasa esto?" recibe basura; quien pregunta "¿qué puedo aprovechar de esto?" recibe recursos. Cambiar las preguntas cambia el foco, y el foco fabrica la experiencia.', 'Tony Robbins'),
  (39, 2, 6, 'action', 'Hábitos anclados a identidad', 'Reformula hoy tus 2 hábitos clave en lenguaje de identidad y úsalo todo el día: no "tengo que entrenar" sino "soy alguien que entrena pase lo que pase"; no "debería escribir" sino "soy alguien que se examina a diario". Cuando surja pereza, la pregunta no es "¿tengo ganas?" sino "¿qué haría la persona del contrato?". Las ganas son clima; la identidad es el terreno.', 'El hábito basado en resultados se agota cuando el resultado tarda; el basado en identidad se autorefuerza porque cada ejecución confirma quién eres. Es la tesis central de Clear y el capítulo de identidad de Robbins a la vez.', 'James Clear / Robbins'),
  (40, 2, 6, 'action', 'Recompensa y celebración', 'Define y agenda la recompensa sana del cierre de tu ciclo semanal (comida favorita, plan que disfrutes, compra pequeña) — solo si el ciclo se cierra completo. Y desde hoy celebra en el acto cada hábito cumplido: puño cerrado, un "bien" en voz alta, la casilla marcada con ganas. El cerebro consolida lo que recompensa de inmediato; no dejes ningún cierre sin señal.', 'Martell exige recompensa significativa en su protocolo y Howes cierra su método con celebrar: eres suficiente. El sistema nervioso necesita sentir que ganar se siente a ganar, o buscará el premio en el evasor.', 'Martell / Howes'),
  (41, 2, 6, 'perception', 'El expediente de evidencia', 'Relee tus registros desde el día 1 y arma el expediente: lista numerada de al menos 10 pruebas concretas de que ya estás actuando como la nueva identidad (días limpios, olas surfeadas, compromisos cumplidos, la conversación que sí tuviste). Ponla donde la veas a diario. Cuando la autoduda alegue, no discutas: presenta el expediente.', 'Howes enseña que contra la autoduda no se argumenta: se presenta evidencia. La identidad se consolida con pruebas revisadas, no con esperanza.', 'Lewis Howes'),
  (42, 2, 6, 'perception', 'Retro semana 6: el marcador', 'Pregunta de la semana: ¿quién ganó más días, la identidad vieja o la nueva? Cuenta los días de cada una con honestidad total y escribe qué inclinó la balanza en cada caso: ¿el entorno? ¿el cansancio? ¿una emoción específica? El patrón que encuentres es tu objetivo táctico de la semana 7.', 'El marcador honesto identidad vieja vs nueva te dice si el contrato opera o decora. Los datos sin drama son el estilo de la casa estoica.', 'Plan 90 días'),

  -- SEMANA 7: Bucles competidores (NAC de Robbins completo)
  (43, 2, 7, 'action', 'La palanca: dolor y placer', 'Antes de sustituir tu bucle, consigue palanca total (paso 2 del método de Robbins): escribe dos páginas — una con TODO el dolor que te costará este hábito en 5 años si no cambia (salud, relaciones, autoimagen, dinero, tiempo), y otra con TODO el placer de haberlo reemplazado. Léelas en voz alta. El cambio ocurre cuando no cambiar duele más que cambiar.', 'Robbins enseña que toda conducta humana obedece a dos fuerzas: evitar dolor y ganar placer. Su Condicionamiento Neuro-Asociativo empieza asociando dolor masivo e inmediato al patrón viejo — sin palanca emocional, la información no mueve nada.', 'Tony Robbins'),
  (44, 2, 7, 'action', 'Sustitución uno a uno', 'Elige el reemplazo directo de tu conducta de evasión y ejecútalo hoy en CADA impulso: ¿urgencia de scrollear? 10 sentadillas o 10 respiraciones. ¿Ansiedad de comer? Té caliente y una nota en el cuaderno. ¿Aburrimiento? 5 minutos de caminata. Mismo disparador, misma recompensa (alivio), conducta nueva. El paso 4 del método: la alternativa debe estar decidida y a la mano ANTES del impulso.', 'El bucle no se elimina: se le pone a competir una alternativa que cubra la misma necesidad. Robbins lo llama crear la alternativa empoderante; Clear, hacer que el hábito bueno sea la respuesta obvia.', 'Robbins / Clear'),
  (45, 2, 7, 'action', 'Dieta de dopamina', 'Un día completo sin estímulos de alta intensidad: sin redes, sin azúcar, sin series, sin noticias, sin pornografía. Solo recompensas naturales: comida real, conversación cara a cara, movimiento, naturaleza, lectura, silencio. Registra a qué horas la urgencia de estímulo grita más fuerte: esos son tus horarios vulnerables, apúntalos para blindarlos.', 'Restringir la gratificación instantánea 24 horas resensibiliza el circuito de recompensa y te muestra sin anestesia cuánto dependías del estímulo. Holiday lo llamaría un día de templanza; la neurociencia, un reset de línea base.', 'Holiday / neurociencia'),
  (46, 2, 7, 'action', 'Trabajo profundo: sitzfleisch', 'Un bloque de 90 minutos de trabajo profundo en tu proyecto más importante: teléfono en otra habitación, una sola pestaña, cronómetro visible. Cuando quieras levantarte, aplica la vieja palabra alemana sitzfleisch: quedarse en la silla hasta terminar. La incomodidad de seguir sentado ES el entrenamiento, no un efecto secundario.', 'Holiday cuenta cómo los grandes se distinguen por la capacidad de aguantar en la silla: Edison probó seis mil filamentos. El foco sostenido es el músculo exactamente opuesto a la evasión — cada bloque lo hipertrofia.', 'Ryan Holiday / Martell'),
  (47, 2, 7, 'will', 'Aburrimiento voluntario', 'Siéntate 20 minutos sin hacer absolutamente nada: sin celular, sin música, sin libro, sin "meditar" siquiera. Solo tú y el vacío. Observa la urgencia de estímulo subir, gritar y — si no le obedeces — bajar. Es la ola de siempre, en su forma más pura. La intolerancia al aburrimiento es el motor silencioso de todas tus fugas: hoy le cortas el combustible.', 'Solà enseña que el cerebro rinde su máximo bajo estímulos neutros, y Brewer que la urgencia no atendida se extingue. Quien puede estar solo con su mente sin huir ya no necesita ninguno de sus evasores.', 'Solà / Brewer'),
  (48, 2, 7, 'action', 'Condicionamiento: repetir hasta el surco', 'Hoy toca el paso 5 del método de Robbins: condicionar. Ejecuta tu sustitución (impulso → conducta nueva) tantas veces como aparezca el impulso, y CELEBRA cada ejecución en el acto con emoción real — puño, sonrisa, un "eso es". La repetición con intensidad emocional es lo que talla el surco neuronal nuevo. Sin emoción, es solo información; con emoción, es condicionamiento.', 'Robbins insiste: el condicionamiento requiere repetición + intensidad emocional. Cada ciclo impulso→alternativa→celebración debilita la autopista vieja y pavimenta la nueva.', 'Tony Robbins'),
  (49, 2, 7, 'perception', 'Retro semana 7: ¿ya compite tu bucle?', '¿Cuántas veces esta semana el impulso terminó en la conducta nueva en vez de la vieja? Escribe el marcador exacto (nuevo vs viejo) y qué sustitución funcionó mejor. Prueba de Robbins (paso 6): imagina el disparador ahora mismo — ¿qué conducta aparece primero en tu mente? Si ya aparece la nueva, el condicionamiento está prendiendo.', 'El bucle competidor gana por repetición contabilizada, no por intención. Verificar que la nueva asociación funciona es el paso final del Condicionamiento Neuro-Asociativo.', 'Tony Robbins'),

  -- SEMANA 8: Trabajo con la sombra (Howes: máscaras + sanar el pasado)
  (50, 2, 8, 'perception', 'Admitir: la conducta y su máscara', 'Escribe la conducta de autosabotaje que aún persiste (perfeccionismo que paraliza, búsqueda de validación, procrastinación del proyecto importante) y la ganancia evasiva que te da. Luego identifica qué máscara la protege: ¿la del estoico que no siente? ¿la del invencible que no teme? ¿la del sabelotodo que no pregunta? ¿la del bromista que esquiva lo serio? Nombra tu máscara principal sin adornos.', 'Howes mapeó las máscaras con que los hombres esconden su humanidad — estoico, invencible, alfa, bromista, sabelotodo — y descubrió que cada una protege una herida y cobra un precio en conexión. No se puede transformar lo que la máscara sigue tapando.', 'Lewis Howes'),
  (51, 2, 8, 'perception', 'Observar: los pródromos del sabotaje', 'Monitorea hoy sin juicio los disparadores corporales y emocionales que anteceden a tu autosabotaje: ¿qué pasa justo antes? ¿qué sensación (tensión, vacío, aceleración), qué pensamiento ("no va a quedar bien", "mejor después"), qué situación (exposición, evaluación, comparación)? Solo registra, como el científico del día 3 pero apuntando al saboteador.', 'El autosabotaje tiene pródromos visibles: aprender a verlos venir te da el segundo que necesitas para elegir. Howes lo llama entender el ciclo mente-en-movimiento: pensamiento → emoción → decisión → refuerzo del autoconcepto.', 'Lewis Howes'),
  (52, 2, 8, 'will', 'Ventilar: la carta que no se envía', 'Escribe la carta que nunca enviarás: a la situación o persona ligada a la herida que originó tu patrón de protección. Di absolutamente todo — rabia, tristeza, lo injusto, lo que necesitabas y no llegó. Al terminar, identifica el voto de sombra que hiciste entonces ("nunca más voy a confiar / mostrarme / necesitar a nadie"). Ese voto te protegió una vez; hoy te cobra intereses.', 'Howes narra cómo contar por primera vez su propia herida fue el punto de quiebre de su vida adulta: lo que no se ventila, gobierna. Los votos de autolimitación se hicieron para sobrevivir a algo que ya pasó.', 'Lewis Howes'),
  (53, 2, 8, 'will', 'Reformular: la herida como currículum', 'Reescribe esa historia como catalizador, en una página: ¿qué fortaleza, sensibilidad o radar construyó en ti esa experiencia? ¿A quién entiendes o puedes ayudar gracias a ella? ¿Qué parte de tu misión nace exactamente ahí? No es negar el daño: es decidir qué produce el daño de aquí en adelante. Frankl lo llamaba valores de actitud: la última libertad.', 'Howes convierte su mayor vergüenza en su mayor servicio y Frankl demostró en el extremo que el sufrimiento inalterable se transforma en logro al elegir su significado. La herida reformulada deja de ser techo y se vuelve piso.', 'Howes / Frankl'),
  (54, 2, 8, 'action', 'La culpa como brújula', 'Elige un error real de tu pasado que aún te pese. Extrae de él UNA rectificación concreta ejecutable hoy — la disculpa pendiente, el pago, el cambio de conducta visible — y hazla antes de dormir. La culpa sana no es un castigo perpetuo: es la brecha entre lo que hiciste y tus valores pidiendo ser cerrada con un acto, no con rumiación.', 'Frankl enseña que la culpa bien usada revela la distancia entre conducta y valores e insta a la rectificación inmediata. La rumiación mira el pasado; la rectificación lo redime.', 'Viktor Frankl'),
  (55, 2, 8, 'action', 'El 80% a propósito', 'Entrega o publica hoy algo al 80% deliberadamente: el informe sin la tercera revisión, el mensaje sin pulir dos veces, el avance imperfecto. Observa: el mundo no se acaba, nadie te expulsa, y lo hecho empieza a existir mientras lo perfecto seguía en borrador. El perfeccionismo es la máscara del sabelotodo casada con el miedo al juicio: hoy le fallas a ambos a propósito.', 'Howes identifica el miedo al juicio como uno de los tres grandes asesinos de la grandeza, y Brown que el perfeccionismo es autosabotaje disfrazado de estándar. La entrega imperfecta repetida es su antídoto exacto.', 'Howes / Brown'),
  (56, 2, 8, 'perception', 'Retro semana 8: la sombra nombrada', '¿Qué parte de tu sombra ya puedes nombrar sin vergüenza? Escríbela en una frase en tercera persona ("hay una parte de mí que aprendió a esconderse para no ser juzgada"). ¿Qué máscara sigue puesta y en qué contextos? Lo integrado ya no necesita esconderse ni mandar: mide cuánto de tu sombra ya camina a tu lado en vez de empujarte por la espalda.', 'Nombrar la sombra sin vergüenza es la medida del trabajo hecho. Howes insiste en que quitarse la máscara no es debilidad expuesta: es fuerza que ya no necesita disfraz.', 'Lewis Howes'),

  -- SEMANA 9: Incomodidad voluntaria (Holiday: templanza + Howes: conversión del miedo)
  (57, 3, 9, 'will', 'Premeditatio malorum', 'Visualiza en detalle y por escrito perder algo que valoras: el empleo, la salud de alguien, el proyecto. No como morbo: como ensayo. Escribe cómo respondería tu mejor versión el primer día, qué haría la primera semana, qué quedaría en pie que nadie puede quitarte (tu criterio, tu palabra, tu capacidad de empezar). Termina agradeciendo que hoy no pasó — con detalle.', 'Séneca ensayaba la pérdida para quitarle al azar el monopolio de la sorpresa: el golpe imaginado con calma duele la mitad cuando llega, y mientras no llega, fabrica gratitud. Es el ejercicio estoico con mejor relación costo-beneficio.', 'Séneca'),
  (58, 3, 9, 'will', 'La dosis de dificultad', 'Elige tu dosis de dificultad voluntaria hoy: ducha fría, entrenamiento más duro de lo cómodo, ayuno corto (si tu salud lo permite), subir por las escaleras cargado. El malestar es el ejercicio, no el efecto secundario: estás demostrándole al sistema nervioso que la incomodidad no es una emergencia, es un clima.', 'Holiday dedica la primera parte de su libro a la disciplina del cuerpo: los grandes se entrenan en lo duro voluntario para que lo duro involuntario los encuentre ya entrenados. Robbins lo llama expandir el umbral de lo que puedes sostener.', 'Ryan Holiday / Robbins'),
  (59, 3, 9, 'action', 'Convierte el miedo en combustible', 'Identifica tu miedo activo más frecuente (fallar, tener éxito y no sostenerlo, ser juzgado) y aplícale el kit de conversión: 1) Escríbelo en su versión más catastrófica y ponle probabilidad real. 2) Pregúntate: ¿qué me está costando este miedo cada mes que le obedezco? 3) Hazle hoy UNA desobediencia concreta: la intervención, el envío, la pregunta que el miedo prohíbe. El miedo no se debate: se desobedece en dosis.', 'Howes clasifica los tres miedos que matan la grandeza — al fracaso, al éxito y al juicio — y su kit de conversión los convierte en datos y acciones. El miedo desobedecido en pequeño pierde autoridad en grande.', 'Lewis Howes'),
  (60, 3, 9, 'will', 'Renuncia voluntaria', 'Renuncia hoy a un placer cotidiano que das por hecho: el café, el postre, la serie, la siesta. No por castigo: para comprobar que puedes y recordar que es un lujo, no una necesidad. Nota cuántas veces tu mano va sola hacia lo renunciado: cada una es una mini-ola, y hoy las surfeas todas.', 'Séneca practicaba días de pobreza voluntaria preguntándose: ¿es esto lo que tanto temía? La renuncia periódica inmuniza contra la esclavitud de la comodidad y renueva el sabor de lo ordinario.', 'Séneca / Holiday'),
  (61, 3, 9, 'will', 'Intención paradójica', 'Toma algo que te genera ansiedad anticipatoria — que te tiemble la voz, quedarte en blanco, sonrojarte — y deséalo deliberadamente hoy: intenta que te pase, exagéralo mentalmente hasta que dé risa ("voy a temblar tanto que provocaré un sismo"). La ansiedad anticipatoria vive de que huyas de ella; al perseguirla con humor, le quitas el empleo.', 'Frankl usaba la intención paradójica con éxito clínico: lo que se desea con humor deja de poder amenazarte, porque el círculo miedo-del-miedo se rompe por el lado que nadie espera.', 'Viktor Frankl'),
  (62, 3, 9, 'action', 'Entrena el no', 'Pide hoy algo sabiendo que probablemente te lo nieguen: un descuento, un favor grande, una excepción. El objetivo NO es conseguirlo: es escuchar el no, sostenerlo con el cuerpo relajado y comprobar que no pasa nada. Registra qué sentiste 10 segundos antes de pedir: ese pico es el músculo trabajando.', 'El miedo al rechazo gobierna más decisiones que el rechazo mismo. Howes lo ubica dentro del miedo al juicio: la exposición voluntaria en dosis controladas es el único desensibilizador probado.', 'Howes / escalera social'),
  (63, 3, 9, 'perception', 'Retro semana 9: los cuatro pilares', 'Puntúa de 1 a 10 tus cuatro pilares tras la semana de incomodidad: tolerancia (calma bajo presión), contención (estabilidad tras el golpe), resiliencia (velocidad de recuperación) y adaptabilidad (salir mejor). Compara con lo que habrías puntuado el día 1. ¿Cuál subió más? ¿Cuál sigue siendo el eslabón débil? Esa es tu dosis de la próxima semana.', 'Los pilares del carácter solo se miden en contacto con la dificultad: una semana de incomodidad voluntaria te dio los datos que un año de comodidad esconde.', 'Solà / Holiday'),

  -- SEMANA 10: Misión trascendente (Frankl + Howes: Misión Significativa)
  (64, 3, 10, 'will', 'Valores de creación', 'Responde por escrito: ¿qué produces o aportas que trascienda tu comodidad? Define tu proyecto de sentido para esta temporada: algo que sirva a tu entorno — trabajo con propósito, mentoría, creación, voluntariado. Aplica el filtro de Howes: una misión significativa cruza lo que te apasiona con lo que haces bien y con lo que otros necesitan. Escribe 3 candidatos y elige uno.', 'El sentido se realiza primero creando: es la primera avenida de valores de Frankl. Howes añade el diagnóstico moderno: la falta de misión clara es la raíz del autosabotaje — sin norte, las emociones se vuelven mecanismos de evasión.', 'Frankl / Howes'),
  (65, 3, 10, 'will', 'Valores de experiencia', 'Dedica hoy 30 minutos a recibir el mundo conscientemente: naturaleza sin celular, música con atención total, una conversación con presencia completa, arte contemplado de verdad. No produzcas nada. El sentido no solo se fabrica: también se recibe — pero solo si hay alguien en casa cuando llega.', 'La segunda avenida de valores de Frankl es la experiencia: la belleza y el encuentro auténtico llenan el mismo vacío que la evasión intenta tapar. Media hora de presencia real vale más que cinco horas de estímulo.', 'Viktor Frankl'),
  (66, 3, 10, 'will', 'Valores de actitud', 'Identifica tu sufrimiento inevitable actual — lo que no puedes cambiar: una pérdida, una condición, un contexto — y decide por escrito la actitud con la que lo vas a portar. Frase completa: "No elegí X, pero elijo enfrentarlo con Y". Esa elección es tuya e inalienable: nadie ha podido quitársela nunca a nadie.', 'Frankl lo demostró donde nadie podría refutarlo: cuando no se puede cambiar la situación, el último reducto de libertad es la actitud. Ahí la tragedia se convierte en logro personal.', 'Viktor Frankl'),
  (67, 3, 10, 'will', 'La vida te pregunta', 'Invierte la pregunta: en lugar de "¿qué me da la vida?", escribe qué te está exigiendo esta temporada — ¿reconstruir salud? ¿ordenar finanzas? ¿reparar una relación? ¿crear algo que no existe? Elige la exigencia más incómoda de la lista y respóndele hoy con una acción concreta antes de dormir. La responsabilidad existencial se demuestra en actos, no en ensayos.', 'La revolución copernicana de Frankl: no interrogas a la vida — la vida te interroga, a cada instante, y tu vida es la serie de tus respuestas.', 'Viktor Frankl'),
  (68, 3, 10, 'will', 'Misión en una frase', 'Redacta tu misión trascendente para esta temporada en UNA frase con estructura: a quién sirves + qué haces por ellos + por qué importa. Prueba de calidad de Howes: ¿te da un poco de miedo y mucha energía a la vez? ¿Funciona un lunes gris? Pégala visible: espejo, fondo de pantalla, primera página del cuaderno.', 'Howes hace redactar la Declaración de Misión Significativa porque el norte escrito convierte la disciplina en devoción: ya no te fuerzas a practicar — practicas porque hay alguien esperando tu mejor versión.', 'Lewis Howes'),
  (69, 3, 10, 'action', 'Servicio directo', 'Haz hoy algo por alguien que no pueda devolvértelo: tiempo, conocimiento, ayuda concreta, reconocimiento sincero. Sin publicarlo, sin cobrarlo, sin contarlo. Nota el efecto secundario: el vacío que tu evasor solía tapar se llena solo durante unas horas. Apunta esa sensación en el expediente de evidencia.', 'Howes cierra su escuela de grandeza con una vida de servicio y Frankl con la autotrascendencia: la contribución es la necesidad más alta y el único placer sin resaca. Dar sin retorno confirma que ya no operas desde la escasez.', 'Howes / Frankl'),
  (70, 3, 10, 'perception', 'Retro semana 10: prueba de estrés de la misión', 'Somete tu misión a la prueba de estrés: ¿aguanta un día malo? ¿Te levantaría un lunes gris a las 5:50? ¿La entiende un niño de 10 años? Si falla alguna, refínala: más concreta, más tuya, menos diseñada para impresionar. La misión de verdad se reconoce porque funciona exactamente cuando la motivación no está.', 'Frankl citaba a Nietzsche: quien tiene un porqué puede soportar casi cualquier cómo. La retro semanal verifica que tu porqué sea de carga y no de vitrina.', 'Frankl / Howes'),

  -- SEMANA 11: Amor fati y memento mori (Diario Estoico: noviembre/diciembre)
  (71, 3, 11, 'will', 'Memento mori', 'Medita 10 minutos sobre tu finitud: el tiempo es tu único recurso no renovable, y no sabes cuánto queda en la cuenta. Escribe: si me quedaran 52 semanas, ¿qué haría distinto esta misma semana? ¿Qué dejaría de aplazar? ¿A quién le diría qué? Elige UNA de esas respuestas y hazla hoy. No mañana: hoy.', 'Los estoicos meditaban sobre la muerte no por morbo sino por matemática: Séneca enseña que no tenemos poco tiempo, sino que perdemos mucho. La conciencia de la finitud es el asesino natural de la procrastinación existencial.', 'Séneca / Marco Aurelio'),
  (72, 3, 11, 'will', 'Amor fati', 'Toma tu revés más reciente y escríbelo como si lo hubieras elegido: "Elegí que esto pasara porque me habilita a...". No es negación del dolor: es apropiación del destino. Completa con 3 cosas concretas que este revés te entrena, te enseña o te abre. Luego camina 10 minutos repitiendo la conclusión.', 'Amor fati — no solo aceptar lo que pasa sino quererlo — es el tema de noviembre del año estoico de Holiday: el fuego usa como combustible todo lo que le echan. La adversidad apropiada deja de ser obstáculo y se vuelve materia prima.', 'Holiday / Nietzsche'),
  (73, 3, 11, 'will', 'El obstáculo es el camino', 'Identifica tu impedimento número 1 actual y conviértelo en el ejercicio mismo: ¿te bloquea la falta de tiempo? Entonces tu entrenamiento es priorizar. ¿Un colega difícil? Tu entrenamiento es negociar. ¿La incertidumbre? Tu entrenamiento es actuar sin garantías. Escribe el plan de conversión y ejecuta el primer paso hoy.', 'Marco Aurelio lo dejó escrito para sí mismo: lo que estorba a la acción hace avanzar la acción; lo que se atraviesa en el camino se convierte en camino. El impedimento contiene exactamente el entrenamiento que te falta.', 'Marco Aurelio / Holiday'),
  (74, 3, 11, 'will', 'La vista desde arriba', 'Ante tu problema más pesado, haz el ejercicio de perspectiva de Marco Aurelio: visualízalo desde el techo, luego desde la ciudad, desde el país, desde el planeta, desde un siglo después. Escribe qué tamaño real tiene a cada altura. Después baja de vuelta y actúa sobre él con el tamaño corregido — la acción es más limpia cuando el pánico no infla al enemigo.', 'La vista cósmica no minimiza tu vida: recalibra la urgencia. Marco Aurelio gobernaba un imperio en guerra y peste con este ejercicio; tu bandeja de entrada lo resistirá.', 'Marco Aurelio'),
  (75, 3, 11, 'will', 'Gratitud de francotirador', 'Escribe 3 gratitudes específicas de hoy conectadas a tu propósito. Prohibido lo genérico: no "mi familia" sino "la pregunta que me hizo X en el almuerzo porque me obligó a repensar Y". Detalle o no cuenta. La gratitud de francotirador entrena al cerebro a encontrar evidencia de sentido en el día ordinario, que es donde vives.', 'Robbins abre sus mañanas con gratitud dirigida porque el foco fabrica la emoción, y Howes la usa como antídoto de la escasez. La genérica se vuelve trámite; la específica recablea.', 'Robbins / Howes'),
  (76, 3, 11, 'will', 'El día diseñado', 'Vive hoy un día ordinario como si lo hubieras diseñado: presencia total en lo cotidiano — el café, el trayecto, la reunión, la cena. Cada vez que la mente huya al futuro o al celular, tráela con suavidad: "esto también lo elegí". La vida no está después del programa ni del proyecto: es esto, hoy, ya.', 'Los estoicos enseñan que se puede vivir bien incluso en un palacio — o en un martes. Diciembre del año estoico medita la mortalidad para concluir esto: el día ordinario presente ES la vida que temías perder.', 'Marco Aurelio / Holiday'),
  (77, 3, 11, 'perception', 'Retro semana 11: la adversidad agradecida', 'Pregunta mayor: ¿qué adversidad de estos 77 días ya agradeces? Escribe cómo algo que parecía en contra terminó siendo a favor — o qué te enseñó que nada más te habría enseñado. Si puedes agradecer la adversidad pasada en concreto, el amor fati dejó de ser teoría y ya opera en tu sistema.', 'Howes convierte la adversidad en ventaja como capítulo fundacional de la grandeza: el pasado no se cambia, pero su función sí. La retro lo verifica con tus propios datos.', 'Howes / Holiday'),

  -- SEMANA 12: Entorno, equipo y soberanía (Martell + Howes: School of Greatness / Make Money Easy)
  (78, 3, 12, 'perception', 'Auditoría del círculo', 'Lista tus 10 relaciones más frecuentes. Junto a cada una marca sin juicio moral: ¿eleva tu estándar o lo baja? ¿te acerca a tu contrato o a tu bucle? ¿es de alta reciprocidad o solo drena? Los promedios importan: tu sistema nervioso calibra su "normal" con las 5 personas que más ves. Identifica quién sube tu promedio y quién lo hunde.', 'Howes dedica un capítulo a construir el equipo ganador: nadie llega solo a la grandeza, y el entorno de referencia define el estándar mínimo que tu cerebro acepta como normal.', 'Howes / Solà'),
  (79, 3, 12, 'action', 'Curaduría relacional', 'Ejecuta hoy una decisión de la auditoría: reduce deliberadamente el contacto con una influencia de evasión (sin drama: menos disponibilidad, menos plan) y agenda tiempo real esta semana con una persona que eleve tu estándar. Bonus de Howes: identifica un posible mentor y da el primer paso — un mensaje específico agradeciendo algo concreto de su trabajo.', 'La depuración del entorno no es soberbia: es proteger el sistema en construcción. Howes insiste en pedir a los mejores que te adopten: el mentor correcto comprime años de aprendizaje en meses.', 'Solà / Howes'),
  (80, 3, 12, 'perception', 'Las Seis Fs', 'Puntúa de 1 a 10 tus seis áreas: Fe (propósito/trascendencia), Familia y amigos, Fitness (energía física), Finanzas, Futuro yo (aprendizaje) y Fun (recreación sana). Sé honesto: la nota es de HOY, no del año pasado ni del plan. Identifica la más baja y escribe por qué está así — sin excusas, solo mecánica: ¿qué falta de sistema la tiene ahí?', 'Martell usa las Seis Fs porque el crecimiento desbalanceado se cobra después: la F más baja es la fuga por donde se drenará todo lo demás. El diagnóstico sin acción es entretenimiento; mañana toca actuar.', 'Dan Martell'),
  (81, 3, 12, 'action', 'Acción en tu F débil', 'Ejecuta hoy una acción concreta en tu área más baja: la llamada a la familia, la cita médica agendada, el presupuesto abierto, la clase inscrita, el plan de diversión sana puesto en el calendario. Hoy, no esta semana. La F débil no mejora con conciencia: mejora con la primera acción incómoda y con el sistema que instales después de ella.', 'Martell convierte el diagnóstico en calendario: cada área débil necesita un sistema mínimo, no una intención máxima. La primera acción rompe la inercia; el sistema evita recaer.', 'Dan Martell'),
  (82, 3, 12, 'action', 'Soberanía financiera: la historia del dinero', 'Dos partes hoy: 1) Escribe tu historia del dinero — ¿qué aprendiste de niño sobre el dinero, de quién, y cómo esa historia opera hoy en tus decisiones (miedo, culpa, evasión, estatus)? 2) Revisa tus gastos del último mes: ¿cuánto fue consumo de dopamina y cuánto construcción de sistemas (ahorro, inversión, educación)? Haz UN ajuste concreto hoy: una suscripción menos, una transferencia automática más.', 'Howes sostiene que el dinero fluye con facilidad solo cuando sanas la historia emocional que lo bloquea: el consumo compulsivo es el mismo bucle de dopamina con otro disfraz. La soberanía del tiempo se compra con sistemas, no con ingresos.', 'Lewis Howes / Martell'),
  (83, 3, 12, 'action', 'Enseña lo aprendido', 'Comparte hoy con alguien — colega, amigo, familiar — la herramienta de estos 90 días que más te sirvió: enséñale el protocolo de 5 pasos, el examen nocturno o la dicotomía del control. Enséñalo bien: contexto, pasos, por qué funciona. Lo que puedes enseñar con claridad es lo único que de verdad aprendiste.', 'Howes estructura toda su escuela sobre esta mecánica: aprender → aplicar → enseñar. Enseñar consolida el conocimiento propio y cumple a la vez el servicio que da sentido — doble pago por el mismo acto.', 'Howes / Frankl'),
  (84, 3, 12, 'perception', 'Retro semana 12: la arquitectura', '¿Tu entorno completo — personas, espacios, pantallas, agenda, dinero — ya sostiene tu estándar mínimo o todavía lo sabotea en algún flanco? Lista lo que queda por depurar y agenda cuándo. Verdad incómoda de cierre: al final no te sostiene la motivación sino la arquitectura. Revisa los planos.', 'Clear lo resume: no subes al nivel de tus metas, caes al nivel de tus sistemas. La semana 12 audita que el sistema completo esté a la altura del contrato.', 'James Clear / Martell'),

  -- SEMANA 13: Evaluación final (Howes: celebrar — eres suficiente)
  (85, 3, 13, 'evaluation', 'Kit de prevención de recaídas', 'Crea tu documento de emergencia en una página: tus 3 gatillos principales (con horario y contexto), tus planes if-then, el protocolo de 5 pasos, tus 3 citas estoicas de guardia y 2 contactos de apoyo con permiso para preguntarte sin filtro. Guárdalo accesible: notas del celular y papel. La recaída no se previene con confianza sino con protocolo.', 'El kit es tu plan de contingencia escrito en tiempos de paz: Séneca enseñaba que el sabio no es quien nunca cae sino quien tiene decidido, de antemano, cómo se levanta.', 'Evaluación / Séneca'),
  (86, 3, 13, 'evaluation', 'Relectura del día 1', 'Relee tu diario de identidad del día 1 y tu declaración de guerra del día 7. Escribe la distancia recorrida: ¿qué creencia limitante murió? ¿qué haces hoy con naturalidad que entonces parecía imposible? ¿qué sigue igual y merece el siguiente ciclo? Medirte contra tu punto de partida — no contra un ideal — es la única evaluación honesta.', 'Howes cierra su método celebrando el progreso real: compararte con tu día 1 construye; compararte con la perfección o con otros, destruye. Los datos de tu propio recorrido son el único jurado válido.', 'Lewis Howes'),
  (87, 3, 13, 'evaluation', 'Carta al día 180', 'Escribe una carta a tu yo de dentro de 90 días: qué debe seguir haciendo sin negociar, qué señales tempranas de recaída debe vigilar (sé específico: horarios, excusas favoritas, personas), qué le agradeces por no haberse rendido este trimestre. Séllala con fecha de apertura. El mejor guardián de tu progreso eres tú, con memoria.', 'La carta al futuro fija el estándar y crea un pacto entre versiones de ti: convierte la continuidad — el punto exacto donde casi todos los programas mueren — en un compromiso personal con nombre propio.', 'Evaluación'),
  (88, 3, 13, 'evaluation', 'Contrato 2.0', 'Actualiza tu contrato sagrado con la evidencia de 90 días: qué cláusulas suben de estándar (ya te quedaron pequeñas), cuáles se ajustan a la realidad (eran de vitrina), cuál nueva entra (la que el trimestre te enseñó que faltaba). Fírmalo de nuevo, con fecha. El contrato es un documento vivo: la versión con cicatrices vale más que la versión con esperanza.', 'Robbins enseña que la identidad se expande por decisión y evidencia: el contrato 2.0 consolida al que ya eres y apunta al que sigues. Sin actualización, el documento se vuelve nostalgia.', 'Robbins / Solà'),
  (89, 3, 13, 'evaluation', 'La siguiente temporada: el sistema sostenible', 'Diseña la siguiente temporada — no otro sprint de 90 días: el sistema sostenible. Define: qué prácticas quedan diarias (exámenes, estándar mínimo), cuáles semanales (retro, dosis de dificultad, servicio), cuál es tu estándar mínimo permanente y qué proyecto de sentido lidera el próximo trimestre. Los 90 días fueron el andamio; el edificio es la vida ordinaria con el sistema puesto.', 'Holiday insiste en que la disciplina no es una fase sino un destino que se camina a diario: el programa termina, la práctica no. El sistema sostenible es la diferencia entre una transformación y una anécdota.', 'Ryan Holiday'),
  (90, 3, 13, 'evaluation', 'Evaluación final: celebra — eres suficiente', 'Abre el informe de 90 días en la app: progreso por módulo, rachas, días perdidos, ánimo, journaling. Escribe tu retro final: quién eras, quién eres, quién sigues construyendo. Y luego — orden directa — CELEBRA de verdad: la cena, el plan, el reconocimiento en voz alta de lo que hiciste. No como premio por ser perfecto: como constancia de que apareciste 90 días.', 'Howes termina su método con la lección que casi todos se saltan: celebra, eres suficiente. La evidencia dice qué pasó; tu relato decide qué significa; la celebración le enseña al sistema nervioso que este camino paga — y que quiere volver mañana.', 'Lewis Howes')
) AS v(day_number, phase, week, module, title, instructions, rationale, source_author)
ON CONFLICT (track_id, day_number) DO UPDATE SET
  phase = EXCLUDED.phase,
  week = EXCLUDED.week,
  module = EXCLUDED.module,
  title = EXCLUDED.title,
  instructions = EXCLUDED.instructions,
  rationale = EXCLUDED.rationale,
  source_author = EXCLUDED.source_author;

-- ------------------------------------------------------------
-- RETOS SEMANALES (13)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'interna')
INSERT INTO stoic.program_weeks (track_id, week_number, theme, challenge_title, challenge_description, deliverable)
SELECT t.id, v.week_number, v.theme, v.challenge_title, v.challenge_description, v.deliverable
FROM t, (VALUES
  (1, 'Conciencia y decisión', 'Mapea tu bucle y firma la decisión', 'Completa el diario de identidad, el mapa forense de tu bucle principal (disparador, emoción, conducta, recompensa, ganancia secundaria, costo anual en horas) y la decisión formal escrita de reemplazarlo.', 'Texto de identidad (día 1) + tabla del bucle + declaración de guerra firmada con fecha.'),
  (2, 'Sustracción y cuerpo', 'Siete días sin tu evasor primario', 'Elimina tu evasor primario los 7 días con fricción física instalada, ataca el alba al menos 3 mañanas y cumple el estándar mínimo viable a diario. Regla activa: nunca fallar dos días seguidos.', 'Registro de días limpios + horas rojas recuperadas vs semana 1 + tus 3 madrugadas.'),
  (3, 'Dicotomía del control', 'Instala los dos exámenes', 'Haz el examen matutino (Marco Aurelio) y el nocturno (Séneca) al menos 5 de 7 días, más un día completo de queja cero con reformulaciones contadas.', 'Bitácora de exámenes + marcador del día de queja cero (quejas vs reformulaciones).'),
  (4, 'Regulación somática', 'Surfea cinco olas', 'Usa el protocolo de 5 pasos y el surf de olas ante al menos 5 impulsos reales sin ceder, cronometrando cuánto dura de verdad cada ola. Practica la Tríada (fisiología, foco, lenguaje) en horarios fijos.', 'Registro de impulsos: gatillo, intensidad, duración real de la ola, resultado.'),
  (5, 'Contrato de identidad', 'Firma tu contrato sagrado', 'Redacta y firma tu contrato de autoconcepto en presente y con precisión milimétrica, léelo en voz alta mañana y noche toda la semana, blinda el calendario y haz tu compromiso público con consecuencia disuasoria real.', 'El contrato firmado + nombre del testigo + la consecuencia definida + calendario blindado.'),
  (6, 'Identidad en acción', 'Siete votos y el expediente', 'Acumula 7 evidencias numeradas de la nueva identidad (una por día), practica la incantación con el cuerpo encendido y las preguntas de poder matutinas a diario, y arma el expediente de 10 pruebas.', 'Lista numerada de las 7 evidencias con fecha + el expediente de 10 pruebas visible.'),
  (7, 'Bucles competidores', 'El condicionamiento completo', 'Ejecuta el ciclo completo del método: palanca (las dos páginas de dolor/placer), sustitución 1:1 en cada impulso, un día de dieta de dopamina, 3 bloques de trabajo profundo de 90 minutos y celebración inmediata en cada ejecución.', 'Las dos páginas de palanca + marcador semanal (conducta nueva vs vieja) + registro del día de dieta.'),
  (8, 'Trabajo con la sombra', 'Quítate la máscara', 'Completa las cuatro etapas con tu patrón de autosabotaje: admitir (nombrando tu máscara principal), observar (pródromos), ventilar (la carta no enviada y el voto de sombra) y reformular (la herida como currículum). Cierra con una entrega al 80% deliberada.', 'La narrativa reescrita: qué fortaleza construyó la herida + el nombre de tu máscara + lo entregado al 80%.'),
  (9, 'Incomodidad voluntaria', 'Cinco dosis de dificultad elegida', 'Ejecuta al menos 5 incomodidades voluntarias: una física (frío/ayuno/entrenamiento), una social (pedir sabiendo el no), una renuncia, una premeditatio malorum escrita y una desobediencia directa a tu miedo dominante con el kit de conversión.', 'Registro de las 5 dosis + puntaje 1-10 de los cuatro pilares del carácter (antes vs después).'),
  (10, 'Misión trascendente', 'Tu misión en una frase', 'Recorre las tres avenidas de Frankl (creación, experiencia, actitud), redacta tu Declaración de Misión Significativa en una frase (a quién sirves + qué haces + por qué importa), iníciala con una primera acción y haz un acto de servicio sin retorno.', 'La frase de misión (pegada y visible) + la primera acción ejecutada + el acto de servicio.'),
  (11, 'Amor fati y memento mori', 'Siete días de perspectiva', 'Cada día una práctica: memento mori con acción inmediata, amor fati del último revés, el obstáculo convertido en camino, la vista desde arriba, gratitud de francotirador, el día diseñado y la retro de adversidad agradecida.', 'Siete entradas de diario, una por práctica, con la acción concreta que cada una disparó.'),
  (12, 'Arquitectura del entorno', 'Depura, balancea y sana el dinero', 'Completa la auditoría del círculo con una decisión ejecutada, contacta un posible mentor, puntúa tus Seis Fs con acción inmediata en la más débil, y escribe tu historia del dinero con un ajuste financiero concreto.', 'Lista de relaciones con dirección + puntaje Seis Fs + acción en la F débil + el ajuste financiero hecho.'),
  (13, 'Evaluación y celebración', 'Cierre de ciclo completo', 'Crea tu kit de prevención de recaídas, relee el día 1 y mide la distancia, escribe la carta al día 180, firma el contrato 2.0, diseña el sistema sostenible y CELEBRA de verdad el cierre.', 'Kit de recaídas + carta al día 180 + contrato 2.0 + diseño de la siguiente temporada + la celebración hecha.')
) AS v(week_number, theme, challenge_title, challenge_description, deliverable)
ON CONFLICT (track_id, week_number) DO UPDATE SET
  theme = EXCLUDED.theme,
  challenge_title = EXCLUDED.challenge_title,
  challenge_description = EXCLUDED.challenge_description,
  deliverable = EXCLUDED.deliverable;

-- ------------------------------------------------------------
-- HITOS MENSUALES (3)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'interna')
INSERT INTO stoic.program_months (track_id, month_number, title, description)
SELECT t.id, v.month_number, v.title, v.description
FROM t, (VALUES
  (1, 'Descompresión: percepción y cuerpo', 'Mapear el bucle con precisión forense, sustraer el evasor primario, atacar el alba, instalar el estándar mínimo viable y los exámenes matutino (Marco Aurelio) y nocturno (Séneca), y dominar el protocolo de regulación ante impulsos (Brewer + Tríada de Robbins). Hito verificable: 21 o más días del mes con el estándar mínimo cumplido, el bucle mapeado con datos reales y al menos 5 olas surfeadas sin ceder.'),
  (2, 'Identidad: el contrato en operación', 'Firmar y operar el contrato sagrado con la Regla del 300%, el vocabulario transformacional y las preguntas de poder matutinas; ejecutar el Condicionamiento Neuro-Asociativo completo (palanca, interrupción, sustitución, condicionamiento) y quitarse la máscara con el trabajo de sombra (admitir, observar, ventilar, reformular). Hito verificable: racha de 14 días sin ceder al bucle principal + expediente de 10 evidencias + la narrativa de la herida reescrita.'),
  (3, 'Trascendencia: voluntad y propósito', 'Entrenar la voluntad con incomodidad elegida y el kit de conversión del miedo; definir la Declaración de Misión Significativa y el proyecto de sentido (Frankl); practicar amor fati y memento mori; depurar el entorno, balancear las Seis Fs y sanar la historia del dinero; cerrar con el kit de recaídas, el contrato 2.0 y la celebración. Hito verificable: misión en una frase operando + proyecto de sentido en marcha + kit de recaídas terminado + evaluación final completada y celebrada.')
) AS v(month_number, title, description)
ON CONFLICT (track_id, month_number) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description;
