-- ============================================================
-- StoiComunication V2 - Seed Track 2: Práctica Interna
-- 90 días + 13 retos semanales + 3 hitos mensuales
-- Fuentes: Marco Aurelio, Séneca, Epicteto, Viktor Frankl,
--          Judson Brewer, James Clear, Martell, Howes, Robbins,
--          Solà, Brené Brown, Ryan Holiday
-- ============================================================

-- ------------------------------------------------------------
-- DÍAS (90)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'interna')
INSERT INTO stoic.program_days (track_id, day_number, phase, week, module, title, instructions, rationale, source_author)
SELECT t.id, v.day_number, v.phase, v.week, v.module, v.title, v.instructions, v.rationale, v.source_author
FROM t, (VALUES
  -- SEMANA 1: Diario de identidad y mapa de bucles
  (1, 1, 1, 'perception', 'Diario de identidad', 'Escribe 15 minutos respondiendo: ¿quién soy ahora? ¿quién quiero ser en 90 días? ¿qué creencias me limitan? Guarda este texto: lo releerás el día 86 para medir la distancia recorrida.', 'El cambio duradero es de identidad, no de conducta: primero defines quién quieres ser, luego actúas como esa persona.', 'James Clear / Howes'),
  (2, 1, 1, 'perception', 'Mapa del bucle', 'Haz la tabla de tu principal hábito de evasión (scrolling, alcohol, azúcar, juegos): Disparador → Emoción → Conducta → Recompensa. Ejemplo: "al cansarme (D) siento vacío (E), abro el celular (C) para aliviar el aburrimiento (R)".', 'No puedes interrumpir un bucle que no has mapeado: hacer visible la cadena es el primer acto de control.', 'Resumen ejecutivo / Brewer'),
  (3, 1, 1, 'perception', 'Observación sin juicio', 'Hoy solo registra: cada vez que aparezca el impulso de tu bucle, anota hora, gatillo e intensidad (1-10). No lo pelees ni te juzgues: eres un científico recolectando datos.', 'La observación curiosa y no juiciosa disuelve la identificación automática con el impulso: ya no eres el impulso, eres quien lo observa.', 'Judson Brewer'),
  (4, 1, 1, 'will', 'Las preguntas de Frankl', 'Responde por escrito: ¿por qué vale la pena esforzarse? ¿qué problema del mundo (o de tu entorno) quieres ayudar a resolver? ¿qué legado quieres dejar? No busques la respuesta perfecta: busca la honesta.', 'La adicción y la evasión florecen en el vacío existencial; la voluntad de sentido es el antídoto de fondo, no la fuerza de voluntad.', 'Viktor Frankl'),
  (5, 1, 1, 'perception', 'Auditoría del tiempo', 'Registra todas tus horas de hoy por colores: verde (construye tu futuro), amarillo (necesario neutro), rojo (evasión o destrucción). Al final del día cuantifica las horas rojas.', 'Lo que no se mide no se recupera: la auditoría revela cuánta vida se está fugando por los evasores.', 'Dan Martell'),
  (6, 1, 1, 'perception', 'La ganancia secundaria', 'Escribe qué te da realmente tu hábito de evasión en términos de necesidades: ¿certidumbre (adormece el malestar)? ¿variedad (estímulo constante)? ¿significado (validación)? Sé brutalmente honesto.', 'Todo patrón nocivo persiste porque satisface 3 o más necesidades humanas a la vez: hasta no saber cuáles, no puedes sustituirlas.', 'Tony Robbins'),
  (7, 1, 1, 'perception', 'Retro semana 1', 'Relee tus registros de la semana y nombra por escrito tu bucle número 1 a romper en estos 90 días, con su disparador principal y su ganancia secundaria. Esta es tu declaración de guerra.', 'Un enemigo con nombre, mapa y motivo es un enemigo que se puede vencer.', 'Plan 90 días'),

  -- SEMANA 2: Sustracción e ingeniería del entorno
  (8, 1, 2, 'action', 'Sustracción absoluta', 'Elimina hoy tu evasor primario por completo y ponle fricción física: borra la app, saca el licor de la casa, deja el celular en otra habitación. Que ceder requiera esfuerzo.', 'El progreso no viene de añadir más disciplina a un sistema saturado, sino de sustraer los asesinos del tiempo.', 'Dan Martell'),
  (9, 1, 2, 'action', 'Ingeniería del entorno', 'Esta noche prepara el entorno para el hábito clave de mañana: la ropa de entrenar visible, el libro en la almohada, el escritorio despejado. Haz que la conducta buena sea la opción por defecto.', 'La disciplina no se gestiona con fuerza de voluntad sino alisando el camino: menos fricción para lo bueno, más para lo malo.', 'Martell / Clear / Solà'),
  (10, 1, 2, 'action', 'Estándar mínimo viable', 'Define por escrito tu línea base innegociable de sueño (hora de acostarte), alimentación (qué no entra) y movimiento (mínimo diario). Cúmplela hoy sin excepción, con o sin motivación.', 'El estándar mínimo viable es la línea infranqueable que se respeta todos los días del año, independiente del estado de ánimo.', 'Adrià Solà Pastor'),
  (11, 1, 2, 'action', 'Descanso neutro', 'Haz hoy un bloque de 15 minutos de estímulo neutro: caminata sin dispositivos ni música bajo luz natural, o lectura reflexiva en papel. Sin excepción y sin celular en el bolsillo.', 'Los descansos neutros resensibilizan los receptores de dopamina saturados por la gratificación instantánea.', 'Solà / neurociencia'),
  (12, 1, 2, 'action', 'Planes If-Then', 'Escribe 3 planes condicionales para tus momentos de tentación: "si siento urgencia de X, entonces haré Y (respirar 4-8, tomar agua, salir a caminar 5 min)". Ensáyalos mentalmente dos veces.', 'Automatizar la respuesta saludable ANTES de que aparezca el impulso elimina la negociación mental en caliente, que casi siempre se pierde.', 'Dan Martell'),
  (13, 1, 2, 'action', 'Compromisos simples', 'Cumple hoy la cadena de compromisos mínimos: tender la cama, vaso de agua al despertar, 30 minutos de movimiento y acostarte a tu hora. Marca cada uno.', 'Los compromisos simples cumplidos le demuestran al cerebro que tu palabra interna vale: es la base de la autoconfianza real.', 'Resumen ejecutivo / Solà'),
  (14, 1, 2, 'perception', 'Retro semana 2', 'Cuantifica: ¿cuántas horas rojas recuperaste esta semana vs la semana 1? ¿Cuántos días cumpliste el estándar mínimo? Regla desde hoy: nunca fallar dos días seguidos.', 'La regla de nunca fallar dos días evita que un tropiezo se convierta en abandono: el fallo aislado es dato, el doble es patrón.', 'Martell / Clear'),

  -- SEMANA 3: Dicotomía del control
  (15, 1, 3, 'will', 'Examen matutino de Marco Aurelio', 'Dedica 10 minutos al despertar: escribe los obstáculos probables de hoy (personas difíciles, retrasos, críticas), separa qué depende de ti (tus juicios, intenciones, reacciones) y qué no, y decide cómo responderás con calma a lo incontrolable.', 'Prepararte mentalmente para la adversidad antes de que llegue te quita la sorpresa, que es la mitad del golpe.', 'Marco Aurelio'),
  (16, 1, 3, 'will', 'Examen nocturno de Séneca', 'Antes de dormir, 10 minutos por escrito: ¿qué hice mal hoy y cómo afectó mi paz o mis relaciones? ¿qué hice bien? ¿qué haría diferente? Honesto y sin autoflagelación.', 'El examen vespertino cierra el ciclo del día, promueve descanso sin ansiedad y convierte cada jornada en materia prima de mejora.', 'Séneca'),
  (17, 1, 3, 'will', 'Dicotomía radical', 'Ante cada molestia de hoy, pregúntate en el momento: ¿esto depende de mí? Si sí, actúa ahora. Si no, suéltalo conscientemente y redirige la energía a lo que sí controlas.', 'La dicotomía del control es el corazón operativo del estoicismo: toda la ansiedad vive en el territorio de lo que no depende de ti.', 'Epicteto'),
  (18, 1, 3, 'will', 'Reserva de juicio', 'Hoy no emitas juicios inmediatos. Ante lo que te altere, di internamente: "esto es una impresión, no un hecho" y espera antes de reaccionar o etiquetar.', 'No nos perturban las cosas sino nuestros juicios sobre ellas: espaciar impresión y respuesta es la libertad estoica en acción.', 'Epicteto'),
  (19, 1, 3, 'will', 'Los dos exámenes juntos', 'Haz hoy el ciclo completo: examen matutino de preparación + examen nocturno de revisión. Nota por escrito cómo cambia el cierre del día cuando lo abriste con intención.', 'Mañana y noche son los dos extremos del bucle diario: controlarlos ambos convierte el día entero en práctica.', 'Marco Aurelio / Séneca'),
  (20, 1, 3, 'will', 'Queja cero', 'Un día completo sin quejarte en voz alta. Cada queja detectada se reformula en el momento: o en acción concreta ("voy a...") o en aceptación explícita ("no depende de mí, sigo").', 'La queja es la fuga de energía del estoico: entrena al cerebro en victimismo y no cambia nada del mundo externo.', 'Plan 90 días'),
  (21, 1, 3, 'perception', 'Retro semana 3', 'Revisa la semana: ¿qué te robó más paz? ¿Estaba de tu lado de la dicotomía o del otro? ¿Cuántos días completaste ambos exámenes? Ajusta el horario si fallaste alguno.', 'Casi siempre descubrimos que lo que más paz roba está fuera de nuestro control: verlo por escrito lo vuelve innegable.', 'Plan 90 días'),

  -- SEMANA 4: Regulación somática
  (22, 1, 4, 'will', 'Protocolo de 5 pasos', 'Memoriza y usa hoy ante cualquier impulso: 1) detén el cuerpo y endereza la postura, 2) tres respiraciones con exhalación doble (4-8), 3) localiza la emoción en el cuerpo, 4) di "observo el impulso y lo dejo pasar como una ola", 5) inserta tu pensamiento de identidad.', 'La secuencia interviene el bucle en el cuerpo antes de que llegue a la conducta: cada repetición debilita el camino neuronal del hábito.', 'Plan de Cambio de Identidad'),
  (23, 1, 4, 'will', 'Olas de ansia', 'Cuando venga el craving hoy, no lo pelees ni cedas: obsérvalo con curiosidad como una ola que sube, llega a su pico y baja sola. Cronométralo: ¿cuánto duró realmente?', 'Los impulsos son como gatos callejeros: si no los alimentas con la conducta, dejan de venir. Ninguna ola dura para siempre.', 'Judson Brewer'),
  (24, 1, 4, 'will', 'Respiración programada', 'Haz 3 sesiones de respiración fisiológica hoy en horarios fijos (no reactivos): mañana, mediodía y tarde. Inhala 4, exhala 8, por 2 minutos.', 'La regulación programada baja el nivel basal de estrés, que es lo que decide si el prefrontal o el estriado toman el control del día.', 'Robbins / neurociencia'),
  (25, 1, 4, 'will', 'Mapeo somático', 'Ante cada emoción fuerte de hoy, antes de actuar, nombra dónde vive en tu cuerpo: nudo en el estómago, opresión en la garganta, calor en la cara. Solo nómbrala con curiosidad.', 'Localizar la emoción en el cuerpo activa la observación y desactiva la identificación: el marco RAIN empieza ahí.', 'Judson Brewer'),
  (26, 1, 4, 'will', 'Interrupción de patrón', 'Al detectar hoy el inicio de tu bucle, cambia de inmediato el estado físico: levántate, cambia de habitación, sal a la luz, sacude el cuerpo. Movimiento antes que argumento.', 'El cambio brusco de fisiología interrumpe el estado bioquímico del bucle: no puedes pensar diferente en el mismo cuerpo.', 'Tony Robbins'),
  (27, 1, 4, 'will', 'La oferta mayor y mejor', 'Cuando resistas un impulso hoy, escribe inmediatamente después cómo se siente la paz de no haber cedido. Compárala por escrito con lo que da la recaída.', 'El cerebro necesita evidencia de que la presencia consciente paga más que la excitación de la recaída: dásela por escrito.', 'Judson Brewer'),
  (28, 1, 4, 'perception', 'Retro semana 4 y cierre de fase', '¿Cuántas olas surfeaste sin ceder esta semana? ¿Cuál fue tu mejor intervención del protocolo de 5 pasos? Cierra la fase 1: puntúa de 1 a 10 tu conciencia del bucle y tu capacidad de regulación.', 'La fase de descompresión termina cuando ya no eres esclavo del impulso inmediato: mide cuánto te falta.', 'Plan 90 días'),

  -- SEMANA 5: Cierre fase 1 + contrato sagrado
  (29, 1, 5, 'perception', 'Examen de fase 1', 'Relee todas tus retros del mes. Escribe: ¿qué evasor sigue vivo? ¿qué práctica ya es automática? ¿qué se te olvidó por completo? Prepara la lista de lo que entra al contrato de la fase 2.', 'La revisión mensual honesta convierte 30 días de práctica en cimientos y no en anécdota.', 'Séneca / Plan 90 días'),
  (30, 1, 5, 'will', 'Día de integración', 'Ejecuta el día perfecto de fase 1: examen matutino + estándar mínimo viable + descanso neutro + protocolo ante impulsos + examen nocturno. Todo en un día.', 'Un día completo integrado es la prueba de que las piezas ya forman un sistema.', 'Plan 90 días'),
  (31, 2, 5, 'will', 'El contrato sagrado', 'Redacta formalmente tu contrato de autoconcepto: describe con precisión milimétrica cómo actúa, come, entrena, habla y descansa la persona en la que te estás convirtiendo. Fírmalo.', 'El autoconcepto es un contrato que firmas contigo: la autoconfianza real nace de cumplir la palabra dada en la intimidad.', 'Solà / Martell'),
  (32, 2, 5, 'will', 'Regla del 300%', 'Lee tu contrato en voz alta al despertar y antes de dormir. Aplica hoy la regla: 100% claridad en la identidad + 100% creencia en su viabilidad + sostener ambas el 100% del tiempo. Caza cada pensamiento de duda y reformúlalo.', 'La duda intermitente sabotea más que el fallo ocasional: la regla del 300% cierra la puerta a la conjetura de incapacidad.', 'Dan Martell'),
  (33, 2, 5, 'action', 'Bloqueo de calendario', 'Agenda tus hábitos clave de la semana como citas inamovibles en el calendario (entrenamiento, lectura, exámenes, trabajo profundo). Si no está agendado, no existe.', 'Bloquear el tiempo elimina la negociación mental del momento: la decisión ya fue tomada por tu mejor versión.', 'Dan Martell'),
  (34, 2, 5, 'action', 'Compromiso público', 'Comunica tu meta de 90 días a alguien que te pueda pedir cuentas (mentor, pareja, amigo exigente) o públicamente. Define con esa persona un chequeo semanal.', 'La presión social positiva es un sistema externo de consistencia que funciona cuando la motivación interna falla.', 'Dan Martell'),
  (35, 2, 5, 'perception', 'Retro semana 5', 'Relee tu contrato: ¿qué cláusula te cuesta más creer? Esa es exactamente la que define tu trabajo de las próximas semanas. Escribe por qué te cuesta y qué evidencia la haría creíble.', 'La cláusula increíble señala la herida de identidad: el contrato se vuelve real cláusula por cláusula, con evidencia.', 'Plan 90 días'),

  -- SEMANA 6: Identidad en acción
  (36, 2, 6, 'action', 'Afirmación en acción', 'Haz hoy una cosa que SOLO haría tu nueva identidad (la conversación que evitas, el entrenamiento más duro, el trabajo antes del placer) y regístrala como evidencia numerada: Evidencia #1.', 'Cada acción alineada es un voto por la nueva identidad: el cambio se construye con votos acumulados, no con declaraciones.', 'James Clear'),
  (37, 2, 6, 'will', 'Incantación física', 'Repite tu frase de identidad del contrato en movimiento: caminando fuerte, entrenando, con el cuerpo activado. No sentado ni susurrando: el cuerpo debe participar.', 'La afirmación intelectual el cerebro la rechaza; la incantación con fisiología comprometida recablea el sistema nervioso.', 'Tony Robbins'),
  (38, 2, 6, 'action', 'Hábitos anclados a identidad', 'Reformula hoy tus 2 hábitos clave en lenguaje de identidad: no "tengo que entrenar" sino "soy alguien que entrena X días"; no "debo escribir" sino "soy alguien que se examina a diario". Úsalo todo el día.', 'El hábito basado en resultados se agota; el basado en identidad se autorefuerza porque cada ejecución confirma quién eres.', 'James Clear'),
  (39, 2, 6, 'action', 'Recompensa significativa', 'Define y agenda la recompensa sana que te darás al cerrar el ciclo semanal de hábitos completo (comida especial, plan que disfrutes, compra pequeña). Solo si cierras el ciclo.', 'El cerebro necesita cerrar el bucle con recompensa: si no se la das sana y programada, la buscará en el evasor.', 'Dan Martell'),
  (40, 2, 6, 'action', 'Consecuencia disuasoria', 'Define un costo real y verificable si rompes el contrato esta semana: transferencia a una causa que no apoyas, confesión pública, doble entrenamiento. Comunícaselo a tu testigo.', 'La consecuencia severa y real convierte el compromiso difuso en un contrato con cláusula de penalización: el cerebro lo toma en serio.', 'Dan Martell'),
  (41, 2, 6, 'perception', 'Evidencia acumulada', 'Relee tus registros desde el día 1 y lista 10 pruebas concretas de que ya estás actuando como la nueva identidad. Numéralas. Ponlas donde las veas.', 'La identidad se consolida con evidencia revisada, no con esperanza: 10 pruebas escritas valen más que mil afirmaciones.', 'Lewis Howes'),
  (42, 2, 6, 'perception', 'Retro semana 6', 'Pregunta de la semana: ¿quién ganó más días, la identidad vieja o la nueva? Cuenta los días de cada una con honestidad y escribe qué inclinó la balanza en cada caso.', 'El marcador honesto identidad vieja vs nueva te dice si el contrato opera o decora.', 'Plan 90 días'),

  -- SEMANA 7: Bucles competidores
  (43, 2, 7, 'action', 'Sustitución uno a uno', 'Elige el reemplazo directo de tu conducta de evasión y úsalo hoy en cada impulso: ¿urgencia de scrollear? 10 sentadillas. ¿Ansiedad de comer? Té caliente. ¿Aburrimiento? 5 minutos de caminata.', 'El bucle no se elimina, se sustituye: mismo disparador, misma recompensa (alivio), conducta nueva.', 'Clear / Brewer'),
  (44, 2, 7, 'action', 'Fricción inversa', 'Reconfigura hoy tu entorno digital y físico: apps de evasión enterradas o borradas, notificaciones apagadas, el libro y las pesas visibles, el escritorio listo. Lo bueno a un paso, lo malo a diez.', 'Somos la conducta de menor fricción disponible: diseñar el entorno es decidir por adelantado.', 'Clear / Martell'),
  (45, 2, 7, 'action', 'Dieta de dopamina', 'Un día completo sin estímulos de alta intensidad: sin redes, sin azúcar, sin series, sin pornografía, sin noticias. Solo recompensas naturales: comida real, conversación, movimiento, naturaleza, lectura.', 'Restringir la gratificación instantánea por 24 horas resensibiliza el circuito de recompensa y te muestra cuánto dependías del estímulo.', 'Protocolo de reducción de estímulos'),
  (46, 2, 7, 'action', 'Trabajo profundo', 'Un bloque de 90 minutos de trabajo profundo en tu proyecto más importante: teléfono en otra habitación, una sola pestaña, cronómetro visible. Nada más existe.', 'La capacidad de foco sostenido es el músculo opuesto a la evasión: cada bloque profundo es entrenamiento doble.', 'Dan Martell'),
  (47, 2, 7, 'will', 'Aburrimiento voluntario', 'Siéntate 20 minutos sin hacer absolutamente nada: sin celular, sin música, sin libro. Observa la urgencia de estímulo subir y bajar. No es meditación formal: es tolerar el vacío.', 'La intolerancia al aburrimiento es el motor silencioso de la adicción al estímulo: entrenarla es cortar el combustible.', 'Solà / Brewer'),
  (48, 2, 7, 'action', 'Celebración inmediata', 'Hoy, al completar cada hábito o resistir cada impulso, márcalo en el momento y celebra físicamente (puño cerrado, "bien", sonrisa consciente). No dejes ningún cierre sin señal.', 'El cerebro consolida lo que recompensa de inmediato: la celebración pequeña y en el acto es el pegamento del hábito nuevo.', 'Clear / Fogg'),
  (49, 2, 7, 'perception', 'Retro semana 7', '¿Tu bucle competidor ya compite? Evidencia: ¿cuántas veces esta semana el impulso terminó en la conducta nueva en vez de la vieja? Escribe el marcador y qué sustitución funciona mejor.', 'El bucle competidor gana por repetición contabilizada, no por intención.', 'Plan 90 días'),

  -- SEMANA 8: Trabajo con la sombra
  (50, 2, 8, 'perception', 'Admitir', 'Escribe la conducta de autosabotaje que aún persiste (perfeccionismo que paraliza, búsqueda de validación, procrastinación del proyecto importante) y la ganancia evasiva que te da. Sin adornos.', 'No se puede transformar lo que no se admite: la sombra gobierna exactamente mientras permanece innombrada.', 'Lewis Howes'),
  (51, 2, 8, 'perception', 'Observar', 'Monitorea hoy sin juicio los disparadores corporales y emocionales que anteceden a tu autosabotaje: ¿qué pasa justo antes? ¿qué sensación, qué pensamiento, qué situación? Solo registra.', 'El autosabotaje tiene pródromos visibles: aprender a verlos venir es ganar el segundo que necesitas para elegir.', 'Lewis Howes'),
  (52, 2, 8, 'will', 'Ventilar', 'Escribe la carta que nunca enviarás: a la situación o persona ligada a la herida que originó tu patrón de protección. Di todo. Al terminar, identifica el "voto de sombra" que hiciste ("nunca más voy a...").', 'Los votos de autolimitación se hicieron para sobrevivir a algo que ya pasó: ventilarlos por escrito les quita el mando.', 'Lewis Howes'),
  (53, 2, 8, 'will', 'Reformular', 'Reescribe esa historia como catalizador: ¿qué fortaleza, sensibilidad o capacidad construyó en ti esa experiencia? ¿A quién puedes entender o ayudar gracias a ella? Escríbelo como narrativa nueva.', 'La logoterapia lo llama valores de actitud: el sufrimiento inalterable se transforma en logro personal al elegir qué significa.', 'Howes / Frankl'),
  (54, 2, 8, 'action', 'La culpa como brújula', 'Elige un error real de tu pasado que aún te pese. Extrae de él UNA rectificación concreta ejecutable hoy (disculpa, pago, cambio de conducta) y hazla.', 'La culpa sana no es autoflagelación: es la brecha entre lo que hiciste y tus valores, pidiendo rectificación inmediata.', 'Viktor Frankl'),
  (55, 2, 8, 'action', 'El 80% a propósito', 'Entrega o publica hoy algo al 80% deliberadamente: el informe sin la tercera revisión, el mensaje sin pulir dos veces. Observa que el mundo no se acaba.', 'El perfeccionismo es autosabotaje disfrazado de estándar: entrenar la entrega imperfecta rompe la parálisis.', 'Brené Brown'),
  (56, 2, 8, 'perception', 'Retro semana 8', '¿Qué parte de tu sombra ya puedes nombrar sin vergüenza? Escríbela en una frase en tercera persona ("hay una parte de mí que..."). ¿Qué parte sigue defendiéndose?', 'Nombrar la sombra sin vergüenza es la medida del trabajo hecho: lo integrado ya no necesita esconderse ni mandar.', 'Plan 90 días'),

  -- SEMANA 9: Incomodidad voluntaria
  (57, 3, 9, 'will', 'Premeditatio malorum', 'Visualiza en detalle y por escrito perder algo que valoras (el empleo, la salud de alguien, un proyecto). No como morbo: escribe cómo responderías con virtud, qué harías el primer día, qué quedaría en pie.', 'Ensayar la adversidad le quita el monopolio del miedo: el estoico no espera que la vida sea amable, se prepara para que no lo sea.', 'Séneca'),
  (58, 3, 9, 'will', 'Incomodidad física', 'Elige tu dosis de dificultad voluntaria hoy: ducha fría, entrenamiento más duro de lo cómodo, ayuno corto (si tu salud lo permite). El malestar es el ejercicio, no el efecto secundario.', 'La exposición deliberada a la dificultad entrena los cuatro pilares: tolerancia, contención, resiliencia y adaptabilidad.', 'Séneca / Solà'),
  (59, 3, 9, 'action', 'Habla donde callarías', 'Interviene hoy donde normalmente guardarías silencio por timidez o miedo a la desaprobación: la duda en la junta con directivos, la opinión técnica divergente, la pregunta "básica".', 'Tolerar la incomodidad del nerviosismo desensibiliza la respuesta de estrés social y fortalece la identidad de quien se muestra.', 'Séneca / Plan 90 días'),
  (60, 3, 9, 'will', 'Renuncia voluntaria', 'Renuncia hoy a un placer cotidiano que das por hecho: el café, el postre, la serie, la siesta. No por castigo: para comprobar que puedes y recordar que es un lujo, no una necesidad.', 'Practicar la renuncia periódica inmuniza contra la esclavitud de la comodidad y renueva el aprecio por lo que se tiene.', 'Séneca'),
  (61, 3, 9, 'will', 'Intención paradójica', 'Toma algo que te genera ansiedad anticipatoria (que te tiemble la voz, quedarte en blanco, sonrojarte) y deséalo deliberadamente hoy: intenta que te pase, exagéralo mentalmente hasta que dé risa.', 'La intención paradójica desmantela la ansiedad anticipatoria: lo que se desea con humor deja de poder amenazarte.', 'Viktor Frankl'),
  (62, 3, 9, 'action', 'Entrena el rechazo', 'Pide hoy algo sabiendo que probablemente te digan que no: un descuento, un favor grande, una excepción. El objetivo no es conseguirlo: es escuchar el no y comprobar que no pasa nada.', 'El miedo al rechazo gobierna más decisiones que el rechazo mismo: exponerse al no en dosis controladas lo desactiva.', 'Escalera social'),
  (63, 3, 9, 'perception', 'Retro semana 9', 'Puntúa de 1 a 10 tus cuatro pilares tras la semana de incomodidad: tolerancia (calma bajo presión), contención (estabilidad tras el golpe), resiliencia (velocidad de recuperación) y adaptabilidad (salir mejor). ¿Cuál subió?', 'Los pilares del carácter solo se miden en contacto con la dificultad: la semana te dio los datos.', 'Solà Pastor'),

  -- SEMANA 10: Misión trascendente
  (64, 3, 10, 'will', 'Valores de creación', 'Responde por escrito: ¿qué produces o aportas que trascienda tu comodidad? Define tu proyecto de sentido para esta temporada: algo que sirva a tu entorno (trabajo con propósito, mentoría, creación, voluntariado).', 'El sentido se realiza primero creando: el trabajo con propósito es la primera avenida de valores de Frankl.', 'Viktor Frankl'),
  (65, 3, 10, 'will', 'Valores de experiencia', 'Dedica hoy 30 minutos a recibir el mundo conscientemente: naturaleza sin celular, música con atención total, una conversación con presencia completa, arte contemplado de verdad.', 'El sentido también se recibe: el encuentro auténtico con la belleza y con otros es la segunda avenida de valores.', 'Viktor Frankl'),
  (66, 3, 10, 'will', 'Valores de actitud', 'Identifica tu sufrimiento inevitable actual (lo que no puedes cambiar: una pérdida, una condición, un contexto) y decide por escrito la actitud con la que lo vas a portar. Esa elección es tuya e inalienable.', 'Cuando no se puede cambiar la situación, el último reducto de libertad es la actitud: ahí la tragedia se convierte en logro.', 'Viktor Frankl'),
  (67, 3, 10, 'will', 'La vida te pregunta', 'Invierte la pregunta: en lugar de "¿qué me da la vida?", escribe qué te está exigiendo esta temporada (¿reconstruir salud? ¿ordenar finanzas? ¿reparar una relación? ¿crear algo?). Respóndele hoy con una acción.', 'La revolución copernicana de Frankl: no interrogas a la vida, la vida te interroga y tú respondes con actos.', 'Viktor Frankl'),
  (68, 3, 10, 'will', 'Misión en una frase', 'Redacta tu misión trascendente para esta temporada en una sola frase (quién te beneficias + qué haces + por qué importa). Pégala donde la veas a diario.', 'Sin misión clara para la etapa actual, las respuestas emocionales se vuelven mecanismos automáticos de evasión.', 'Lewis Howes'),
  (69, 3, 10, 'action', 'Servicio directo', 'Haz hoy algo por alguien que no pueda devolvértelo: tiempo, conocimiento, ayuda concreta, reconocimiento. Sin publicarlo ni cobrarlo.', 'La contribución es la necesidad más alta: dar sin retorno confirma que ya no operas desde la escasez.', 'Howes / Frankl'),
  (70, 3, 10, 'perception', 'Retro semana 10', 'Prueba de estrés de tu misión: ¿aguanta un día malo? ¿Te levantaría un lunes gris? Si no, refínala: más concreta, más tuya, menos impresionante para otros.', 'La misión de verdad se reconoce porque funciona precisamente cuando la motivación no está.', 'Plan 90 días'),

  -- SEMANA 11: Amor fati y memento mori
  (71, 3, 11, 'will', 'Memento mori', 'Medita 10 minutos sobre tu finitud: el tiempo es tu único recurso no renovable. Escribe: si te quedaran 52 semanas, ¿qué harías distinto esta misma semana? Haz hoy una de esas cosas.', 'La conciencia de la muerte no deprime al estoico: le pone precio real a cada hora y mata la procrastinación existencial.', 'Marco Aurelio'),
  (72, 3, 11, 'will', 'Amor fati', 'Toma tu revés más reciente y escríbelo como si lo hubieras elegido: "elegí que esto pasara porque me habilita a...". No es negación del dolor: es apropiación del destino.', 'Amor fati: no solo aceptar lo que pasa sino quererlo, porque es la materia prima de lo que vas a construir.', 'Nietzsche / Holiday'),
  (73, 3, 11, 'will', 'El obstáculo es el camino', 'Identifica tu impedimento número 1 actual y conviértelo en el ejercicio mismo: ¿te bloquea la falta de tiempo? Entrena priorización. ¿Un colega difícil? Entrena negociación. Escribe el plan y ejecuta el primer paso.', 'Lo que estorba a la acción hace avanzar la acción: el impedimento contiene exactamente el entrenamiento que necesitas.', 'Marco Aurelio / Holiday'),
  (74, 3, 11, 'will', 'La vista desde arriba', 'Ante tu problema más pesado, haz el ejercicio de perspectiva: visualízalo desde el techo, desde la ciudad, desde el país, desde el planeta, desde un siglo después. Escribe qué tamaño real tiene.', 'La vista cósmica no minimiza tu vida: recalibra el pánico de lo urgente frente a lo que de verdad importa.', 'Marco Aurelio'),
  (75, 3, 11, 'will', 'Gratitud enfocada', 'Escribe 3 gratitudes específicas de hoy conectadas a tu propósito (no "mi familia" en genérico: "la pregunta que me hizo X porque me obligó a pensar Y"). Detalle o no cuenta.', 'La gratitud específica entrena al cerebro a encontrar evidencia de sentido; la genérica se vuelve trámite.', 'Plan 90 días'),
  (76, 3, 11, 'will', 'El día diseñado', 'Vive hoy un día ordinario como si lo hubieras diseñado: presencia total en lo cotidiano (el café, el trayecto, la reunión, la cena). Cada vez que la mente huya al futuro, tráela.', 'La vida no está después del programa ni del proyecto: es esto. La presencia es el fin del entrenamiento, no su interrupción.', 'Estoicismo práctico'),
  (77, 3, 11, 'perception', 'Retro semana 11', 'Pregunta mayor: ¿qué adversidad de estos 77 días ya agradeces? Escribe cómo algo que parecía en contra terminó siendo a favor (o qué te enseñó).', 'Cuando puedes agradecer la adversidad pasada en concreto, el amor fati dejó de ser teoría.', 'Plan 90 días'),

  -- SEMANA 12: Entorno y Seis Fs
  (78, 3, 12, 'perception', 'Auditoría del círculo', 'Lista tus 10 relaciones más frecuentes. Junto a cada una marca: ¿eleva tu estándar o lo baja? ¿te acerca a tu contrato o a tu bucle? Sin juicio moral: solo dirección.', 'El sistema nervioso imita el estándar mínimo aceptado por su entorno de referencia: tu círculo es tu techo silencioso.', 'Solà / Martell'),
  (79, 3, 12, 'action', 'Curaduría relacional', 'Ejecuta una decisión de la auditoría: reduce deliberadamente el contacto con una influencia de evasión y agenda tiempo real con una persona que eleve tu estándar.', 'La depuración del entorno no es soberbia: es proteger el sistema que estás construyendo mientras se consolida.', 'Adrià Solà Pastor'),
  (80, 3, 12, 'perception', 'Las Seis Fs', 'Puntúa de 1 a 10 tus seis áreas: Fe (propósito/trascendencia), Familia y amigos, Fitness (energía física), Finanzas, Futuro yo (aprendizaje), Fun (recreación sana). Identifica la más baja.', 'El crecimiento desbalanceado se cobra después: la F más baja es la fuga por donde se drenará todo lo demás.', 'Dan Martell'),
  (81, 3, 12, 'action', 'Acción en tu F débil', 'Ejecuta hoy una acción concreta en tu área más baja: la llamada a la familia, la cita médica, el presupuesto, la clase, el plan de diversión sana. Hoy, no esta semana.', 'La F débil no mejora con conciencia sino con la primera acción incómoda y concreta.', 'Dan Martell'),
  (82, 3, 12, 'action', 'Soberanía financiera', 'Revisa tus gastos del último mes: ¿cuánto fue consumo inmediato (dopamina) y cuánto construcción de sistemas (ahorro, inversión, educación)? Haz un ajuste concreto hoy.', 'La psicología financiera del consumo inmediato es el mismo bucle de dopamina con otro disfraz: la soberanía del tiempo se compra con sistemas.', 'Howes / Martell'),
  (83, 3, 12, 'action', 'Enseña lo aprendido', 'Comparte hoy con alguien (colega, amigo, familiar) la herramienta de estos 90 días que más te sirvió: enséñale el protocolo, el examen nocturno o la dicotomía. Enseñar consolida.', 'Lo que puedes enseñar con claridad es lo único que de verdad aprendiste: y contribuir cierra el círculo del sentido.', 'Frankl / Plan 90 días'),
  (84, 3, 12, 'perception', 'Retro semana 12', '¿Tu entorno (personas, espacios, pantallas, agenda) ya sostiene tu estándar mínimo o todavía lo sabotea? Lista lo que queda por depurar y agenda cuándo.', 'Al final, no te sostiene la motivación sino la arquitectura: entorno, agenda, círculo y contrato.', 'Plan 90 días'),

  -- SEMANA 13: Evaluación final
  (85, 3, 13, 'evaluation', 'Kit de prevención de recaídas', 'Crea tu documento de emergencia: tus 3 gatillos principales, tus planes if-then, el protocolo de 5 pasos, tus citas estoicas de guardia y 2 contactos de apoyo. Una página, accesible siempre.', 'La recaída no se previene con confianza sino con protocolo: el kit es tu plan de contingencia escrito en tiempos de paz.', 'Evaluación'),
  (86, 3, 13, 'evaluation', 'Relectura del día 1', 'Relee tu diario de identidad del día 1. Escribe la distancia recorrida: ¿qué creencia limitante murió? ¿qué haces hoy con naturalidad que entonces parecía imposible? ¿qué sigue igual?', 'Medir la distancia contra tu propio punto de partida (no contra un ideal) es la evaluación honesta.', 'Evaluación'),
  (87, 3, 13, 'evaluation', 'Carta al día 180', 'Escribe una carta a tu yo de dentro de 90 días: qué debe seguir haciendo sin negociar, qué señales de recaída debe vigilar, qué le agradeces por no haberse rendido.', 'La carta al futuro fija el estándar y crea un pacto entre versiones de ti: el mejor guardián de tu progreso eres tú, con memoria.', 'Evaluación'),
  (88, 3, 13, 'evaluation', 'Contrato 2.0', 'Actualiza tu contrato sagrado con lo aprendido: qué cláusulas suben de estándar, cuáles se ajustan a la realidad, cuál nueva entra. Fírmalo de nuevo.', 'El contrato es un documento vivo: la versión 2.0 con evidencia real vale más que la 1.0 con esperanza.', 'Evaluación'),
  (89, 3, 13, 'evaluation', 'La siguiente temporada', 'Diseña la siguiente temporada: no otro sprint de 90 días, sino el sistema sostenible (qué prácticas quedan a diario, cuáles semanales, cuál es tu estándar mínimo permanente).', 'Los 90 días fueron el andamio; el edificio es la vida ordinaria con el sistema integrado.', 'Evaluación'),
  (90, 3, 13, 'evaluation', 'Evaluación final de 90 días', 'Abre el informe de 90 días en la app: progreso por módulo, rachas, días perdidos, frecuencia de journaling, estados de ánimo. Escribe tu retro final: quién eras, quién eres, quién sigues construyendo.', 'El ciclo se cierra con datos y con narrativa: la evidencia dice qué pasó, tu relato decide qué significa.', 'Evaluación')
) AS v(day_number, phase, week, module, title, instructions, rationale, source_author)
ON CONFLICT (track_id, day_number) DO NOTHING;

-- ------------------------------------------------------------
-- RETOS SEMANALES (13)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'interna')
INSERT INTO stoic.program_weeks (track_id, week_number, theme, challenge_title, challenge_description, deliverable)
SELECT t.id, v.week_number, v.theme, v.challenge_title, v.challenge_description, v.deliverable
FROM t, (VALUES
  (1, 'Conciencia y diagnóstico', 'Mapea tu bucle número 1', 'Completa el diario de identidad y el mapa completo de tu principal bucle de evasión: disparador, emoción, conducta, recompensa y ganancia secundaria.', 'Texto de identidad (día 1) + tabla del bucle + declaración de guerra escrita.'),
  (2, 'Sustracción', 'Siete días sin tu evasor primario', 'Elimina tu evasor primario los 7 días con fricción física instalada, y cumple el estándar mínimo viable a diario.', 'Registro de días limpios + horas rojas recuperadas vs semana 1.'),
  (3, 'Dicotomía del control', 'Instala los dos exámenes', 'Haz el examen matutino (Marco Aurelio) y el nocturno (Séneca) al menos 5 de 7 días, más un día completo de queja cero.', 'Bitácora de exámenes + registro del día de queja cero.'),
  (4, 'Regulación somática', 'Surfea cinco olas', 'Usa el protocolo de 5 pasos y el surf de olas de ansia ante al menos 5 impulsos reales sin ceder.', 'Registro de impulsos: gatillo, intensidad, duración de la ola, resultado.'),
  (5, 'Contrato de identidad', 'Firma tu contrato sagrado', 'Redacta y firma tu contrato de autoconcepto, léelo en voz alta mañana y noche toda la semana, y haz tu compromiso público con un testigo.', 'El contrato escrito y firmado + nombre de tu testigo y fecha del chequeo semanal.'),
  (6, 'Identidad en acción', 'Siete evidencias', 'Acumula 7 evidencias numeradas de la nueva identidad en acción (una por día): cosas que solo haría la persona de tu contrato.', 'Lista numerada de las 7 evidencias con fecha.'),
  (7, 'Bucles competidores', 'Un día de dieta de dopamina', 'Completa un día entero de dieta de dopamina y al menos 3 bloques de trabajo profundo de 90 minutos en la semana.', 'Registro del día de dieta (qué sentiste, qué urgencias subieron) + los 3 bloques.'),
  (8, 'Trabajo con la sombra', 'El proceso completo', 'Completa las cuatro etapas con tu patrón de autosabotaje: admitir, observar, ventilar (la carta no enviada) y reformular (la narrativa nueva).', 'La narrativa reescrita: qué fortaleza construyó en ti la herida.'),
  (9, 'Incomodidad voluntaria', 'Tres actos de dificultad elegida', 'Ejecuta al menos 3 incomodidades voluntarias: una física (frío/ayuno/entrenamiento), una social (hablar donde callarías o pedir sabiendo el no) y una de renuncia.', 'Registro de los 3 actos + puntaje 1-10 de los cuatro pilares del carácter.'),
  (10, 'Misión trascendente', 'Tu misión en una frase', 'Redacta tu misión de temporada en una frase, iníciala con una primera acción concreta de tu proyecto de sentido y haz un acto de servicio sin retorno.', 'La frase de misión (pegada y visible) + la primera acción ejecutada.'),
  (11, 'Amor fati y memento mori', 'Práctica diaria de perspectiva', 'Cada día de la semana, una práctica: memento mori, amor fati del último revés, el obstáculo como camino, la vista desde arriba, gratitud específica.', 'Siete entradas de diario, una por práctica.'),
  (12, 'Arquitectura del entorno', 'Depura y balancea', 'Completa la auditoría del círculo con una decisión ejecutada, puntúa tus Seis Fs y ejecuta una acción en la más débil.', 'Lista de relaciones con dirección (eleva/baja) + puntaje de las Seis Fs + acción hecha.'),
  (13, 'Evaluación final', 'Cierre y sistema sostenible', 'Crea tu kit de prevención de recaídas, escribe la carta al día 180, firma el contrato 2.0 y completa la evaluación final en la app.', 'Kit de recaídas + carta al día 180 + contrato 2.0 + retro final escrita.')
) AS v(week_number, theme, challenge_title, challenge_description, deliverable)
ON CONFLICT (track_id, week_number) DO NOTHING;

-- ------------------------------------------------------------
-- HITOS MENSUALES (3)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'interna')
INSERT INTO stoic.program_months (track_id, month_number, title, description)
SELECT t.id, v.month_number, v.title, v.description
FROM t, (VALUES
  (1, 'Descompresión: conciencia y sustracción', 'Mapear el bucle de evasión, sustraer el evasor primario, instalar el estándar mínimo viable y los exámenes matutino y nocturno, y dominar el protocolo de regulación ante impulsos. Hito verificable: 21 o más días del mes con el estándar mínimo viable cumplido y el bucle mapeado con datos reales.'),
  (2, 'Identidad: el contrato en operación', 'Redactar y operar el contrato sagrado de autoconcepto con la Regla del 300%, construir bucles competidores (sustitución, fricción inversa, trabajo profundo) e integrar la sombra (admitir, observar, ventilar, reformular). Hito verificable: racha de 14 días sin ceder al bucle principal + 7 evidencias numeradas de la nueva identidad.'),
  (3, 'Trascendencia: propósito y sistema sostenible', 'Definir la misión trascendente y el proyecto de sentido (Frankl), practicar amor fati y memento mori, depurar el entorno relacional, balancear las Seis Fs y cerrar con el kit de prevención de recaídas y el contrato 2.0. Hito verificable: proyecto de sentido en marcha + kit de recaídas terminado + evaluación final completada.')
) AS v(month_number, title, description)
ON CONFLICT (track_id, month_number) DO NOTHING;
