-- ============================================================
-- StoiCom V12 - Track 3: Influencia (temporada avanzada, 30 días)
-- 30 días + 5 retos semanales + 1 hito
-- Fuentes: Tony Robbins (Poder sin límites: anclaje cap.17,
--          redefinición del marco cap.16, metaprogramas cap.14,
--          precisión del lenguaje cap.12; Controle su destino:
--          reglas y valores cap.15-16, emociones cap.11) + Epicteto.
-- Contenido original: frameworks citados por nombre, sin reproducir
-- texto de los libros. Generado desde scratchpad/seed-influencia.mjs.
-- Idempotente: re-ejecutar ACTUALIZA el contenido existente.
-- ============================================================

INSERT INTO stoic.tracks (slug, name, description, duration_days)
VALUES ('influencia', 'Influencia', 'La temporada avanzada: 30 días para dirigir el estado, el marco y la decisión — los tuyos y los de la mesa. Anclaje, redefinición del marco, precisión del lenguaje y metaprogramas de Robbins, sobre la disciplina estoica que ya instalaste. Para quien terminó sus primeros 90 días.', 30)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  duration_days = EXCLUDED.duration_days;

-- ------------------------------------------------------------
-- DÍAS (30)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'influencia')
INSERT INTO stoic.program_days (track_id, day_number, phase, week, module, title, instructions, rationale, source_author)
SELECT t.id, v.day_number, v.phase, v.week, v.module, v.title, v.instructions, v.rationale, v.source_author
FROM t, (VALUES
  (1, 1, 1, 'perception', 'Inventario de estados', 'Dibuja dos columnas. Izquierda: los tres estados en los que rindes al máximo — nómbralos con precisión ("certeza tranquila", no "bien") y anota la última vez que cada uno apareció: dónde estabas, qué hacías, qué postura tenías. Derecha: los tres estados que te sabotean en conversaciones importantes, con la misma precisión forense. Elige de la izquierda EL estado que más falta te hace cuando hablas bajo presión: ese vas a instalarlo mañana.', 'No puedes anclar lo que no sabes nombrar. Robbins parte de aquí: el estado es la materia prima del desempeño, y la mayoría no tiene ni vocabulario para los suyos. El inventario convierte "a veces estoy encendido" en un mapa utilizable.', 'Tony Robbins — anclaje de estado'),
  (2, 1, 1, 'will', 'Instala el ancla', 'A solas, de pie: revive el recuerdo más intenso del estado que elegiste ayer. Métete en la escena — lo que veías, lo que oías, cómo respirabas — y amplifícala con el cuerpo entero: espalda, respiración, mandíbula, voz. Cuando la intensidad llegue al pico (no antes, no después), dispara tu ancla: un gesto único que no uses en la vida diaria — presión de pulgar y anular, puño contra el muslo — junto a una palabra dicha en voz baja. Suelta, rompe el estado caminando unos pasos, y repite el ciclo completo cinco veces.', 'El ancla es asociación pura: estímulo único + estado en su punto máximo + repetición. Robbins es taxativo con el momento — instalada en la subida o en la bajada, el ancla queda ligada a un estado tibio. En el pico o no sirve.', 'Tony Robbins — anclaje de estado'),
  (3, 1, 1, 'will', 'Prueba de fuego', 'Hoy, en frío y sin preparar nada, dispara el ancla: mismo gesto, misma palabra. Mide cuánto del estado vuelve (1-10). Siete o más: tienes ancla — refuérzala una vez más en el pico. Menos de siete: reinstala desde cero con un recuerdo más intenso o un gesto más distintivo. El error casi siempre está en haber disparado fuera del pico o en usar un gesto que ya haces todo el día.', 'Un ancla sin probar es una superstición. La prueba en frío separa la asociación real del efecto placebo de la sesión: si no enciende el estado sin contexto, no va a encenderlo en una sala de juntas.', 'Tony Robbins — anclaje de estado'),
  (4, 1, 1, 'action', 'El ancla antes de hablar', 'Elige la conversación más exigente de tu día — la llamada que vienes aplazando, la junta donde sueles encogerte — y dispara el ancla en los noventa segundos previos: en el pasillo, en el auto, antes de abrir la puerta. Entra mientras el estado sigue arriba. Después anota: intensidad del estado al entrar, y qué cambió en tu voz y en tu postura comparado con tu entrada habitual.', 'El estado se instala antes del evento, no durante: adentro ya estás reaccionando. Los noventa segundos previos son la única ventana que controlas por completo — y casi todos la gastan repasando miedos.', 'Tony Robbins — anclaje de estado'),
  (5, 1, 1, 'will', 'Apila estados', 'Suma un segundo estado a la misma ancla. Repite el proceso del día 2 con un recuerdo distinto — si anclaste certeza, apila calma; si anclaste calma, apila decisión — disparando el mismo gesto y la misma palabra en el pico. Tres ciclos bastan. Al final, prueba en frío: el disparo debe traer una mezcla más densa que la de ayer.', 'Las anclas se apilan: cada estado añadido en el pico se suma a la asociación en lugar de reemplazarla. Un ancla con tres estados apilados es una herramienta distinta a la del primer día — más gruesa, más difícil de tumbar por el contexto.', 'Tony Robbins — anclaje de estado'),
  (6, 1, 1, 'action', 'Ancla bajo fuego', 'Hoy el disparo no es preventivo: es correctivo. En el momento exacto en que detectes el estado saboteador — el acelerón del pecho cuando te contradicen, el impulso de encogerte cuando alguien sube la voz — dispara el ancla en plena conversación. El gesto es discreto por diseño: nadie tiene que notarlo. Registra después: ¿cuánto tardaste en detectar el estado? ¿Cuánto recuperaste tras el disparo (1-10)?', 'La prueba real de un ancla no es el pasillo sino el fuego: interrumpir un estado en caída y montarle otro encima. Detectar el sabotaje a tiempo es la mitad del ejercicio — el estoico lo llamaba vigilar el asentimiento; Robbins le puso un gatillo físico.', 'Tony Robbins — anclaje de estado'),
  (7, 1, 1, 'perception', 'Retro semana 1: el interruptor', 'Relee tus registros de la semana y responde con números: ¿cuántas veces disparaste el ancla en situaciones reales? ¿Qué intensidad media recuperaste? ¿Cuál disparo te sorprendió y cuál falló? Decide por escrito el mantenimiento: una reinstalación breve por semana, en el pico de un estado real — los mejores momentos de tu semana son munición, no solo recuerdos.', 'Un ancla sin mantenimiento se diluye con los meses. La revisión semanal con números separa la herramienta que ya opera de la que solo funcionó una vez en el sofá.', 'Plan Influencia'),
  (8, 1, 2, 'perception', 'Detecta el marco', 'Toma las tres situaciones que más te pesan esta semana y escribe, para cada una, la frase exacta con que te las cuentas — "me van a evaluar", "otra junta perdida", "tengo que convencerlo". Subraya el verbo y el sustantivo que cargan el peso. Ese es el marco. Todavía no lo cambies: solo constata cuánto de tu estado viene de la frase y no del hecho.', 'Nadie responde a los hechos: responde al marco que los envuelve. Antes de redefinir hay que ver el marco actual con nitidez — es la parte que casi todos se saltan, y por eso sus reencuadres suenan a autoengaño.', 'Tony Robbins — redefinición del marco'),
  (9, 1, 2, 'perception', 'Redefinición de contexto', 'Elige el rasgo tuyo que más te han criticado — terco, intenso, callado, impaciente — y encuentra tres contextos reales donde ese mismo rasgo es una ventaja pagada: la terquedad en una negociación larga, el silencio en una sala que sobre-habla. Escríbelos con situación concreta. Cierra respondiendo: ¿en qué contexto estoy operando yo, y cuál me conviene invocar?', 'Ninguna conducta tiene valor fijo: vale según el escenario. La redefinición de contexto no te pide cambiar — te pide reubicar. Es la maniobra más barata del repertorio: el rasgo ya lo tienes; lo que cambia es dónde lo pones a trabajar.', 'Tony Robbins — redefinición del marco'),
  (10, 1, 2, 'perception', 'Redefinición de contenido', 'Toma el hecho más incómodo de tu mes — el error, el rechazo, el silencio de alguien — y escribe cinco significados alternativos que el mismo hecho soporta sin mentir: "no respondió" puede significar desinterés, saturación, delegación, olvido o miedo. Elige el significado más útil que siga siendo honesto y actúa hoy una vez desde él.', 'El hecho es idéntico; lo que te paraliza es el significado que le asignaste — casi siempre el primero que llegó, no el más probable. Generar cinco antes de elegir rompe el monopolio de la primera interpretación. Epicteto lo dijo primero: no te perturba lo que pasa, sino tu juicio sobre lo que pasa.', 'Tony Robbins — redefinición del marco'),
  (11, 2, 2, 'action', 'Reencuadre en voz alta', 'Hoy, cuando alguien te traiga una queja o un problema, valida el hecho primero — sin saltarte este paso — y luego ofrece un marco distinto en una sola frase: "es un retraso, sí; también es la única revisión honesta que va a tener este proyecto antes de salir". Una vez hoy, con alguien real. Registra la reacción exacta: ¿siguió la conversación por el marco nuevo o volvió al viejo?', 'El reencuadre dicho antes de validar suena a descarte y genera resistencia; dicho después, suena a perspectiva. La medida del éxito no es que aplaudan tu frase: es por cuál marco continúa la conversación.', 'Tony Robbins — redefinición del marco'),
  (12, 2, 2, 'action', 'El marco previo', 'Antes de tu reunión o conversación más importante de hoy, fija el marco en la primera frase — antes de que otro lo haga: "esto no es una revisión de culpas; es la decisión de qué hacemos con lo que ya sabemos". Prepárala por escrito, dila al abrir, y observa cuánto del resto de la conversación ocurre dentro del marco que pusiste.', 'Toda conversación opera dentro de algún marco; la única pregunta es quién lo puso. El que llega sin marco hereda el del otro — y después pelea cuesta arriba contra él. Fijarlo en la primera frase cuesta diez segundos de valentía y ahorra una hora de defensa.', 'Tony Robbins — redefinición del marco'),
  (13, 2, 2, 'will', 'El marco estoico', 'Practica el reencuadre hacia adentro y en tiempo real: tres veces hoy, ante cualquier fricción — el correo seco, el tráfico, la interrupción — di mentalmente el hecho desnudo ("recibí un correo de dos líneas") antes que el juicio ("me está ignorando"). Luego elige el marco a conciencia. Anota las tres al final del día: hecho, primer juicio automático, marco elegido.', 'La disciplina del asentimiento estoica y la redefinición del marco son la misma operación con siglos de distancia: separar la impresión del juicio, y firmar el juicio a mano en vez de dejar que se firme solo. Entrenarla con fricciones pequeñas la vuelve disponible en las grandes.', 'Tony Robbins — redefinición del marco / Epicteto'),
  (14, 2, 2, 'perception', 'Retro semana 2: quién puso el marco', 'Repasa la semana y lista tus últimas cinco conversaciones importantes. Para cada una responde una sola pregunta: ¿quién puso el marco — tú, el otro, o nadie (y entonces lo puso la inercia)? Cuenta el marcador. Escribe la frase de apertura que usarás en la conversación más importante de la semana entrante.', 'El marcador de quién enmarca es el diagnóstico más rápido de tu posición en cualquier mesa. No mide elocuencia: mide iniciativa. Y la frase preparada convierte la lección en munición para el lunes.', 'Plan Influencia'),
  (15, 2, 3, 'perception', 'Caza de generalizaciones', 'Hoy solo escucha y registra: cada "siempre", "nunca", "todos", "nadie", "imposible" que oigas — en otros y en ti. Anota la frase completa y quién la dijo. No corrijas a nadie todavía. Al final del día cuenta cuántas capturaste y marca las dos que más decisiones están dirigiendo: una ajena y una tuya.', 'La generalización borra la información que la contradice: "siempre llega tarde" borra las veces que no. El lenguaje impreciso produce mapas imprecisos, y la gente decide sobre el mapa, no sobre el territorio. Cazarlas sin corregirlas entrena el oído sin gastar pólvora.', 'Tony Robbins — precisión del lenguaje'),
  (16, 2, 3, 'action', 'Las preguntas de precisión', 'Usa dos veces hoy, en conversación real, una pregunta que recupere lo borrado — con curiosidad genuina, no como fiscal. A un "todos están molestos": "¿quiénes exactamente?". A un "esto nunca funciona": "¿nunca, o no funcionó las últimas dos veces?". A un "es imposible": "¿qué lo impide, concretamente?". Registra qué información apareció que la frase original tapaba.', 'La pregunta de precisión no discute la frase: le pide al mapa que muestre el territorio. Casi siempre lo que aparece es más manejable que lo que la generalización pintaba — y el otro llega solo a esa conclusión, que es la única forma en que la acepta.', 'Tony Robbins — precisión del lenguaje'),
  (17, 2, 3, 'action', 'Los comparativos huérfanos', 'Caza hoy los comparativos sin referencia — "esto es muy caro", "él es mejor", "vamos demasiado lento" — y devuélveles la vara: "¿caro comparado con qué?", "¿mejor en qué, exactamente?", "¿lento respecto a qué plan?". Úsalo al menos una vez con otro y una vez contigo: tu propio "no estoy avanzando" también esconde la vara con la que te mides.', 'Todo juicio comparativo esconde un estándar no dicho, y quien controla el estándar controla la conclusión. Sacar la vara a la luz convierte una sentencia en una conversación sobre criterios — que es donde de verdad se negocia.', 'Tony Robbins — precisión del lenguaje'),
  (18, 2, 3, 'perception', 'Metaprograma: hacia o desde', 'Detecta hoy, en dos personas con las que hables, su dirección de motivación: ¿hablan de lo que quieren lograr (hacia) o de lo que quieren evitar (desde)? Escucha los verbos: "ganar, crecer, lograr" contra "evitar, cubrirnos, que no falle". Anota la evidencia de cada uno. No cambies todavía tu discurso: solo clasifica.', 'Los metaprogramas son los filtros con que cada quien decide qué escuchar. El de dirección es el más audible: al de "hacia" lo aburres con riesgos, al de "desde" lo asustas con visiones. Detectarlo lleva dos minutos de atención; ignorarlo cuesta la venta entera.', 'Tony Robbins — metaprogramas'),
  (19, 2, 3, 'perception', 'Metaprograma: interno o externo', 'Detecta hoy el marco de referencia de dos personas: cuando deciden, ¿consultan su propio criterio ("yo lo veo así") o buscan validación afuera ("¿tú qué opinas?", "¿qué hicieron los demás?")? Si hace falta, pregunta: "¿cómo sabes que un trabajo quedó bien hecho?". La respuesta es el diagnóstico. Anota ambos.', 'Al de referencia interna no lo convences con testimonios: se lo tiene que decir su propio criterio — dale datos y espacio. Al de referencia externa dale casos, nombres y respaldo. El mismo argumento que persuade a uno le resbala al otro; no es el argumento, es el filtro.', 'Tony Robbins — metaprogramas'),
  (20, 2, 3, 'action', 'Preséntalo en su idioma', 'Toma una propuesta real que necesites vender esta semana — a tu jefe, a tu pareja, a un cliente — y prepárala en el metaprograma del receptor según tu diagnóstico: al "desde", abre con el riesgo de no actuar; al "hacia", con el resultado; al interno, con datos y un "tú decides"; al externo, con quién más lo hizo. Preséntala hoy y registra la diferencia contra tu versión habitual.', 'No hay mensajes persuasivos en abstracto: hay mensajes que atraviesan el filtro del receptor o rebotan en él. Presentar en su metaprograma no cambia tu propuesta ni una coma — cambia el orden y el énfasis. Es traducción, no manipulación.', 'Tony Robbins — metaprogramas'),
  (21, 3, 3, 'perception', 'Retro semana 3: el mapa del otro', 'Haz la ficha de las tres personas que más necesitas influir este año: ¿hacia o desde? ¿Interno o externo? ¿Qué generalizaciones repiten? ¿Qué vara esconden sus juicios? Una ficha por persona, cuatro líneas cada una, basada en evidencia de esta semana — no en tu opinión de ellos. Guárdalas: son tu preparación permanente para cualquier conversación futura con cada uno.', 'Improvisar la lectura del otro en plena conversación es tarde. La ficha convierte una semana de observación en preparación permanente — y te obliga a distinguir lo que oíste de lo que supones.', 'Plan Influencia'),
  (22, 3, 4, 'perception', 'Jerarquía de valores', 'Responde por escrito: ¿qué es lo más importante para ti en la vida? Lista todo lo que salga — libertad, seguridad, respeto, aventura, tranquilidad — y luego ordénalo a la fuerza: si solo pudieras conservar uno, ¿cuál? ¿Y el siguiente? Quédate con tu top 5 ordenado. Después compara: ¿tu semana real — horas, decisiones, peleas — refleja ese orden o uno distinto?', 'Robbins llama a los valores la brújula personal: decides con ellos aunque nunca los hayas listado. La incongruencia entre el orden que declaras y el que vives es la fuente de fricción interna más común — y no se corrige sin verla escrita.', 'Tony Robbins — reglas y valores'),
  (23, 3, 4, 'perception', 'Las reglas del juego', 'Toma tus dos valores más altos de ayer y escribe, con honestidad forense, qué tiene que pasar para que sientas que se cumplen. "¿Cuándo te sientes respetado?" — si la respuesta es "cuando nadie me interrumpe jamás y todos reconocen mi trabajo", tienes una regla que depende de otros y exige unanimidad. Marca cada regla tuya que sea imposible, ajena o invisible para los demás.', 'La frustración casi nunca viene del valor: viene de la regla que le pusiste. Dos personas con el mismo valor y reglas distintas viven vidas opuestas — una lo cumple a diario, la otra no lo alcanza nunca. Las reglas son el código fuente de tus emociones, y casi nadie ha leído el suyo.', 'Tony Robbins — reglas y valores'),
  (24, 3, 4, 'will', 'Reescribe la regla', 'Reescribe tus reglas marcadas ayer con dos criterios estoicos: que dependan de ti, y que sean alcanzables cualquier día. "Me siento respetado cuando digo lo que pienso aunque tiemble" depende de ti; "cuando todos me escuchan" no. Una regla nueva por cada valor del top 2, escrita y a la vista. Hoy mismo cúmplelas una vez.', 'Es la dicotomía del control aplicada al diseño emocional: Epicteto separa lo que depende de ti de lo que no; Robbins te hace escribir la regla para que la emoción dependa de lo primero. Una regla bajo tu control convierte el valor de lotería en rutina.', 'Tony Robbins — reglas y valores / Epicteto'),
  (25, 3, 4, 'perception', 'Las reglas ajenas', 'Piensa en la persona cercana que más se molesta "sin razón" contigo y hazte la pregunta que nunca te has hecho: ¿cuál es su regla? ¿Qué tiene que pasar, en su código, para sentirse respetada o tomada en cuenta? Si puedes, averígualo hoy directamente: "¿qué hago yo que te hace sentir que no te tomo en serio?". Escucha sin defenderte y anota la regla que descubras.', 'La mayoría de los conflictos crónicos no son choques de valores — ambos quieren respeto — sino de reglas invisibles sobre cómo se demuestra. Descubrir la regla del otro suele disolver en una conversación lo que años de discutir el valor no tocaron.', 'Tony Robbins — reglas y valores'),
  (26, 3, 4, 'will', 'La emoción como señal', 'Cada emoción incómoda de hoy pasa por tres preguntas antes de cualquier reacción: ¿qué me está señalando? ¿Qué acción me pide? ¿La tomo o la pospongo a conciencia? La culpa señala una norma propia violada — repárala. El miedo, preparación pendiente — prepárate. La frustración, un método agotado — cambia de método sin cambiar de meta. Registra al menos tres señales con su acción.', 'Robbins trata cada emoción dolorosa como un mensajero con encargo, no como un defecto a suprimir. Es la lectura estoica en versión operativa: la emoción es un juicio — atiende el juicio y la emoción cumplió su función. Suprimirla es matar al mensajero y quedarse sin el mensaje.', 'Tony Robbins — la emoción como señal'),
  (27, 3, 4, 'will', 'Emociones por diseño', 'Elige tres emociones de poder — gratitud, curiosidad, determinación — y prográmalas: a las 8, a las 13 y a las 18 (pon alarmas), cultiva la que toque durante dos minutos con cuerpo incluido. Gratitud: tres cosas concretas de hoy y a quién se las debes. Curiosidad: una pregunta genuina sobre algo que dabas por sabido. Determinación: tu ancla más la primera acción de la tarea que evitas.', 'Si las emociones dolorosas son señales, las de poder son herramientas — y no llegan solas: se cultivan a horas fijas hasta que el surco existe. Programarlas parece mecánico exactamente hasta la semana en que empiezan a aparecer sin alarma.', 'Tony Robbins — la emoción como señal'),
  (28, 3, 4, 'perception', 'Retro semana 4: el código fuente', 'Consolida tu sistema en una página: top 5 de valores en orden, las reglas reescritas de los dos primeros, la regla descubierta de tu persona difícil, y las tres señales emocionales que más se repitieron con su acción pendiente. Esa página es tu código fuente documentado. Revisa: ¿alguna acción pendiente lleva más de tres días? Prográmala.', 'Un sistema que solo existe en la cabeza se renegocia solo cada vez que conviene. La página escrita es el contrato contra esa renegociación — y la lista de acciones pendientes es donde se ve si las señales se atienden o solo se coleccionan.', 'Plan Influencia'),
  (29, 3, 5, 'evaluation', 'Examen de influencia', 'Elige LA conversación importante que tengas pendiente y ejecútala hoy con el sistema completo: ancla en los noventa segundos previos, marco fijado en tu primera frase, al menos una pregunta de precisión en el medio, y la propuesta presentada en el metaprograma del otro. Prepara por escrito antes; registra por escrito después: qué disparaste, qué aterrizó, qué se te olvidó bajo presión.', 'Las herramientas por separado ya las probaste; el examen es la orquesta. Lo que se te olvide bajo presión es el diagnóstico exacto de qué necesita más repetición — por eso el registro posterior vale tanto como la conversación misma.', 'Plan Influencia'),
  (30, 3, 5, 'evaluation', 'El protocolo permanente', 'Escribe tu protocolo de influencia en una página, en presente y en tus palabras: qué ancla usas y cuándo la mantienes, qué frase de apertura enmarca tus reuniones tipo, tus dos preguntas de precisión de cabecera, las fichas de metaprograma de tus tres personas clave, tus reglas reescritas. Cierra con la fecha de tu próxima revisión completa: en 30 días, en tu calendario, hoy.', 'Un track termina; un protocolo opera. La diferencia entre haber hecho un programa y haber cambiado el repertorio es este documento: corto, tuyo, con fecha de mantenimiento. La influencia sin ética se pudre sola — la tuya queda atada a las reglas que dependen de ti.', 'Plan Influencia')
) AS v(day_number, phase, week, module, title, instructions, rationale, source_author)
ON CONFLICT (track_id, day_number) DO UPDATE SET
  phase = EXCLUDED.phase, week = EXCLUDED.week, module = EXCLUDED.module,
  title = EXCLUDED.title, instructions = EXCLUDED.instructions,
  rationale = EXCLUDED.rationale, source_author = EXCLUDED.source_author;

-- ------------------------------------------------------------
-- SEMANAS (5)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'influencia')
INSERT INTO stoic.program_weeks (track_id, week_number, theme, challenge_title, challenge_description, deliverable)
SELECT t.id, v.week_number, v.theme, v.challenge_title, v.challenge_description, v.deliverable
FROM t, (VALUES
  (1, 'El estado a demanda', 'Tres disparos reales', 'Usa tu ancla instalada antes de tres momentos reales de presión esta semana — una junta, una llamada difícil, una conversación pendiente — y registra en cada uno la intensidad del estado (1-10) antes y después del disparo.', 'Registro de los tres disparos con intensidad antes/después'),
  (2, 'El marco manda', 'El reencuadre en público', 'Reencuadra en voz alta, delante de al menos dos personas, una queja o un problema que traiga otro — validando el hecho primero, cambiando lo que significa después — y observa si la conversación cambia de dirección.', 'Un reencuadre hecho ante dos o más personas, con la reacción registrada'),
  (3, 'Leer al otro', 'La pregunta quirúrgica', 'Disuelve una generalización ajena ("siempre", "todos", "imposible") con una sola pregunta de precisión, sin confrontar, y registra qué información apareció que la frase original escondía.', 'Tres fichas de metaprograma basadas en evidencia de la semana'),
  (4, 'El sistema maestro', 'La regla dicha en voz alta', 'Cuéntale a alguien de confianza una regla imposible que descubriste en ti y cómo la reescribiste. Decirla en voz alta la convierte en contrato.', 'La página de código fuente: valores ordenados, reglas reescritas, señales con acción'),
  (5, 'Integración', 'La conversación completa', 'Ejecuta la conversación del día 29 con todas las herramientas del track y registra el resultado por escrito: es el examen final de la temporada.', 'El protocolo permanente escrito, con fecha de revisión en el calendario')
) AS v(week_number, theme, challenge_title, challenge_description, deliverable)
ON CONFLICT (track_id, week_number) DO UPDATE SET
  theme = EXCLUDED.theme, challenge_title = EXCLUDED.challenge_title,
  challenge_description = EXCLUDED.challenge_description, deliverable = EXCLUDED.deliverable;

-- ------------------------------------------------------------
-- HITO (1)
-- ------------------------------------------------------------
WITH t AS (SELECT id FROM stoic.tracks WHERE slug = 'influencia')
INSERT INTO stoic.program_months (track_id, month_number, title, description)
SELECT t.id, 1, 'Influencia: el sistema integrado', 'Instalar y probar el ancla de estado en situaciones reales; fijar el marco antes de que lo fije otro; recuperar con preguntas de precisión la información que las generalizaciones borran; presentar propuestas en el metaprograma del receptor; y reescribir las reglas propias para que las emociones dependan de lo que está bajo tu control. Hito verificable: el examen de influencia del día 29 ejecutado y el protocolo permanente escrito con fecha de revisión.'
FROM t
ON CONFLICT (track_id, month_number) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description;

SELECT 'track influencia sembrado' AS resultado,
  (SELECT count(*) FROM stoic.program_days d JOIN stoic.tracks t ON t.id = d.track_id WHERE t.slug = 'influencia') AS dias,
  (SELECT count(*) FROM stoic.program_weeks w JOIN stoic.tracks t ON t.id = w.track_id WHERE t.slug = 'influencia') AS semanas;
